#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

#define OBJ_EVENT_GFX_BRENDAN_NORMAL               0
#define OBJ_EVENT_GFX_BRENDAN_MACH_BIKE            1
#define OBJ_EVENT_GFX_BRENDAN_SURFING              2
#define OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE           3
#define OBJ_EVENT_GFX_QUINTY_PLUMP                 4
#define OBJ_EVENT_GFX_NINJA_BOY                    5
#define OBJ_EVENT_GFX_TWIN                         6
#define OBJ_EVENT_GFX_BOY_1                        7
#define OBJ_EVENT_GFX_GIRL_1                       8
#define OBJ_EVENT_GFX_BOY_2                        9
#define OBJ_EVENT_GFX_GIRL_2                      10
#define OBJ_EVENT_GFX_LITTLE_BOY                  11
#define OBJ_EVENT_GFX_LITTLE_GIRL                 12
#define OBJ_EVENT_GFX_BOY_3                       13
#define OBJ_EVENT_GFX_GIRL_3                      14
#define OBJ_EVENT_GFX_RICH_BOY                    15
#define OBJ_EVENT_GFX_WOMAN_1                     16
#define OBJ_EVENT_GFX_FAT_MAN                     17
#define OBJ_EVENT_GFX_POKEFAN_F                   18
#define OBJ_EVENT_GFX_MAN_1                       19
#define OBJ_EVENT_GFX_WOMAN_2                     20
#define OBJ_EVENT_GFX_EXPERT_M                    21
#define OBJ_EVENT_GFX_EXPERT_F                    22
#define OBJ_EVENT_GFX_MAN_2                       23
#define OBJ_EVENT_GFX_WOMAN_3                     24
#define OBJ_EVENT_GFX_POKEFAN_M                   25
#define OBJ_EVENT_GFX_WOMAN_4                     26
#define OBJ_EVENT_GFX_COOK                        27
#define OBJ_EVENT_GFX_LINK_RECEPTIONIST           28
#define OBJ_EVENT_GFX_OLD_MAN                     29
#define OBJ_EVENT_GFX_OLD_WOMAN                   30
#define OBJ_EVENT_GFX_CAMPER                      31
#define OBJ_EVENT_GFX_PICNICKER                   32
#define OBJ_EVENT_GFX_MAN_3                       33
#define OBJ_EVENT_GFX_WOMAN_5                     34
#define OBJ_EVENT_GFX_YOUNGSTER                   35
#define OBJ_EVENT_GFX_BUG_CATCHER                 36
#define OBJ_EVENT_GFX_PSYCHIC_M                   37
#define OBJ_EVENT_GFX_SCHOOL_KID_M                38
#define OBJ_EVENT_GFX_MANIAC                      39
#define OBJ_EVENT_GFX_HEX_MANIAC                  40
#define OBJ_EVENT_GFX_RAYQUAZA_STILL              41
#define OBJ_EVENT_GFX_SWIMMER_M                   42
#define OBJ_EVENT_GFX_SWIMMER_F                   43
#define OBJ_EVENT_GFX_BLACK_BELT                  44
#define OBJ_EVENT_GFX_BEAUTY                      45
#define OBJ_EVENT_GFX_SCIENTIST_1                 46
#define OBJ_EVENT_GFX_LASS                        47
#define OBJ_EVENT_GFX_GENTLEMAN                   48
#define OBJ_EVENT_GFX_SAILOR                      49
#define OBJ_EVENT_GFX_FISHERMAN                   50
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M        51
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_F        52
#define OBJ_EVENT_GFX_TUBER_F                     53
#define OBJ_EVENT_GFX_TUBER_M                     54
#define OBJ_EVENT_GFX_HIKER                       55
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_M        56
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_F        57
#define OBJ_EVENT_GFX_NURSE                       58
#define OBJ_EVENT_GFX_ITEM_BALL                   59
#define OBJ_EVENT_GFX_BERRY_TREE                  60
#define OBJ_EVENT_GFX_BERRY_TREE_EARLY_STAGES     61
#define OBJ_EVENT_GFX_BERRY_TREE_LATE_STAGES      62
#define OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE           63
#define OBJ_EVENT_GFX_PROF_BIRCH                  64
#define OBJ_EVENT_GFX_MAN_4                       65
#define OBJ_EVENT_GFX_MAN_5                       66
#define OBJ_EVENT_GFX_REPORTER_M                  67
#define OBJ_EVENT_GFX_REPORTER_F                  68
#define OBJ_EVENT_GFX_BARD                        69
#define OBJ_EVENT_GFX_ANABEL                      70
#define OBJ_EVENT_GFX_TUCKER                      71
#define OBJ_EVENT_GFX_GRETA                       72
#define OBJ_EVENT_GFX_SPENSER                     73
#define OBJ_EVENT_GFX_NOLAND                      74
#define OBJ_EVENT_GFX_LUCY                        75
#define OBJ_EVENT_GFX_UNUSED_NATU_DOLL            76
#define OBJ_EVENT_GFX_UNUSED_MAGNEMITE_DOLL       77
#define OBJ_EVENT_GFX_UNUSED_SQUIRTLE_DOLL        78
#define OBJ_EVENT_GFX_UNUSED_WOOPER_DOLL          79
#define OBJ_EVENT_GFX_UNUSED_PIKACHU_DOLL         80
#define OBJ_EVENT_GFX_UNUSED_PORYGON2_DOLL        81
#define OBJ_EVENT_GFX_CUTTABLE_TREE               82
#define OBJ_EVENT_GFX_MART_EMPLOYEE               83
#define OBJ_EVENT_GFX_ROOFTOP_SALE_WOMAN          84
#define OBJ_EVENT_GFX_TEALA                       85
#define OBJ_EVENT_GFX_BREAKABLE_ROCK              86
#define OBJ_EVENT_GFX_PUSHABLE_BOULDER            87
#define OBJ_EVENT_GFX_MR_BRINEYS_BOAT             88
#define OBJ_EVENT_GFX_MAY_NORMAL                  89
#define OBJ_EVENT_GFX_MAY_MACH_BIKE               90
#define OBJ_EVENT_GFX_MAY_ACRO_BIKE               91
#define OBJ_EVENT_GFX_MAY_SURFING                 92
#define OBJ_EVENT_GFX_MAY_FIELD_MOVE              93
#define OBJ_EVENT_GFX_TRUCK                       94
#define OBJ_EVENT_GFX_VIGOROTH_CARRYING_BOX       95
#define OBJ_EVENT_GFX_VIGOROTH_FACING_AWAY        96
#define OBJ_EVENT_GFX_BIRCHS_BAG                  97
#define OBJ_EVENT_GFX_ZIGZAGOON_1                 98
#define OBJ_EVENT_GFX_ARTIST                      99
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_NORMAL       100
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_MACH_BIKE    101
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_ACRO_BIKE    102
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_SURFING      103
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_FIELD_MOVE   104
#define OBJ_EVENT_GFX_RIVAL_MAY_NORMAL           105
#define OBJ_EVENT_GFX_RIVAL_MAY_MACH_BIKE        106
#define OBJ_EVENT_GFX_RIVAL_MAY_ACRO_BIKE        107
#define OBJ_EVENT_GFX_RIVAL_MAY_SURFING          108
#define OBJ_EVENT_GFX_RIVAL_MAY_FIELD_MOVE       109
#define OBJ_EVENT_GFX_CAMERAMAN                  110
#define OBJ_EVENT_GFX_BRENDAN_UNDERWATER         111
#define OBJ_EVENT_GFX_MAY_UNDERWATER             112
#define OBJ_EVENT_GFX_MOVING_BOX                 113
#define OBJ_EVENT_GFX_CABLE_CAR                  114
#define OBJ_EVENT_GFX_SCIENTIST_2                115
#define OBJ_EVENT_GFX_DEVON_EMPLOYEE             116
#define OBJ_EVENT_GFX_AQUA_MEMBER_M              117
#define OBJ_EVENT_GFX_AQUA_MEMBER_F              118
#define OBJ_EVENT_GFX_MAGMA_MEMBER_M             119
#define OBJ_EVENT_GFX_MAGMA_MEMBER_F             120
#define OBJ_EVENT_GFX_SIDNEY                     121
#define OBJ_EVENT_GFX_PHOEBE                     122
#define OBJ_EVENT_GFX_GLACIA                     123
#define OBJ_EVENT_GFX_DRAKE                      124
#define OBJ_EVENT_GFX_ROXANNE                    125
#define OBJ_EVENT_GFX_BRAWLY                     126
#define OBJ_EVENT_GFX_WATTSON                    127
#define OBJ_EVENT_GFX_FLANNERY                   128
#define OBJ_EVENT_GFX_NORMAN                     129
#define OBJ_EVENT_GFX_WINONA                     130
#define OBJ_EVENT_GFX_LIZA                       131
#define OBJ_EVENT_GFX_TATE                       132
#define OBJ_EVENT_GFX_WALLACE                    133
#define OBJ_EVENT_GFX_STEVEN                     134
#define OBJ_EVENT_GFX_WALLY                      135
#define OBJ_EVENT_GFX_LITTLE_BOY_3               136
#define OBJ_EVENT_GFX_BRENDAN_FISHING            137
#define OBJ_EVENT_GFX_MAY_FISHING                138
#define OBJ_EVENT_GFX_HOT_SPRINGS_OLD_WOMAN      139
#define OBJ_EVENT_GFX_SS_TIDAL                   140
#define OBJ_EVENT_GFX_SUBMARINE_SHADOW           141
#define OBJ_EVENT_GFX_PICHU_DOLL                 142
#define OBJ_EVENT_GFX_PIKACHU_DOLL               143
#define OBJ_EVENT_GFX_MARILL_DOLL                144
#define OBJ_EVENT_GFX_TOGEPI_DOLL                145
#define OBJ_EVENT_GFX_CYNDAQUIL_DOLL             146
#define OBJ_EVENT_GFX_CHIKORITA_DOLL             147
#define OBJ_EVENT_GFX_TOTODILE_DOLL              148
#define OBJ_EVENT_GFX_JIGGLYPUFF_DOLL            149
#define OBJ_EVENT_GFX_MEOWTH_DOLL                150
#define OBJ_EVENT_GFX_CLEFAIRY_DOLL              151
#define OBJ_EVENT_GFX_DITTO_DOLL                 152
#define OBJ_EVENT_GFX_SMOOCHUM_DOLL              153
#define OBJ_EVENT_GFX_TREECKO_DOLL               154
#define OBJ_EVENT_GFX_TORCHIC_DOLL               155
#define OBJ_EVENT_GFX_MUDKIP_DOLL                156
#define OBJ_EVENT_GFX_DUSKULL_DOLL               157
#define OBJ_EVENT_GFX_WYNAUT_DOLL                158
#define OBJ_EVENT_GFX_BALTOY_DOLL                159
#define OBJ_EVENT_GFX_KECLEON_DOLL               160
#define OBJ_EVENT_GFX_AZURILL_DOLL               161
#define OBJ_EVENT_GFX_SKITTY_DOLL                162
#define OBJ_EVENT_GFX_SWABLU_DOLL                163
#define OBJ_EVENT_GFX_GULPIN_DOLL                164
#define OBJ_EVENT_GFX_LOTAD_DOLL                 165
#define OBJ_EVENT_GFX_SEEDOT_DOLL                166
#define OBJ_EVENT_GFX_PIKA_CUSHION               167
#define OBJ_EVENT_GFX_ROUND_CUSHION              168
#define OBJ_EVENT_GFX_KISS_CUSHION               169
#define OBJ_EVENT_GFX_ZIGZAG_CUSHION             170
#define OBJ_EVENT_GFX_SPIN_CUSHION               171
#define OBJ_EVENT_GFX_DIAMOND_CUSHION            172
#define OBJ_EVENT_GFX_BALL_CUSHION               173
#define OBJ_EVENT_GFX_GRASS_CUSHION              174
#define OBJ_EVENT_GFX_FIRE_CUSHION               175
#define OBJ_EVENT_GFX_WATER_CUSHION              176
#define OBJ_EVENT_GFX_BIG_SNORLAX_DOLL           177
#define OBJ_EVENT_GFX_BIG_RHYDON_DOLL            178
#define OBJ_EVENT_GFX_BIG_LAPRAS_DOLL            179
#define OBJ_EVENT_GFX_BIG_VENUSAUR_DOLL          180
#define OBJ_EVENT_GFX_BIG_CHARIZARD_DOLL         181
#define OBJ_EVENT_GFX_BIG_BLASTOISE_DOLL         182
#define OBJ_EVENT_GFX_BIG_WAILMER_DOLL           183
#define OBJ_EVENT_GFX_BIG_REGIROCK_DOLL          184
#define OBJ_EVENT_GFX_BIG_REGICE_DOLL            185
#define OBJ_EVENT_GFX_BIG_REGISTEEL_DOLL         186
#define OBJ_EVENT_GFX_LATIAS                     187
#define OBJ_EVENT_GFX_LATIOS                     188
#define OBJ_EVENT_GFX_GAMEBOY_KID                189
#define OBJ_EVENT_GFX_CONTEST_JUDGE              190
#define OBJ_EVENT_GFX_BRENDAN_WATERING           191
#define OBJ_EVENT_GFX_MAY_WATERING               192
#define OBJ_EVENT_GFX_BRENDAN_DECORATING         193
#define OBJ_EVENT_GFX_MAY_DECORATING             194
#define OBJ_EVENT_GFX_ARCHIE                     195
#define OBJ_EVENT_GFX_MAXIE                      196
#define OBJ_EVENT_GFX_KYOGRE_FRONT               197
#define OBJ_EVENT_GFX_GROUDON_FRONT              198
#define OBJ_EVENT_GFX_FOSSIL                     199
#define OBJ_EVENT_GFX_REGIROCK                   200
#define OBJ_EVENT_GFX_REGICE                     201
#define OBJ_EVENT_GFX_REGISTEEL                  202
#define OBJ_EVENT_GFX_SKITTY                     203
#define OBJ_EVENT_GFX_KECLEON                    204
#define OBJ_EVENT_GFX_KYOGRE_ASLEEP              205
#define OBJ_EVENT_GFX_GROUDON_ASLEEP             206
#define OBJ_EVENT_GFX_RAYQUAZA                   207
#define OBJ_EVENT_GFX_ZIGZAGOON_2                208
#define OBJ_EVENT_GFX_PIKACHU                    209
#define OBJ_EVENT_GFX_AZUMARILL                  210
#define OBJ_EVENT_GFX_WINGULL                    211
#define OBJ_EVENT_GFX_KECLEON_BRIDGE_SHADOW      212
#define OBJ_EVENT_GFX_TUBER_M_SWIMMING           213
#define OBJ_EVENT_GFX_AZURILL                    214
#define OBJ_EVENT_GFX_MOM                        215
#define OBJ_EVENT_GFX_LINK_BRENDAN               216
#define OBJ_EVENT_GFX_LINK_MAY                   217
#define OBJ_EVENT_GFX_JUAN                       218
#define OBJ_EVENT_GFX_SCOTT                      219
#define OBJ_EVENT_GFX_POOCHYENA                  220
#define OBJ_EVENT_GFX_KYOGRE_SIDE                221
#define OBJ_EVENT_GFX_GROUDON_SIDE               222
#define OBJ_EVENT_GFX_MYSTERY_GIFT_MAN           223
#define OBJ_EVENT_GFX_TRICK_HOUSE_STATUE         224
#define OBJ_EVENT_GFX_KIRLIA                     225
#define OBJ_EVENT_GFX_DUSCLOPS                   226
#define OBJ_EVENT_GFX_UNION_ROOM_NURSE           227
#define OBJ_EVENT_GFX_SUDOWOODO                  228
#define OBJ_EVENT_GFX_MEW                        229
#define OBJ_EVENT_GFX_RED                        230
#define OBJ_EVENT_GFX_LEAF                       231
#define OBJ_EVENT_GFX_DEOXYS                     232
#define OBJ_EVENT_GFX_DEOXYS_TRIANGLE            233
#define OBJ_EVENT_GFX_BRANDON                    234
#define OBJ_EVENT_GFX_LINK_RS_BRENDAN            235
#define OBJ_EVENT_GFX_LINK_RS_MAY                236
#define OBJ_EVENT_GFX_LUGIA                      237
#define OBJ_EVENT_GFX_HOOH                       238
#define OBJ_EVENT_GFX_ACCORDIANIST               239
#define OBJ_EVENT_GFX_ACTOR                      240
#define OBJ_EVENT_GFX_ALDER                      241
#define OBJ_EVENT_GFX_ANTHEA_1                   242
#define OBJ_EVENT_GFX_ANTHEA_2                   243
#define OBJ_EVENT_GFX_AROMA_LADY                 244
#define OBJ_EVENT_GFX_ARTIST_1                   245
#define OBJ_EVENT_GFX_ARTIST_2                   246
#define OBJ_EVENT_GFX_ARTIST_3                   247
#define OBJ_EVENT_GFX_BACKPACKER_F               248
#define OBJ_EVENT_GFX_BACKPACKER_M               249
#define OBJ_EVENT_GFX_BAKER                      250
#define OBJ_EVENT_GFX_BATTLEGIRL_1               251
#define OBJ_EVENT_GFX_BATTLEGIRL_2               252
#define OBJ_EVENT_GFX_BEAUTY_1                   253
#define OBJ_EVENT_GFX_BEAUTY_2                   254
#define OBJ_EVENT_GFX_BEAUTY_3                   255
#define OBJ_EVENT_GFX_BEAUTY_4                   256
#define OBJ_EVENT_GFX_BENGA                      257
#define OBJ_EVENT_GFX_BIANCA_1                   258
#define OBJ_EVENT_GFX_BIANCA_2                   259
#define OBJ_EVENT_GFX_BIKER_1                    260
#define OBJ_EVENT_GFX_BIKER_2                    261
#define OBJ_EVENT_GFX_BIRDKEEPER_F_1             262
#define OBJ_EVENT_GFX_BIRDKEEPER_F_2             263
#define OBJ_EVENT_GFX_BIRDKEEPER_M               264
#define OBJ_EVENT_GFX_BLACKBELT_1                265
#define OBJ_EVENT_GFX_BLACKBELT_2                266
#define OBJ_EVENT_GFX_BLACKBELT_3                267
#define OBJ_EVENT_GFX_BLAINE                     268
#define OBJ_EVENT_GFX_BOARDER                    269
#define OBJ_EVENT_GFX_BOY                        270
#define OBJ_EVENT_GFX_BRAWLY_1                   271
#define OBJ_EVENT_GFX_BROCK                      272
#define OBJ_EVENT_GFX_BRYCEN                     273
#define OBJ_EVENT_GFX_BUG_CATCHER_1              274
#define OBJ_EVENT_GFX_BURGH                      275
#define OBJ_EVENT_GFX_BURGLAR                    276
#define OBJ_EVENT_GFX_BW_MOM                     277
#define OBJ_EVENT_GFX_BW2_MOM                    278
#define OBJ_EVENT_GFX_CAITLIN                    279
#define OBJ_EVENT_GFX_CAMERAMAN_1                280
#define OBJ_EVENT_GFX_CAMPER_1                   281
#define OBJ_EVENT_GFX_CAPTAIN                    282
#define OBJ_EVENT_GFX_CEDRIC                     283
#define OBJ_EVENT_GFX_CHANNELLER                 284
#define OBJ_EVENT_GFX_CHEREN_1                   285
#define OBJ_EVENT_GFX_CHEREN_2                   286
#define OBJ_EVENT_GFX_CHILI                      287
#define OBJ_EVENT_GFX_CILAN                      288
#define OBJ_EVENT_GFX_CLAY                       289
#define OBJ_EVENT_GFX_CLERK_F                    290
#define OBJ_EVENT_GFX_CLERK_M_1                  291
#define OBJ_EVENT_GFX_CLERK_M_2                  292
#define OBJ_EVENT_GFX_CLOWN                      293
#define OBJ_EVENT_GFX_COLLECTOR                  294
#define OBJ_EVENT_GFX_COLRESS                    295
#define OBJ_EVENT_GFX_CONCORDIA_1                296
#define OBJ_EVENT_GFX_CONCORDIA_2                297
#define OBJ_EVENT_GFX_COOLTRAINER_F_1            298
#define OBJ_EVENT_GFX_COOLTRAINER_F_2            299
#define OBJ_EVENT_GFX_COOLTRAINER_F_3            300
#define OBJ_EVENT_GFX_COOLTRAINER_F_4            301
#define OBJ_EVENT_GFX_COOLTRAINER_M_1            302
#define OBJ_EVENT_GFX_COOLTRAINER_M_2            303
#define OBJ_EVENT_GFX_COOLTRAINER_M_3            304
#define OBJ_EVENT_GFX_COOLTRAINER_M_4            305
#define OBJ_EVENT_GFX_COWGIRL                    306
#define OBJ_EVENT_GFX_CRESS                      307
#define OBJ_EVENT_GFX_CURTIS_1                   308
#define OBJ_EVENT_GFX_CURTIS_2                   309
#define OBJ_EVENT_GFX_CYCLIST_F_1                310
#define OBJ_EVENT_GFX_CYCLIST_F_2                311
#define OBJ_EVENT_GFX_CYCLIST_M_1                312
#define OBJ_EVENT_GFX_CYCLIST_M_2                313
#define OBJ_EVENT_GFX_DANCER                     314
#define OBJ_EVENT_GFX_DEPOTAGENT                 315
#define OBJ_EVENT_GFX_DOCTOR                     316
#define OBJ_EVENT_GFX_DRAGONTAMER                317
#define OBJ_EVENT_GFX_DRAYDEN                    318
#define OBJ_EVENT_GFX_ELDER                      319
#define OBJ_EVENT_GFX_ELESA_1                    320
#define OBJ_EVENT_GFX_ELESA_2                    321
#define OBJ_EVENT_GFX_EMMET                      322
#define OBJ_EVENT_GFX_ERICA                      323
#define OBJ_EVENT_GFX_ETHAN                      324
#define OBJ_EVENT_GFX_EXECUTIVE_F                325
#define OBJ_EVENT_GFX_EXECUTIVE_M_1              326
#define OBJ_EVENT_GFX_EXECUTIVE_M_2              327
#define OBJ_EVENT_GFX_EXECUTIVE_M_3              328
#define OBJ_EVENT_GFX_FAT_MAN_1                  329
#define OBJ_EVENT_GFX_FAT_MAN_2                  330
#define OBJ_EVENT_GFX_FAT_MAN_3                  331
#define OBJ_EVENT_GFX_FENNEL                     332
#define OBJ_EVENT_GFX_FIREBREATHER               333
#define OBJ_EVENT_GFX_FISHERMAN_1                334
#define OBJ_EVENT_GFX_FISHERMAN_2                335
#define OBJ_EVENT_GFX_FLANNERY_1                 336
#define OBJ_EVENT_GFX_FLAUTIST                   337
#define OBJ_EVENT_GFX_GAMBLER                    338
#define OBJ_EVENT_GFX_GENTLEMAN_1                339
#define OBJ_EVENT_GFX_GENTLEMAN_2                340
#define OBJ_EVENT_GFX_GENTLEMAN_3                341
#define OBJ_EVENT_GFX_GHETHIS                    342
#define OBJ_EVENT_GFX_GIOVANNI                   343
#define OBJ_EVENT_GFX_GRIMSLEY                   344
#define OBJ_EVENT_GFX_GUIDE_F                    345
#define OBJ_EVENT_GFX_GUIDE_M                    346
#define OBJ_EVENT_GFX_GUITARIST_1                347
#define OBJ_EVENT_GFX_GUITARIST_2                348
#define OBJ_EVENT_GFX_GUITARIST_3                349
#define OBJ_EVENT_GFX_GUITARIST_F_1              350
#define OBJ_EVENT_GFX_GUITARIST_F_2              351
#define OBJ_EVENT_GFX_GUZMA                      352
#define OBJ_EVENT_GFX_GYM_GUIDE                  353
#define OBJ_EVENT_GFX_HARLEQUIN                  354
#define OBJ_EVENT_GFX_HARMONICA                  355
#define OBJ_EVENT_GFX_HIKER_1                    356
#define OBJ_EVENT_GFX_HIKER_2                    357
#define OBJ_EVENT_GFX_HOOPSTER                   358
#define OBJ_EVENT_GFX_HUGH                       359
#define OBJ_EVENT_GFX_IDOL                       360
#define OBJ_EVENT_GFX_INFIELDER                  361
#define OBJ_EVENT_GFX_INGO                       362
#define OBJ_EVENT_GFX_IRIS_1                     363
#define OBJ_EVENT_GFX_IRIS_2                     364
#define OBJ_EVENT_GFX_JANITOR                    365
#define OBJ_EVENT_GFX_JOGGER_1                   366
#define OBJ_EVENT_GFX_JOGGER_2                   367
#define OBJ_EVENT_GFX_JOGGER_3                   368
#define OBJ_EVENT_GFX_JUGGLER                    369
#define OBJ_EVENT_GFX_KEYTAURIST                 370
#define OBJ_EVENT_GFX_KIMONO_GIRL                371
#define OBJ_EVENT_GFX_KOGA                       372
#define OBJ_EVENT_GFX_LADY_1                     373
#define OBJ_EVENT_GFX_LADY_2                     374
#define OBJ_EVENT_GFX_LASS_1                     375
#define OBJ_EVENT_GFX_LASS_2                     376
#define OBJ_EVENT_GFX_LASS_3                     377
#define OBJ_EVENT_GFX_LEONORA_1                  378
#define OBJ_EVENT_GFX_LEONORA_2                  379
#define OBJ_EVENT_GFX_LINEBACKER                 380
#define OBJ_EVENT_GFX_LIZA_1                     381
#define OBJ_EVENT_GFX_LT_SURGE                   382
#define OBJ_EVENT_GFX_LYRA                       383
#define OBJ_EVENT_GFX_MAID_1                     384
#define OBJ_EVENT_GFX_MAID_2                     385
#define OBJ_EVENT_GFX_MAN_6                      386
#define OBJ_EVENT_GFX_MAN_7                      387
#define OBJ_EVENT_GFX_MAN_8                      388
#define OBJ_EVENT_GFX_MARLIN_SWIM                389
#define OBJ_EVENT_GFX_MARLIN                     390
#define OBJ_EVENT_GFX_MARSHALL                   391
#define OBJ_EVENT_GFX_MEDAL_GUY                  392
#define OBJ_EVENT_GFX_MEDIUM                     393
#define OBJ_EVENT_GFX_MISTY                      394
#define OBJ_EVENT_GFX_N                          395
#define OBJ_EVENT_GFX_NEO_GHETHIS_CANE           396
#define OBJ_EVENT_GFX_NEO_GHETHIS                397
#define OBJ_EVENT_GFX_NEO_PLASMA_F               398
#define OBJ_EVENT_GFX_NEO_PLASMA_M               399
#define OBJ_EVENT_GFX_NEO_ZINZOLIN               400
#define OBJ_EVENT_GFX_NINJA_BOY_1                401
#define OBJ_EVENT_GFX_NORMAN_1                   402
#define OBJ_EVENT_GFX_NURSE_1                    403
#define OBJ_EVENT_GFX_NURSE_JOY                  404
#define OBJ_EVENT_GFX_NURSERY_AIDE               405
#define OBJ_EVENT_GFX_OLD_WOMAN_1                406
#define OBJ_EVENT_GFX_PARASOL_LADY_1             407
#define OBJ_EVENT_GFX_PARASOL_LADY_2             408
#define OBJ_EVENT_GFX_PICNICKER_1                409
#define OBJ_EVENT_GFX_PIERS                      410
#define OBJ_EVENT_GFX_PILOT                      411
#define OBJ_EVENT_GFX_POKEFAN_F_1                412
#define OBJ_EVENT_GFX_POKEFAN_F_2                413
#define OBJ_EVENT_GFX_POKEFAN_M_1                414
#define OBJ_EVENT_GFX_POKEFAN_M_2                415
#define OBJ_EVENT_GFX_POKEKID                    416
#define OBJ_EVENT_GFX_POKEMANIAC                 417
#define OBJ_EVENT_GFX_POKEMART                   418
#define OBJ_EVENT_GFX_POKEMON_BREEDER_F_1        419
#define OBJ_EVENT_GFX_POKEMON_BREEDER_F_2        420
#define OBJ_EVENT_GFX_POKEMON_BREEDER_M_1        421
#define OBJ_EVENT_GFX_POKEMON_BREEDER_M_2        422
#define OBJ_EVENT_GFX_POKEMON_RANGER_F_1         423
#define OBJ_EVENT_GFX_POKEMON_RANGER_F_2         424
#define OBJ_EVENT_GFX_POKEMON_RANGER_M_1         425
#define OBJ_EVENT_GFX_POKEMON_RANGER_M_2         426
#define OBJ_EVENT_GFX_POLICEMAN_1                427
#define OBJ_EVENT_GFX_POLICEMAN_2                428
#define OBJ_EVENT_GFX_POSTMAN                    429
#define OBJ_EVENT_GFX_PRESCHOOLER_F              430
#define OBJ_EVENT_GFX_PRESCHOOLER_M              431
#define OBJ_EVENT_GFX_PROFESSOR_JUNIPER          432
#define OBJ_EVENT_GFX_PROFESSOR_OAK              433
#define OBJ_EVENT_GFX_PSYCHIC_F_1                434
#define OBJ_EVENT_GFX_PSYCHIC_F_2                435
#define OBJ_EVENT_GFX_PSYCHIC_M_1                436
#define OBJ_EVENT_GFX_PSYCHIC_M_2                437
#define OBJ_EVENT_GFX_RANCHER                    438
#define OBJ_EVENT_GFX_RECEPTIONIST_1             439
#define OBJ_EVENT_GFX_RECEPTIONIST_2             440
#define OBJ_EVENT_GFX_RECEPTIONIST_3             441
#define OBJ_EVENT_GFX_RECEPTIONIST_4             442
#define OBJ_EVENT_GFX_REPORTER                   443
#define OBJ_EVENT_GFX_RICH_BOY_1                 444
#define OBJ_EVENT_GFX_RICH_BOY_2                 445
#define OBJ_EVENT_GFX_RICH_MAN                   446
#define OBJ_EVENT_GFX_ROUGHNECK_1                447
#define OBJ_EVENT_GFX_ROUGHNECK_2                448
#define OBJ_EVENT_GFX_ROUGHNECK_2_FIGHT          449
#define OBJ_EVENT_GFX_ROXANNE_1                  450
#define OBJ_EVENT_GFX_ROXIE_GUITAR               451
#define OBJ_EVENT_GFX_ROXIE                      452
#define OBJ_EVENT_GFX_RUIN_MANIAC                453
#define OBJ_EVENT_GFX_SABRINA                    454
#define OBJ_EVENT_GFX_SAGE_BRONIUS               455
#define OBJ_EVENT_GFX_SAGE_GIALLO                456
#define OBJ_EVENT_GFX_SAGE_GORM                  457
#define OBJ_EVENT_GFX_SAGE_ROOD                  458
#define OBJ_EVENT_GFX_SAGE_RYOKU                 459
#define OBJ_EVENT_GFX_SAGE_ZINZOLIN              460
#define OBJ_EVENT_GFX_SAGE                       461
#define OBJ_EVENT_GFX_SAILOR_1                   462
#define OBJ_EVENT_GFX_SCHOOLKID_F                463
#define OBJ_EVENT_GFX_SCHOOLKID_M_1              464
#define OBJ_EVENT_GFX_SCIENTIST_F                465
#define OBJ_EVENT_GFX_SCIENTIST_M_1              466
#define OBJ_EVENT_GFX_SCIENTIST_M_2              467
#define OBJ_EVENT_GFX_SCIENTIST_M_3              468
#define OBJ_EVENT_GFX_SHADOW_TRIAD               469
#define OBJ_EVENT_GFX_SHADY_GUY                  470
#define OBJ_EVENT_GFX_SHAUNTAL                   471
#define OBJ_EVENT_GFX_SILVER                     472
#define OBJ_EVENT_GFX_SINGER                     473
#define OBJ_EVENT_GFX_SKIER_F_1                  474
#define OBJ_EVENT_GFX_SKIER_F_2                  475
#define OBJ_EVENT_GFX_SKIER_M                    476
#define OBJ_EVENT_GFX_SKYLA                      478
#define OBJ_EVENT_GFX_SMASHER                    479
#define OBJ_EVENT_GFX_SOCIALITE_1                480
#define OBJ_EVENT_GFX_SOCIALITE_2                481
#define OBJ_EVENT_GFX_STRIKER                    482
#define OBJ_EVENT_GFX_SUPERNERD                  483
#define OBJ_EVENT_GFX_SWIMMER_F_1                484
#define OBJ_EVENT_GFX_SWIMMER_F_2                485
#define OBJ_EVENT_GFX_SWIMMER_F_3                486
#define OBJ_EVENT_GFX_SWIMMER_M_1                487
#define OBJ_EVENT_GFX_SWIMMER_M_2                488
#define OBJ_EVENT_GFX_SWIMMER_M_3                489
#define OBJ_EVENT_GFX_TATE_1                     490
#define OBJ_EVENT_GFX_TEACHER                    491
#define OBJ_EVENT_GFX_TEAM_PLASMA_F              492
#define OBJ_EVENT_GFX_TEAM_PLASMA_M              493
#define OBJ_EVENT_GFX_TEAM_ROCKET_F              494
#define OBJ_EVENT_GFX_TEAM_ROCKET_M              495
#define OBJ_EVENT_GFX_TRUMPETER                  496
#define OBJ_EVENT_GFX_TUBER_F_1                  497
#define OBJ_EVENT_GFX_TUBER_M_1                  498
#define OBJ_EVENT_GFX_TWINS_1                    499
#define OBJ_EVENT_GFX_TWINS_2                    500
#define OBJ_EVENT_GFX_TWINS_3                    501
#define OBJ_EVENT_GFX_ULTIMA                     502
#define OBJ_EVENT_GFX_VETRAN_F                   503
#define OBJ_EVENT_GFX_VETRAN_M_1                 504
#define OBJ_EVENT_GFX_VETRAN_M_2                 505
#define OBJ_EVENT_GFX_WAITER_1                   506
#define OBJ_EVENT_GFX_WAITER_2                   507
#define OBJ_EVENT_GFX_WAITRESS_1                 508
#define OBJ_EVENT_GFX_WAITRESS_2                 509
#define OBJ_EVENT_GFX_WALLACE_1                  510
#define OBJ_EVENT_GFX_WATTSON_1                  511
#define OBJ_EVENT_GFX_WINONA_1                   512
#define OBJ_EVENT_GFX_WOMAN_6                    513
#define OBJ_EVENT_GFX_WOMAN_7                    514
#define OBJ_EVENT_GFX_WOMAN_8                    515
#define OBJ_EVENT_GFX_WOMAN_9                    516
#define OBJ_EVENT_GFX_WOMAN_10                   517
#define OBJ_EVENT_GFX_WOMAN_11                   518
#define OBJ_EVENT_GFX_WORKER_1                   519
#define OBJ_EVENT_GFX_WORKER_2                   520
#define OBJ_EVENT_GFX_WORKER_3                   521
#define OBJ_EVENT_GFX_YANCY_1                    522
#define OBJ_EVENT_GFX_YANCY_2                    523
#define OBJ_EVENT_GFX_YOUNGSTER_1                524
#define OBJ_EVENT_GFX_YOUNGSTER_2                525
#define OBJ_EVENT_GFX_YOUNGSTER_3                526
#define OBJ_EVENT_GFX_POKE_BALL                  527
#define OBJ_EVENT_GFX_OW_MON                     528

// NOTE: The maximum amount of object events has been expanded from 255 to 65535.
// Since dynamic graphics ids still require at least 16 free values, the actual limit
// is 65519, but even considering follower Pokémon, this should be more than enough :)
#define NUM_OBJ_EVENT_GFX                        529


// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define OBJ_EVENT_GFX_VARS   (NUM_OBJ_EVENT_GFX + 1)
#define OBJ_EVENT_GFX_VAR_0  (OBJ_EVENT_GFX_VARS + 0x0)
#define OBJ_EVENT_GFX_VAR_1  (OBJ_EVENT_GFX_VARS + 0x1)
#define OBJ_EVENT_GFX_VAR_2  (OBJ_EVENT_GFX_VARS + 0x2)
#define OBJ_EVENT_GFX_VAR_3  (OBJ_EVENT_GFX_VARS + 0x3)
#define OBJ_EVENT_GFX_VAR_4  (OBJ_EVENT_GFX_VARS + 0x4)
#define OBJ_EVENT_GFX_VAR_5  (OBJ_EVENT_GFX_VARS + 0x5)
#define OBJ_EVENT_GFX_VAR_6  (OBJ_EVENT_GFX_VARS + 0x6)
#define OBJ_EVENT_GFX_VAR_7  (OBJ_EVENT_GFX_VARS + 0x7)
#define OBJ_EVENT_GFX_VAR_8  (OBJ_EVENT_GFX_VARS + 0x8)
#define OBJ_EVENT_GFX_VAR_9  (OBJ_EVENT_GFX_VARS + 0x9)
#define OBJ_EVENT_GFX_VAR_A  (OBJ_EVENT_GFX_VARS + 0xA)
#define OBJ_EVENT_GFX_VAR_B  (OBJ_EVENT_GFX_VARS + 0xB)
#define OBJ_EVENT_GFX_VAR_C  (OBJ_EVENT_GFX_VARS + 0xC)
#define OBJ_EVENT_GFX_VAR_D  (OBJ_EVENT_GFX_VARS + 0xD)
#define OBJ_EVENT_GFX_VAR_E  (OBJ_EVENT_GFX_VARS + 0xE)
#define OBJ_EVENT_GFX_VAR_F  (OBJ_EVENT_GFX_VARS + 0xF)

#define OBJ_EVENT_GFX_MON_BASE  0x200 // 512
#define OBJ_EVENT_GFX_SPECIES_BITS 12 // This will need to be updated when NUM_SPECIES is > ~3.5k
#define OBJ_EVENT_GFX_SPECIES_MASK ((1 << OBJ_EVENT_GFX_SPECIES_BITS) - 1)

// Used to call a specific species' follower graphics. Useful for static encounters.
#define OBJ_EVENT_GFX_SPECIES(name)       (SPECIES_##name + OBJ_EVENT_GFX_MON_BASE)
#define OBJ_EVENT_GFX_SPECIES_SHINY(name) (SPECIES_##name + OBJ_EVENT_GFX_MON_BASE + SPECIES_SHINY_TAG)

#define OW_SPECIES(x) (((x)->graphicsId & OBJ_EVENT_GFX_SPECIES_MASK) - OBJ_EVENT_GFX_MON_BASE)
#define OW_FORM(x) ((x)->graphicsId >> OBJ_EVENT_GFX_SPECIES_BITS)

#define SHADOW_SIZE_S    0
#define SHADOW_SIZE_M    1
#define SHADOW_SIZE_L    2
#define SHADOW_SIZE_NONE 3   // Originally SHADOW_SIZE_XL, which went unused due to shadowSize in ObjectEventGraphicsInfo being only 2 bits.

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2
#define TRACKS_SLITHER    3
#define TRACKS_SPOT       4
#define TRACKS_BUG        5

#define FIRST_DECORATION_SPRITE_GFX OBJ_EVENT_GFX_PICHU_DOLL

#define OBJ_KIND_NORMAL 0
#define OBJ_KIND_CLONE  255 // Exclusive to FRLG

// Special object event local ids
#define OBJ_EVENT_ID_PLAYER 0xFF
#define OBJ_EVENT_ID_CAMERA 0x7F
#define OBJ_EVENT_ID_FOLLOWER 0xFE

// Object event local ids referenced in C files
#define LOCALID_ROUTE111_PLAYER_FALLING 45
#define LOCALID_BIRTH_ISLAND_EXTERIOR_ROCK 1
#define LOCALID_FARAWAY_ISLAND_MEW 1
#define LOCALID_UNION_ROOM_PLAYER_4 2
#define LOCALID_UNION_ROOM_PLAYER_8 3
#define LOCALID_UNION_ROOM_PLAYER_7 4
#define LOCALID_UNION_ROOM_PLAYER_6 5
#define LOCALID_UNION_ROOM_PLAYER_5 6
#define LOCALID_UNION_ROOM_PLAYER_3 7
#define LOCALID_UNION_ROOM_PLAYER_2 8
#define LOCALID_UNION_ROOM_PLAYER_1 9
#define LOCALID_BATTLE_TOWER_LOBBY_REPORTER 5
#define LOCALID_TRUCK_BOX_TOP 1
#define LOCALID_TRUCK_BOX_BOTTOM_L 2
#define LOCALID_TRUCK_BOX_BOTTOM_R 3
#define LOCALID_OLDALE_MART_CLERK 1
#define LOCALID_LAVARIDGE_MART_CLERK 1
#define LOCALID_FALLARBOR_MART_CLERK 1
#define LOCALID_VERDANTURF_MART_CLERK 1
#define LOCALID_PETALBURG_MART_CLERK 1
#define LOCALID_SLATEPORT_MART_CLERK 1
#define LOCALID_MAUVILLE_MART_CLERK 1
#define LOCALID_RUSTBORO_MART_CLERK 1
#define LOCALID_FORTREE_MART_CLERK 1
#define LOCALID_MOSSDEEP_MART_CLERK 1
#define LOCALID_SOOTOPOLIS_MART_CLERK 1
#define LOCALID_BATTLE_FRONTIER_MART_CLERK 1
#define LOCALID_SLATEPORT_ENERGY_GURU 25

// Moved from src/event_object_movement.c so that they're accesible from other files.
#define OBJ_EVENT_PAL_TAG_BRENDAN                 0x1100
#define OBJ_EVENT_PAL_TAG_BRENDAN_REFLECTION      0x1101
#define OBJ_EVENT_PAL_TAG_BRIDGE_REFLECTION       0x1102
#define OBJ_EVENT_PAL_TAG_NPC_1                   0x1103
#define OBJ_EVENT_PAL_TAG_NPC_2                   0x1104
#define OBJ_EVENT_PAL_TAG_NPC_3                   0x1105
#define OBJ_EVENT_PAL_TAG_NPC_4                   0x1106
#define OBJ_EVENT_PAL_TAG_NPC_1_REFLECTION        0x1107
#define OBJ_EVENT_PAL_TAG_NPC_2_REFLECTION        0x1108
#define OBJ_EVENT_PAL_TAG_NPC_3_REFLECTION        0x1109
#define OBJ_EVENT_PAL_TAG_NPC_4_REFLECTION        0x110A
#define OBJ_EVENT_PAL_TAG_QUINTY_PLUMP            0x110B
#define OBJ_EVENT_PAL_TAG_QUINTY_PLUMP_REFLECTION 0x110C
#define OBJ_EVENT_PAL_TAG_TRUCK                   0x110D
#define OBJ_EVENT_PAL_TAG_VIGOROTH                0x110E
#define OBJ_EVENT_PAL_TAG_ZIGZAGOON               0x110F
#define OBJ_EVENT_PAL_TAG_MAY                     0x1110
#define OBJ_EVENT_PAL_TAG_MAY_REFLECTION          0x1111
#define OBJ_EVENT_PAL_TAG_MOVING_BOX              0x1112
#define OBJ_EVENT_PAL_TAG_CABLE_CAR               0x1113
#define OBJ_EVENT_PAL_TAG_SSTIDAL                 0x1114
#define OBJ_EVENT_PAL_TAG_PLAYER_UNDERWATER       0x1115
#define OBJ_EVENT_PAL_TAG_KYOGRE                  0x1116
#define OBJ_EVENT_PAL_TAG_KYOGRE_REFLECTION       0x1117
#define OBJ_EVENT_PAL_TAG_GROUDON                 0x1118
#define OBJ_EVENT_PAL_TAG_GROUDON_REFLECTION      0x1119
#define OBJ_EVENT_PAL_TAG_UNUSED                  0x111A
#define OBJ_EVENT_PAL_TAG_SUBMARINE_SHADOW        0x111B
#define OBJ_EVENT_PAL_TAG_POOCHYENA               0x111C
#define OBJ_EVENT_PAL_TAG_RED_LEAF                0x111D
#define OBJ_EVENT_PAL_TAG_DEOXYS                  0x111E
#define OBJ_EVENT_PAL_TAG_BIRTH_ISLAND_STONE      0x111F
#define OBJ_EVENT_PAL_TAG_HO_OH                   0x1120
#define OBJ_EVENT_PAL_TAG_LUGIA                   0x1121
#define OBJ_EVENT_PAL_TAG_RS_BRENDAN              0x1122
#define OBJ_EVENT_PAL_TAG_RS_MAY                  0x1123
#define OBJ_EVENT_PAL_TAG_DYNAMIC                 0x1124

#if OW_FOLLOWERS_POKEBALLS
// Vanilla
#define OBJ_EVENT_PAL_TAG_BALL_MASTER             0x1150
#define OBJ_EVENT_PAL_TAG_BALL_ULTRA              0x1151
#define OBJ_EVENT_PAL_TAG_BALL_GREAT              0x1152
#define OBJ_EVENT_PAL_TAG_BALL_SAFARI             0x1153
#define OBJ_EVENT_PAL_TAG_BALL_NET                0x1154
#define OBJ_EVENT_PAL_TAG_BALL_DIVE               0x1155
#define OBJ_EVENT_PAL_TAG_BALL_NEST               0x1156
#define OBJ_EVENT_PAL_TAG_BALL_REPEAT             0x1157
#define OBJ_EVENT_PAL_TAG_BALL_TIMER              0x1158
#define OBJ_EVENT_PAL_TAG_BALL_LUXURY             0x1159
#define OBJ_EVENT_PAL_TAG_BALL_PREMIER            0x115A
// Gen IV/Sinnoh
#define OBJ_EVENT_PAL_TAG_BALL_DUSK               0x115B
#define OBJ_EVENT_PAL_TAG_BALL_HEAL               0x115C
#define OBJ_EVENT_PAL_TAG_BALL_QUICK              0x115D
#define OBJ_EVENT_PAL_TAG_BALL_CHERISH            0x115E
#define OBJ_EVENT_PAL_TAG_BALL_PARK               0x115F
// Gen II/Johto Apricorns
#define OBJ_EVENT_PAL_TAG_BALL_FAST               0x1160
#define OBJ_EVENT_PAL_TAG_BALL_LEVEL              0x1161
#define OBJ_EVENT_PAL_TAG_BALL_LURE               0x1162
#define OBJ_EVENT_PAL_TAG_BALL_HEAVY              0x1163
#define OBJ_EVENT_PAL_TAG_BALL_LOVE               0x1164
#define OBJ_EVENT_PAL_TAG_BALL_FRIEND             0x1165
#define OBJ_EVENT_PAL_TAG_BALL_MOON               0x1166
#define OBJ_EVENT_PAL_TAG_BALL_SPORT              0x1167
// Gen V
#define OBJ_EVENT_PAL_TAG_BALL_DREAM              0x1168
// Gen VII
#define OBJ_EVENT_PAL_TAG_BALL_BEAST              0x1169
// Gen VIII
#define OBJ_EVENT_PAL_TAG_BALL_STRANGE            0x116A
#endif //OW_FOLLOWERS_POKEBALLS
#define OBJ_EVENT_PAL_TAG_ACCORDIANIST            0x116B
#define OBJ_EVENT_PAL_TAG_ACTOR                   0x116C
#define OBJ_EVENT_PAL_TAG_ALDER                   0x116D
#define OBJ_EVENT_PAL_TAG_ANTHEA_1                0x116E
#define OBJ_EVENT_PAL_TAG_ANTHEA_2                0x116F
#define OBJ_EVENT_PAL_TAG_AROMA_LADY              0x1170
#define OBJ_EVENT_PAL_TAG_ARTIST_1                0x1171
#define OBJ_EVENT_PAL_TAG_ARTIST_2                0x1172
#define OBJ_EVENT_PAL_TAG_ARTIST_3                0x1173
#define OBJ_EVENT_PAL_TAG_BACKPACKER_F            0x1174
#define OBJ_EVENT_PAL_TAG_BACKPACKER_M            0x1175
#define OBJ_EVENT_PAL_TAG_BAKER                   0x1176
#define OBJ_EVENT_PAL_TAG_BATTLEGIRL_1            0x1177
#define OBJ_EVENT_PAL_TAG_BATTLEGIRL_2            0x1178
#define OBJ_EVENT_PAL_TAG_BEAUTY_1                0X1179
#define OBJ_EVENT_PAL_TAG_BEAUTY_2                0x117A
#define OBJ_EVENT_PAL_TAG_BEAUTY_3                0x117B
#define OBJ_EVENT_PAL_TAG_BEAUTY_4                0x117C
#define OBJ_EVENT_PAL_TAG_BENGA                   0x117D
#define OBJ_EVENT_PAL_TAG_BIANCA_1                0x117E
#define OBJ_EVENT_PAL_TAG_BIANCA_2                0x117F
#define OBJ_EVENT_PAL_TAG_BIKER_1                 0x1180
#define OBJ_EVENT_PAL_TAG_BIKER_2                 0x1181
#define OBJ_EVENT_PAL_TAG_BIRDKEEPER_F_1          0x1182
#define OBJ_EVENT_PAL_TAG_BIRDKEEPER_F_2          0x1183
#define OBJ_EVENT_PAL_TAG_BIRDKEEPER_M            0x1184
#define OBJ_EVENT_PAL_TAG_BLACKBELT_1             0x1185
#define OBJ_EVENT_PAL_TAG_BLACKBELT_2             0x1186
#define OBJ_EVENT_PAL_TAG_BLACKBELT_3             0x1187
#define OBJ_EVENT_PAL_TAG_BLAINE                  0x1188
#define OBJ_EVENT_PAL_TAG_BOARDER                 0x1189
#define OBJ_EVENT_PAL_TAG_BOY                     0x118A
#define OBJ_EVENT_PAL_TAG_BRAWLY_1                0x118B
#define OBJ_EVENT_PAL_TAG_BROCK                   0x118C
#define OBJ_EVENT_PAL_TAG_BRYCEN                  0x118D
#define OBJ_EVENT_PAL_TAG_BUG_CATCHER_1           0x118E
#define OBJ_EVENT_PAL_TAG_BURGH                   0x118F
#define OBJ_EVENT_PAL_TAG_BURGLAR                 0x1190
#define OBJ_EVENT_PAL_TAG_BW_MOM                  0x1191
#define OBJ_EVENT_PAL_TAG_BW2_MOM                 0x1192
#define OBJ_EVENT_PAL_TAG_CAITLIN                 0x1193
#define OBJ_EVENT_PAL_TAG_CAMERAMAN_1             0x1194
#define OBJ_EVENT_PAL_TAG_CAMPER_1                0x1195
#define OBJ_EVENT_PAL_TAG_CAPTAIN                 0x1196
#define OBJ_EVENT_PAL_TAG_CEDRIC                  0x1197
#define OBJ_EVENT_PAL_TAG_CHANNELLER              0x1198
#define OBJ_EVENT_PAL_TAG_CHEREN_1                0x1199
#define OBJ_EVENT_PAL_TAG_CHEREN_2                0x119A
#define OBJ_EVENT_PAL_TAG_CHILI                   0x119B
#define OBJ_EVENT_PAL_TAG_CILAN                   0x119C
#define OBJ_EVENT_PAL_TAG_CLAY                    0x119D
#define OBJ_EVENT_PAL_TAG_CLERK_F                 0x119E
#define OBJ_EVENT_PAL_TAG_CLERK_M_1               0x119F
#define OBJ_EVENT_PAL_TAG_CLERK_M_2               0x11A0
#define OBJ_EVENT_PAL_TAG_CLOWN                   0x11A1
#define OBJ_EVENT_PAL_TAG_COLLECTOR               0x11A2
#define OBJ_EVENT_PAL_TAG_COLRESS                 0x11A3
#define OBJ_EVENT_PAL_TAG_CONCORDIA_1             0x11A4
#define OBJ_EVENT_PAL_TAG_CONCORDIA_2             0x11A5
#define OBJ_EVENT_PAL_TAG_COOLTRAINER_F_1         0x11A6
#define OBJ_EVENT_PAL_TAG_COOLTRAINER_F_2         0x11A7
#define OBJ_EVENT_PAL_TAG_COOLTRAINER_F_3         0x11A8
#define OBJ_EVENT_PAL_TAG_COOLTRAINER_F_4         0x11A9
#define OBJ_EVENT_PAL_TAG_COOLTRAINER_M_1         0x11AA
#define OBJ_EVENT_PAL_TAG_COOLTRAINER_M_2         0x11AB
#define OBJ_EVENT_PAL_TAG_COOLTRAINER_M_3         0x11AC
#define OBJ_EVENT_PAL_TAG_COOLTRAINER_M_4         0x11AD
#define OBJ_EVENT_PAL_TAG_COWGIRL                 0x11AE
#define OBJ_EVENT_PAL_TAG_CRESS                   0x11AF
#define OBJ_EVENT_PAL_TAG_CURTIS_1                0x11B0
#define OBJ_EVENT_PAL_TAG_CURTIS_2                0x11B1
#define OBJ_EVENT_PAL_TAG_CYCLIST_F_1             0x11B2
#define OBJ_EVENT_PAL_TAG_CYCLIST_F_2             0x11B3
#define OBJ_EVENT_PAL_TAG_CYCLIST_M_1             0x11B4
#define OBJ_EVENT_PAL_TAG_CYCLIST_M_2             0x11B5
#define OBJ_EVENT_PAL_TAG_DANCER                  0x11B6
#define OBJ_EVENT_PAL_TAG_DEPOTAGENT              0x11B7
#define OBJ_EVENT_PAL_TAG_DOCTOR                  0x11B8
#define OBJ_EVENT_PAL_TAG_DRAGONTAMER             0x11B9
#define OBJ_EVENT_PAL_TAG_DRAYDEN                 0x11BA
#define OBJ_EVENT_PAL_TAG_ELDER                   0x11BB
#define OBJ_EVENT_PAL_TAG_ELESA_1                 0x11BC
#define OBJ_EVENT_PAL_TAG_ELESA_2                 0x11BD
#define OBJ_EVENT_PAL_TAG_EMMET                   0x11BE
#define OBJ_EVENT_PAL_TAG_ERICA                   0x11BF
#define OBJ_EVENT_PAL_TAG_ETHAN                   0x11C0
#define OBJ_EVENT_PAL_TAG_EXECUTIVE_F             0x11C1
#define OBJ_EVENT_PAL_TAG_EXECUTIVE_M_1           0x11C2
#define OBJ_EVENT_PAL_TAG_EXECUTIVE_M_2           0x11C3
#define OBJ_EVENT_PAL_TAG_EXECUTIVE_M_3           0x11C4
#define OBJ_EVENT_PAL_TAG_FAT_MAN_1               0x11C5
#define OBJ_EVENT_PAL_TAG_FAT_MAN_2               0x11C6
#define OBJ_EVENT_PAL_TAG_FAT_MAN_3               0x11C7
#define OBJ_EVENT_PAL_TAG_FENNEL                  0x11C8
#define OBJ_EVENT_PAL_TAG_FIREBREATHER            0x11C9
#define OBJ_EVENT_PAL_TAG_FISHERMAN_1             0x11CA
#define OBJ_EVENT_PAL_TAG_FISHERMAN_2             0x11CB
#define OBJ_EVENT_PAL_TAG_FLANNERY_1              0x11CC
#define OBJ_EVENT_PAL_TAG_FLAUTIST                0x11CD
#define OBJ_EVENT_PAL_TAG_GAMBLER                 0x11CE
#define OBJ_EVENT_PAL_TAG_GENTLEMAN_1             0x11CF
#define OBJ_EVENT_PAL_TAG_GENTLEMAN_2             0x11D0
#define OBJ_EVENT_PAL_TAG_GENTLEMAN_3             0x11D1
#define OBJ_EVENT_PAL_TAG_GHETHIS                 0x11D2
#define OBJ_EVENT_PAL_TAG_GIOVANNI                0x11D3
#define OBJ_EVENT_PAL_TAG_GRIMSLEY                0x11D4
#define OBJ_EVENT_PAL_TAG_GUIDE_F                 0x11D5
#define OBJ_EVENT_PAL_TAG_GUIDE_M                 0x11D6
#define OBJ_EVENT_PAL_TAG_GUITARIST_1             0x11D7
#define OBJ_EVENT_PAL_TAG_GUITARIST_2             0x11D8
#define OBJ_EVENT_PAL_TAG_GUITARIST_3             0x11D9
#define OBJ_EVENT_PAL_TAG_GUITARIST_F_1           0x11DA
#define OBJ_EVENT_PAL_TAG_GUITARIST_F_2           0x11DB
#define OBJ_EVENT_PAL_TAG_GUZMA                   0x11DC
#define OBJ_EVENT_PAL_TAG_GYM_GUIDE               0x11DD
#define OBJ_EVENT_PAL_TAG_HARLEQUIN               0x11DE
#define OBJ_EVENT_PAL_TAG_HARMONICA               0x11DF
#define OBJ_EVENT_PAL_TAG_HIKER_1                 0x11E0
#define OBJ_EVENT_PAL_TAG_HIKER_2                 0x11E1
#define OBJ_EVENT_PAL_TAG_HOOPSTER                0x11E2
#define OBJ_EVENT_PAL_TAG_HUGH                    0x11E3
#define OBJ_EVENT_PAL_TAG_IDOL                    0x11E4
#define OBJ_EVENT_PAL_TAG_INFIELDER               0x11E5
#define OBJ_EVENT_PAL_TAG_INGO                    0x11E6
#define OBJ_EVENT_PAL_TAG_IRIS_1                  0x11E7
#define OBJ_EVENT_PAL_TAG_IRIS_2                  0x11E8
#define OBJ_EVENT_PAL_TAG_JANITOR                 0x11E9
#define OBJ_EVENT_PAL_TAG_JOGGER_1                0x11EA
#define OBJ_EVENT_PAL_TAG_JOGGER_2                0x11EB
#define OBJ_EVENT_PAL_TAG_JOGGER_3                0x11EC
#define OBJ_EVENT_PAL_TAG_JUGGLER                 0x11ED
#define OBJ_EVENT_PAL_TAG_KEYTAURIST              0x11EE
#define OBJ_EVENT_PAL_TAG_KIMONO_GIRL             0x11EF
#define OBJ_EVENT_PAL_TAG_KOGA                    0x11F0
#define OBJ_EVENT_PAL_TAG_LADY_1                  0x11F1
#define OBJ_EVENT_PAL_TAG_LADY_2                  0x11F2
#define OBJ_EVENT_PAL_TAG_LASS_1                  0x11F3
#define OBJ_EVENT_PAL_TAG_LASS_2                  0x11F4
#define OBJ_EVENT_PAL_TAG_LASS_3                  0x11F5
#define OBJ_EVENT_PAL_TAG_LEONORA_1               0x11F6
#define OBJ_EVENT_PAL_TAG_LEONORA_2               0x11F7
#define OBJ_EVENT_PAL_TAG_LINEBACKER              0x11F8
#define OBJ_EVENT_PAL_TAG_LIZA_1                  0x11F9
#define OBJ_EVENT_PAL_TAG_LT_SURGE                0x11FA
#define OBJ_EVENT_PAL_TAG_LYRA                    0x11FB
#define OBJ_EVENT_PAL_TAG_MAID_1                  0x11FC
#define OBJ_EVENT_PAL_TAG_MAID_2                  0x11FD
#define OBJ_EVENT_PAL_TAG_MAN_6                   0x11FE
#define OBJ_EVENT_PAL_TAG_MAN_7                   0x11FF
#define OBJ_EVENT_PAL_TAG_MAN_8                   0x1200
#define OBJ_EVENT_PAL_TAG_MARLIN_SWIM             0x1201
#define OBJ_EVENT_PAL_TAG_MARLIN                  0x1202
#define OBJ_EVENT_PAL_TAG_MARSHALL                0x1203
#define OBJ_EVENT_PAL_TAG_MEDAL_GUY               0x1204
#define OBJ_EVENT_PAL_TAG_MEDIUM                  0x1205
#define OBJ_EVENT_PAL_TAG_MISTY                   0x1206
#define OBJ_EVENT_PAL_TAG_N                       0x1207
#define OBJ_EVENT_PAL_TAG_NEO_GHETHIS             0x1208
#define OBJ_EVENT_PAL_TAG_NEO_PLASMA_F            0x1209
#define OBJ_EVENT_PAL_TAG_NEO_PLASMA_M            0x120A
#define OBJ_EVENT_PAL_TAG_NEO_ZINZOLIN            0x120B
#define OBJ_EVENT_PAL_TAG_NINJA_BOY_1             0x120C
#define OBJ_EVENT_PAL_TAG_NORMAN_1                0x120D
#define OBJ_EVENT_PAL_TAG_NURSE_1                 0x120E
#define OBJ_EVENT_PAL_TAG_NURSE_JOY               0x120F
#define OBJ_EVENT_PAL_TAG_NURSERY_AIDE            0x1210
#define OBJ_EVENT_PAL_TAG_OLD_WOMAN_1             0x1211
#define OBJ_EVENT_PAL_TAG_PARASOL_LADY_1          0x1212
#define OBJ_EVENT_PAL_TAG_PARASOL_LADY_2          0x1213
#define OBJ_EVENT_PAL_TAG_PICNICKER_1             0x1214
#define OBJ_EVENT_PAL_TAG_PIERS                   0x1215
#define OBJ_EVENT_PAL_TAG_PILOT                   0x1216
#define OBJ_EVENT_PAL_TAG_POKEFAN_F_1             0x1217
#define OBJ_EVENT_PAL_TAG_POKEFAN_F_2             0x1218
#define OBJ_EVENT_PAL_TAG_POKEFAN_M_1             0x1219
#define OBJ_EVENT_PAL_TAG_POKEFAN_M_2             0x121A
#define OBJ_EVENT_PAL_TAG_POKEKID                 0x121B
#define OBJ_EVENT_PAL_TAG_POKEMANIAC              0x121C
#define OBJ_EVENT_PAL_TAG_POKEMART                0x121D
#define OBJ_EVENT_PAL_TAG_POKEMON_BREEDER_F_1     0x121E
#define OBJ_EVENT_PAL_TAG_POKEMON_BREEDER_F_2     0x121F
#define OBJ_EVENT_PAL_TAG_POKEMON_BREEDER_M_1     0x1220
#define OBJ_EVENT_PAL_TAG_POKEMON_BREEDER_M_2     0x1221
#define OBJ_EVENT_PAL_TAG_POKEMON_RANGER_F_1      0x1222
#define OBJ_EVENT_PAL_TAG_POKEMON_RANGER_F_2      0x1223
#define OBJ_EVENT_PAL_TAG_POKEMON_RANGER_M_1      0x1224
#define OBJ_EVENT_PAL_TAG_POKEMON_RANGER_M_2      0x1225
#define OBJ_EVENT_PAL_TAG_POLICEMAN_1             0x1226
#define OBJ_EVENT_PAL_TAG_POLICEMAN_2             0x1227
#define OBJ_EVENT_PAL_TAG_POSTMAN                 0x1228
#define OBJ_EVENT_PAL_TAG_PRESCHOOLER_F           0x1229
#define OBJ_EVENT_PAL_TAG_PRESCHOOLER_M           0x122A
#define OBJ_EVENT_PAL_TAG_PROFESSOR_JUNIPER       0x122B
#define OBJ_EVENT_PAL_TAG_PROFESSOR_OAK           0x122C
#define OBJ_EVENT_PAL_TAG_PSYCHIC_F_1             0x122D
#define OBJ_EVENT_PAL_TAG_PSYCHIC_F_2             0x122E
#define OBJ_EVENT_PAL_TAG_PSYCHIC_M_1             0x122F
#define OBJ_EVENT_PAL_TAG_PSYCHIC_M_2             0x1230
#define OBJ_EVENT_PAL_TAG_PT_DAWN                 0x1231
#define OBJ_EVENT_PAL_TAG_PT_LUCAS                0x1232
#define OBJ_EVENT_PAL_TAG_RANCHER                 0x1233
#define OBJ_EVENT_PAL_TAG_RECEPTIONIST_1          0x1234
#define OBJ_EVENT_PAL_TAG_RECEPTIONIST_2          0x1235
#define OBJ_EVENT_PAL_TAG_RECEPTIONIST_3          0x1236
#define OBJ_EVENT_PAL_TAG_REPORTER                0x1237
#define OBJ_EVENT_PAL_TAG_RICH_BOY_1              0x1238
#define OBJ_EVENT_PAL_TAG_RICH_BOY_2              0x1239
#define OBJ_EVENT_PAL_TAG_RICH_MAN                0x123A
#define OBJ_EVENT_PAL_TAG_ROUGHNECK_1             0x123B
#define OBJ_EVENT_PAL_TAG_ROUGHNECK_2             0x123C
#define OBJ_EVENT_PAL_TAG_ROXANNE_1               0x123D
#define OBJ_EVENT_PAL_TAG_ROXIE                   0x123E
#define OBJ_EVENT_PAL_TAG_RUIN_MANIAC             0x123F
#define OBJ_EVENT_PAL_TAG_SABRINA                 0x1240
#define OBJ_EVENT_PAL_TAG_SAGE_BRONIUS            0x1241
#define OBJ_EVENT_PAL_TAG_SAGE_GIALLO             0x1242
#define OBJ_EVENT_PAL_TAG_SAGE_GORM               0x1243
#define OBJ_EVENT_PAL_TAG_SAGE_ROOD               0x1244
#define OBJ_EVENT_PAL_TAG_SAGE_RYOKU              0x1245
#define OBJ_EVENT_PAL_TAG_SAGE_ZINZOLIN           0x1246
#define OBJ_EVENT_PAL_TAG_SAGE                    0x1247
#define OBJ_EVENT_PAL_TAG_SAILOR_1                0x1248
#define OBJ_EVENT_PAL_TAG_SCHOOLKID_F             0x1249
#define OBJ_EVENT_PAL_TAG_SCHOOLKID_M_1           0x124A
#define OBJ_EVENT_PAL_TAG_SCIENTIST_F             0x124B
#define OBJ_EVENT_PAL_TAG_SCIENTIST_M_1           0x124C
#define OBJ_EVENT_PAL_TAG_SCIENTIST_M_2           0x124D
#define OBJ_EVENT_PAL_TAG_SCIENTIST_M_3           0x124E
#define OBJ_EVENT_PAL_TAG_SHADOW_TRIAD            0x124F
#define OBJ_EVENT_PAL_TAG_SHADY_GUY               0x1250
#define OBJ_EVENT_PAL_TAG_SHAUNTAL                0x1251
#define OBJ_EVENT_PAL_TAG_SILVER                  0x1252
#define OBJ_EVENT_PAL_TAG_SINGER                  0x1253
#define OBJ_EVENT_PAL_TAG_SKIER_F_1               0x1254
#define OBJ_EVENT_PAL_TAG_SKIER_F_2               0x1255
#define OBJ_EVENT_PAL_TAG_SKIER_M                 0x1256
#define OBJ_EVENT_PAL_TAG_SKYLA                   0x1257
#define OBJ_EVENT_PAL_TAG_SMASHER                 0x1258
#define OBJ_EVENT_PAL_TAG_SOCIALITE_1             0x1259
#define OBJ_EVENT_PAL_TAG_SOCIALITE_2             0x125A
#define OBJ_EVENT_PAL_TAG_STRIKER                 0x125B
#define OBJ_EVENT_PAL_TAG_SUPERNERD               0x125C
#define OBJ_EVENT_PAL_TAG_SWIMMER_F_1             0x125D
#define OBJ_EVENT_PAL_TAG_SWIMMER_F_2             0x125E
#define OBJ_EVENT_PAL_TAG_SWIMMER_F_3             0x125F
#define OBJ_EVENT_PAL_TAG_SWIMMER_M_1             0x1260
#define OBJ_EVENT_PAL_TAG_SWIMMER_M_2             0x1261
#define OBJ_EVENT_PAL_TAG_SWIMMER_M_3             0x1262
#define OBJ_EVENT_PAL_TAG_TATE_1                  0x1263
#define OBJ_EVENT_PAL_TAG_TEACHER                 0x1264
#define OBJ_EVENT_PAL_TAG_TEAM_PLASMA_F           0x1265
#define OBJ_EVENT_PAL_TAG_TEAM_PLASMA_M           0x1266
#define OBJ_EVENT_PAL_TAG_TEAM_ROCKET_F           0x1267
#define OBJ_EVENT_PAL_TAG_TEAM_ROCKET_M           0x1268
#define OBJ_EVENT_PAL_TAG_TRUMPETER               0x1269
#define OBJ_EVENT_PAL_TAG_TUBER_F_1               0x126A
#define OBJ_EVENT_PAL_TAG_TUBER_M_1               0x126B
#define OBJ_EVENT_PAL_TAG_TWINS_1                 0x126C
#define OBJ_EVENT_PAL_TAG_TWINS_2                 0x126D
#define OBJ_EVENT_PAL_TAG_TWINS_3                 0x126E
#define OBJ_EVENT_PAL_TAG_ULTIMA                  0x126F
#define OBJ_EVENT_PAL_TAG_VETRAN_F                0x1270
#define OBJ_EVENT_PAL_TAG_VETRAN_M_1              0x1271
#define OBJ_EVENT_PAL_TAG_VETRAN_M_2              0x1272
#define OBJ_EVENT_PAL_TAG_WAITER_1                0x1273
#define OBJ_EVENT_PAL_TAG_WAITER_2                0x1274
#define OBJ_EVENT_PAL_TAG_WAITRESS_1              0x1275
#define OBJ_EVENT_PAL_TAG_WAITRESS_2              0x1276
#define OBJ_EVENT_PAL_TAG_WALLACE_1               0x1277
#define OBJ_EVENT_PAL_TAG_WATTSON_1               0x1278
#define OBJ_EVENT_PAL_TAG_WINONA_1                0x1279
#define OBJ_EVENT_PAL_TAG_WOMAN_6                 0x127A
#define OBJ_EVENT_PAL_TAG_WOMAN_7                 0x127B
#define OBJ_EVENT_PAL_TAG_WOMAN_8                 0x127C
#define OBJ_EVENT_PAL_TAG_WOMAN_9                 0x127D
#define OBJ_EVENT_PAL_TAG_WOMAN_10                0x127E
#define OBJ_EVENT_PAL_TAG_WOMAN_11                0x127F
#define OBJ_EVENT_PAL_TAG_WORKER_1                0x1280
#define OBJ_EVENT_PAL_TAG_WORKER_2                0x1281
#define OBJ_EVENT_PAL_TAG_WORKER_3                0x1282
#define OBJ_EVENT_PAL_TAG_YANCY_1                 0x1283
#define OBJ_EVENT_PAL_TAG_YANCY_2                 0x1284
#define OBJ_EVENT_PAL_TAG_YOUNGSTER_1             0x1285
#define OBJ_EVENT_PAL_TAG_YOUNGSTER_2             0x1286
#define OBJ_EVENT_PAL_TAG_YOUNGSTER_3             0x1287
// Used as a placeholder follower graphic
#define OBJ_EVENT_PAL_TAG_SUBSTITUTE              0x7611
#define OBJ_EVENT_PAL_TAG_EMOTES                  0x8002
// Not a real OW palette tag; used for the white flash applied to followers
#define OBJ_EVENT_PAL_TAG_WHITE                   (OBJ_EVENT_PAL_TAG_NONE - 1)
#define OBJ_EVENT_PAL_TAG_NONE                    0x12FF

// This + localId is used as the tileTag
// for compressed graphicsInfos
// '(C)ompressed (E)vent'
#define COMP_OW_TILE_TAG_BASE 0xCE00

#endif  // GUARD_CONSTANTS_EVENT_OBJECTS_H
