#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

#include "constants/global.h"
#include "constants/map_event_ids.h"

#define PLAYER_AVATAR_GFX_MALE_NORMAL     (IS_FRLG ? OBJ_EVENT_GFX_RED_NORMAL     : OBJ_EVENT_GFX_LUCAS_NORMAL)
#define PLAYER_AVATAR_GFX_MALE_MACH_BIKE  (IS_FRLG ? OBJ_EVENT_GFX_RED_BIKE       : OBJ_EVENT_GFX_LUCAS_MACH_BIKE)
#define PLAYER_AVATAR_GFX_MALE_ACRO_BIKE  (IS_FRLG ? OBJ_EVENT_GFX_RED_BIKE       : OBJ_EVENT_GFX_LUCAS_ACRO_BIKE)
#define PLAYER_AVATAR_GFX_MALE_SURFING    (IS_FRLG ? OBJ_EVENT_GFX_RED_SURF       : OBJ_EVENT_GFX_LUCAS_SURFING)
#define PLAYER_AVATAR_GFX_MALE_UNDERWATER (IS_FRLG ? OBJ_EVENT_GFX_RED_SURF       : OBJ_EVENT_GFX_LUCAS_UNDERWATER)
#define PLAYER_AVATAR_GFX_MALE_FIELD_MOVE (IS_FRLG ? OBJ_EVENT_GFX_RED_FIELD_MOVE : OBJ_EVENT_GFX_LUCAS_FIELD_MOVE)
#define PLAYER_AVATAR_GFX_MALE_FISHING    (IS_FRLG ? OBJ_EVENT_GFX_RED_FISH       : OBJ_EVENT_GFX_LUCAS_FISHING)
#define PLAYER_AVATAR_GFX_MALE_WATERING   (IS_FRLG ? OBJ_EVENT_GFX_RED_FIELD_MOVE : OBJ_EVENT_GFX_LUCAS_WATERING)
#define PLAYER_AVATAR_GFX_MALE_VSSEEKER   (IS_FRLG ? OBJ_EVENT_GFX_RED_VS_SEEKER  : OBJ_EVENT_GFX_LUCAS_FIELD_MOVE)
#define PLAYER_AVATAR_GFX_FEMALE_NORMAL     (IS_FRLG ? OBJ_EVENT_GFX_GREEN_NORMAL     : OBJ_EVENT_GFX_DAWN_NORMAL)
#define PLAYER_AVATAR_GFX_FEMALE_MACH_BIKE  (IS_FRLG ? OBJ_EVENT_GFX_GREEN_BIKE       : OBJ_EVENT_GFX_DAWN_MACH_BIKE)
#define PLAYER_AVATAR_GFX_FEMALE_ACRO_BIKE  (IS_FRLG ? OBJ_EVENT_GFX_GREEN_BIKE       : OBJ_EVENT_GFX_DAWN_ACRO_BIKE)
#define PLAYER_AVATAR_GFX_FEMALE_SURFING    (IS_FRLG ? OBJ_EVENT_GFX_GREEN_SURF       : OBJ_EVENT_GFX_DAWN_SURFING)
#define PLAYER_AVATAR_GFX_FEMALE_UNDERWATER (IS_FRLG ? OBJ_EVENT_GFX_GREEN_SURF       : OBJ_EVENT_GFX_DAWN_UNDERWATER)
#define PLAYER_AVATAR_GFX_FEMALE_FIELD_MOVE (IS_FRLG ? OBJ_EVENT_GFX_GREEN_FIELD_MOVE : OBJ_EVENT_GFX_DAWN_FIELD_MOVE)
#define PLAYER_AVATAR_GFX_FEMALE_FISHING    (IS_FRLG ? OBJ_EVENT_GFX_GREEN_FISH       : OBJ_EVENT_GFX_DAWN_FISHING)
#define PLAYER_AVATAR_GFX_FEMALE_WATERING   (IS_FRLG ? OBJ_EVENT_GFX_GREEN_FIELD_MOVE : OBJ_EVENT_GFX_DAWN_WATERING)
#define PLAYER_AVATAR_GFX_FEMALE_VSSEEKER   (IS_FRLG ? OBJ_EVENT_GFX_GREEN_VS_SEEKER  : OBJ_EVENT_GFX_DAWN_FIELD_MOVE)

enum
{
    OBJ_EVENT_GFX_BRENDAN_NORMAL,
    OBJ_EVENT_GFX_BRENDAN_MACH_BIKE,
    OBJ_EVENT_GFX_BRENDAN_SURFING,
    OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE,
    OBJ_EVENT_GFX_QUINTY_PLUMP,
    OBJ_EVENT_GFX_NINJA_BOY,
    OBJ_EVENT_GFX_TWIN,
    OBJ_EVENT_GFX_BOY_1,
    OBJ_EVENT_GFX_GIRL_1,
    OBJ_EVENT_GFX_BOY_2,
    OBJ_EVENT_GFX_GIRL_2,
    OBJ_EVENT_GFX_LITTLE_BOY,
    OBJ_EVENT_GFX_LITTLE_GIRL,
    OBJ_EVENT_GFX_BOY_3,
    OBJ_EVENT_GFX_GIRL_3,
    OBJ_EVENT_GFX_RICH_BOY,
    OBJ_EVENT_GFX_WOMAN_1,
    OBJ_EVENT_GFX_FAT_MAN,
    OBJ_EVENT_GFX_POKEFAN_F,
    OBJ_EVENT_GFX_MAN_1,
    OBJ_EVENT_GFX_WOMAN_2,
    OBJ_EVENT_GFX_EXPERT_M,
    OBJ_EVENT_GFX_EXPERT_F,
    OBJ_EVENT_GFX_MAN_2,
    OBJ_EVENT_GFX_WOMAN_3,
    OBJ_EVENT_GFX_POKEFAN_M,
    OBJ_EVENT_GFX_WOMAN_4,
    OBJ_EVENT_GFX_COOK,
    OBJ_EVENT_GFX_LINK_RECEPTIONIST,
    OBJ_EVENT_GFX_OLD_MAN,
    OBJ_EVENT_GFX_OLD_WOMAN,
    OBJ_EVENT_GFX_CAMPER,
    OBJ_EVENT_GFX_PICNICKER,
    OBJ_EVENT_GFX_MAN_3,
    OBJ_EVENT_GFX_WOMAN_5,
    OBJ_EVENT_GFX_YOUNGSTER,
    OBJ_EVENT_GFX_BUG_CATCHER,
    OBJ_EVENT_GFX_PSYCHIC_M,
    OBJ_EVENT_GFX_SCHOOL_KID_M,
    OBJ_EVENT_GFX_MANIAC,
    OBJ_EVENT_GFX_HEX_MANIAC,
    OBJ_EVENT_GFX_RAYQUAZA_STILL,
    OBJ_EVENT_GFX_SWIMMER_M,
    OBJ_EVENT_GFX_SWIMMER_F,
    OBJ_EVENT_GFX_BLACK_BELT,
    OBJ_EVENT_GFX_BEAUTY,
    OBJ_EVENT_GFX_SCIENTIST_1,
    OBJ_EVENT_GFX_LASS,
    OBJ_EVENT_GFX_GENTLEMAN,
    OBJ_EVENT_GFX_SAILOR,
    OBJ_EVENT_GFX_FISHERMAN,
    OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M,
    OBJ_EVENT_GFX_RUNNING_TRIATHLETE_F,
    OBJ_EVENT_GFX_TUBER_F,
    OBJ_EVENT_GFX_TUBER_M,
    OBJ_EVENT_GFX_HIKER,
    OBJ_EVENT_GFX_CYCLING_TRIATHLETE_M,
    OBJ_EVENT_GFX_CYCLING_TRIATHLETE_F,
    OBJ_EVENT_GFX_NURSE,
    OBJ_EVENT_GFX_ITEM_BALL,
    OBJ_EVENT_GFX_BERRY_TREE,
    OBJ_EVENT_GFX_BERRY_TREE_EARLY_STAGES,
    OBJ_EVENT_GFX_BERRY_TREE_LATE_STAGES,
    OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE,
    OBJ_EVENT_GFX_PROF_BIRCH,
    OBJ_EVENT_GFX_MAN_4,
    OBJ_EVENT_GFX_MAN_5,
    OBJ_EVENT_GFX_REPORTER_M,
    OBJ_EVENT_GFX_REPORTER_F,
    OBJ_EVENT_GFX_BARD,
    OBJ_EVENT_GFX_ANABEL,
    OBJ_EVENT_GFX_TUCKER,
    OBJ_EVENT_GFX_GRETA,
    OBJ_EVENT_GFX_SPENSER,
    OBJ_EVENT_GFX_NOLAND,
    OBJ_EVENT_GFX_LUCY,
    OBJ_EVENT_GFX_UNUSED_NATU_DOLL,
    OBJ_EVENT_GFX_UNUSED_MAGNEMITE_DOLL,
    OBJ_EVENT_GFX_UNUSED_SQUIRTLE_DOLL,
    OBJ_EVENT_GFX_UNUSED_WOOPER_DOLL,
    OBJ_EVENT_GFX_UNUSED_PIKACHU_DOLL,
    OBJ_EVENT_GFX_UNUSED_PORYGON2_DOLL,
    OBJ_EVENT_GFX_CUTTABLE_TREE,
    OBJ_EVENT_GFX_MART_EMPLOYEE,
    OBJ_EVENT_GFX_ROOFTOP_SALE_WOMAN,
    OBJ_EVENT_GFX_TEALA,
    OBJ_EVENT_GFX_BREAKABLE_ROCK,
    OBJ_EVENT_GFX_PUSHABLE_BOULDER,
    OBJ_EVENT_GFX_MR_BRINEYS_BOAT,
    OBJ_EVENT_GFX_MAY_NORMAL,
    OBJ_EVENT_GFX_MAY_MACH_BIKE,
    OBJ_EVENT_GFX_MAY_ACRO_BIKE,
    OBJ_EVENT_GFX_MAY_SURFING,
    OBJ_EVENT_GFX_MAY_FIELD_MOVE,
    OBJ_EVENT_GFX_TRUCK,
    OBJ_EVENT_GFX_VIGOROTH_CARRYING_BOX,
    OBJ_EVENT_GFX_VIGOROTH_FACING_AWAY,
    OBJ_EVENT_GFX_BIRCHS_BAG,
    OBJ_EVENT_GFX_ZIGZAGOON_1,
    OBJ_EVENT_GFX_ARTIST,
    OBJ_EVENT_GFX_RIVAL_LUCAS_NORMAL,
    OBJ_EVENT_GFX_RIVAL_LUCAS_MACH_BIKE,
    OBJ_EVENT_GFX_RIVAL_LUCAS_ACRO_BIKE,
    OBJ_EVENT_GFX_RIVAL_LUCAS_SURFING,
    OBJ_EVENT_GFX_RIVAL_LUCAS_FIELD_MOVE,
    OBJ_EVENT_GFX_RIVAL_DAWN_NORMAL,
    OBJ_EVENT_GFX_RIVAL_DAWN_MACH_BIKE,
    OBJ_EVENT_GFX_RIVAL_DAWN_ACRO_BIKE,
    OBJ_EVENT_GFX_RIVAL_DAWN_SURFING,
    OBJ_EVENT_GFX_RIVAL_DAWN_FIELD_MOVE,
    OBJ_EVENT_GFX_CAMERAMAN,
    OBJ_EVENT_GFX_LUCAS_UNDERWATER,
    OBJ_EVENT_GFX_DAWN_UNDERWATER,
    OBJ_EVENT_GFX_MOVING_BOX,
    OBJ_EVENT_GFX_CABLE_CAR,
    OBJ_EVENT_GFX_SCIENTIST_2,
    OBJ_EVENT_GFX_DEVON_EMPLOYEE,
    OBJ_EVENT_GFX_AQUA_MEMBER_M,
    OBJ_EVENT_GFX_AQUA_MEMBER_F,
    OBJ_EVENT_GFX_MAGMA_MEMBER_M,
    OBJ_EVENT_GFX_MAGMA_MEMBER_F,
    OBJ_EVENT_GFX_SIDNEY,
    OBJ_EVENT_GFX_PHOEBE,
    OBJ_EVENT_GFX_GLACIA,
    OBJ_EVENT_GFX_DRAKE,
    OBJ_EVENT_GFX_ROXANNE,
    OBJ_EVENT_GFX_BRAWLY,
    OBJ_EVENT_GFX_WATTSON,
    OBJ_EVENT_GFX_FLANNERY,
    OBJ_EVENT_GFX_NORMAN,
    OBJ_EVENT_GFX_WINONA,
    OBJ_EVENT_GFX_LIZA,
    OBJ_EVENT_GFX_TATE,
    OBJ_EVENT_GFX_WALLACE,
    OBJ_EVENT_GFX_STEVEN,
    OBJ_EVENT_GFX_WALLY,
    OBJ_EVENT_GFX_LITTLE_BOY_3,
    OBJ_EVENT_GFX_LUCAS_FISHING,
    OBJ_EVENT_GFX_DAWN_FISHING,
    OBJ_EVENT_GFX_HOT_SPRINGS_OLD_WOMAN,
    OBJ_EVENT_GFX_SS_TIDAL,
    OBJ_EVENT_GFX_SUBMARINE_SHADOW,
    OBJ_EVENT_GFX_PICHU_DOLL,
    OBJ_EVENT_GFX_PIKACHU_DOLL,
    OBJ_EVENT_GFX_MARILL_DOLL,
    OBJ_EVENT_GFX_TOGEPI_DOLL,
    OBJ_EVENT_GFX_CYNDAQUIL_DOLL,
    OBJ_EVENT_GFX_CHIKORITA_DOLL,
    OBJ_EVENT_GFX_TOTODILE_DOLL,
    OBJ_EVENT_GFX_JIGGLYPUFF_DOLL,
    OBJ_EVENT_GFX_MEOWTH_DOLL,
    OBJ_EVENT_GFX_CLEFAIRY_DOLL,
    OBJ_EVENT_GFX_DITTO_DOLL,
    OBJ_EVENT_GFX_SMOOCHUM_DOLL,
    OBJ_EVENT_GFX_TREECKO_DOLL,
    OBJ_EVENT_GFX_TORCHIC_DOLL,
    OBJ_EVENT_GFX_MUDKIP_DOLL,
    OBJ_EVENT_GFX_DUSKULL_DOLL,
    OBJ_EVENT_GFX_WYNAUT_DOLL,
    OBJ_EVENT_GFX_BALTOY_DOLL,
    OBJ_EVENT_GFX_KECLEON_DOLL,
    OBJ_EVENT_GFX_AZURILL_DOLL,
    OBJ_EVENT_GFX_SKITTY_DOLL,
    OBJ_EVENT_GFX_SWABLU_DOLL,
    OBJ_EVENT_GFX_GULPIN_DOLL,
    OBJ_EVENT_GFX_LOTAD_DOLL,
    OBJ_EVENT_GFX_SEEDOT_DOLL,
    OBJ_EVENT_GFX_PIKA_CUSHION,
    OBJ_EVENT_GFX_ROUND_CUSHION,
    OBJ_EVENT_GFX_KISS_CUSHION,
    OBJ_EVENT_GFX_ZIGZAG_CUSHION,
    OBJ_EVENT_GFX_SPIN_CUSHION,
    OBJ_EVENT_GFX_DIAMOND_CUSHION,
    OBJ_EVENT_GFX_BALL_CUSHION,
    OBJ_EVENT_GFX_GRASS_CUSHION,
    OBJ_EVENT_GFX_FIRE_CUSHION,
    OBJ_EVENT_GFX_WATER_CUSHION,
    OBJ_EVENT_GFX_BIG_SNORLAX_DOLL,
    OBJ_EVENT_GFX_BIG_RHYDON_DOLL,
    OBJ_EVENT_GFX_BIG_LAPRAS_DOLL,
    OBJ_EVENT_GFX_BIG_VENUSAUR_DOLL,
    OBJ_EVENT_GFX_BIG_CHARIZARD_DOLL,
    OBJ_EVENT_GFX_BIG_BLASTOISE_DOLL,
    OBJ_EVENT_GFX_BIG_WAILMER_DOLL,
    OBJ_EVENT_GFX_BIG_REGIROCK_DOLL,
    OBJ_EVENT_GFX_BIG_REGICE_DOLL,
    OBJ_EVENT_GFX_BIG_REGISTEEL_DOLL,
    OBJ_EVENT_GFX_LATIAS,
    OBJ_EVENT_GFX_LATIOS,
    OBJ_EVENT_GFX_GAMEBOY_KID,
    OBJ_EVENT_GFX_CONTEST_JUDGE,
    OBJ_EVENT_GFX_LUCAS_WATERING,
    OBJ_EVENT_GFX_DAWN_WATERING,
    OBJ_EVENT_GFX_BRENDAN_DECORATING,
    OBJ_EVENT_GFX_MAY_DECORATING,
    OBJ_EVENT_GFX_ARCHIE,
    OBJ_EVENT_GFX_MAXIE,
    OBJ_EVENT_GFX_KYOGRE_FRONT,
    OBJ_EVENT_GFX_GROUDON_FRONT,
    OBJ_EVENT_GFX_FOSSIL,
    OBJ_EVENT_GFX_REGIROCK,
    OBJ_EVENT_GFX_REGICE,
    OBJ_EVENT_GFX_REGISTEEL,
    OBJ_EVENT_GFX_SKITTY,
    OBJ_EVENT_GFX_KECLEON,
    OBJ_EVENT_GFX_KYOGRE_ASLEEP,
    OBJ_EVENT_GFX_GROUDON_ASLEEP,
    OBJ_EVENT_GFX_RAYQUAZA,
    OBJ_EVENT_GFX_ZIGZAGOON_2,
    OBJ_EVENT_GFX_PIKACHU,
    OBJ_EVENT_GFX_AZUMARILL,
    OBJ_EVENT_GFX_WINGULL,
    OBJ_EVENT_GFX_KECLEON_BRIDGE_SHADOW,
    OBJ_EVENT_GFX_TUBER_M_SWIMMING,
    OBJ_EVENT_GFX_AZURILL,
    OBJ_EVENT_GFX_MOM,
    OBJ_EVENT_GFX_LINK_LUCAS,
    OBJ_EVENT_GFX_LINK_DAWN,
    OBJ_EVENT_GFX_JUAN,
    OBJ_EVENT_GFX_SCOTT,
    OBJ_EVENT_GFX_POOCHYENA,
    OBJ_EVENT_GFX_KYOGRE_SIDE,
    OBJ_EVENT_GFX_GROUDON_SIDE,
    OBJ_EVENT_GFX_MYSTERY_GIFT_MAN,
    OBJ_EVENT_GFX_TRICK_HOUSE_STATUE,
    OBJ_EVENT_GFX_KIRLIA,
    OBJ_EVENT_GFX_DUSCLOPS,
    OBJ_EVENT_GFX_UNION_ROOM_NURSE,
    OBJ_EVENT_GFX_SUDOWOODO,
    OBJ_EVENT_GFX_MEW,
    OBJ_EVENT_GFX_RED,
    OBJ_EVENT_GFX_LEAF,
    OBJ_EVENT_GFX_DEOXYS,
    OBJ_EVENT_GFX_DEOXYS_TRIANGLE,
    OBJ_EVENT_GFX_BRANDON,
    OBJ_EVENT_GFX_LINK_RS_BRENDAN,
    OBJ_EVENT_GFX_LINK_RS_MAY,
    OBJ_EVENT_GFX_LUGIA,
    OBJ_EVENT_GFX_HOOH,
    OBJ_EVENT_GFX_POKE_BALL,
    OBJ_EVENT_GFX_OW_MON,
    OBJ_EVENT_GFX_LIGHT_SPRITE,
    OBJ_EVENT_GFX_APRICORN_TREE,
    OBJ_EVENT_GFX_RED_NORMAL, // FRLG objects
    OBJ_EVENT_GFX_RED_BIKE,
    OBJ_EVENT_GFX_RED_SURF,
    OBJ_EVENT_GFX_RED_FIELD_MOVE,
    OBJ_EVENT_GFX_RED_FISH,
    OBJ_EVENT_GFX_RED_VS_SEEKER,
    OBJ_EVENT_GFX_RED_VS_SEEKER_BIKE,
    OBJ_EVENT_GFX_UNUSED_250,
    OBJ_EVENT_GFX_GREEN_NORMAL,
    OBJ_EVENT_GFX_GREEN_BIKE,
    OBJ_EVENT_GFX_GREEN_SURF,
    OBJ_EVENT_GFX_GREEN_FIELD_MOVE,
    OBJ_EVENT_GFX_GREEN_FISH,
    OBJ_EVENT_GFX_GREEN_VS_SEEKER,
    OBJ_EVENT_GFX_GREEN_VS_SEEKER_BIKE,
    OBJ_EVENT_GFX_BOY,
    OBJ_EVENT_GFX_CRUSH_GIRL,
    OBJ_EVENT_GFX_MAN,
    OBJ_EVENT_GFX_ROCKER,
    OBJ_EVENT_GFX_BALDING_MAN,
    OBJ_EVENT_GFX_OLD_MAN_1,
    OBJ_EVENT_GFX_OLD_MAN_2,
    OBJ_EVENT_GFX_OLD_MAN_LYING_DOWN,
    OBJ_EVENT_GFX_TUBER_M_WATER,
    OBJ_EVENT_GFX_TUBER_M_LAND,
    OBJ_EVENT_GFX_COOLTRAINER_M,
    OBJ_EVENT_GFX_COOLTRAINER_F,
    OBJ_EVENT_GFX_SWIMMER_M_WATER,
    OBJ_EVENT_GFX_SWIMMER_F_WATER,
    OBJ_EVENT_GFX_SWIMMER_M_LAND,
    OBJ_EVENT_GFX_SWIMMER_F_LAND,
    OBJ_EVENT_GFX_WORKER_M,
    OBJ_EVENT_GFX_WORKER_F,
    OBJ_EVENT_GFX_ROCKET_M,
    OBJ_EVENT_GFX_ROCKET_F,
    OBJ_EVENT_GFX_GBA_KID,
    OBJ_EVENT_GFX_POKE_MANIAC_FRLG,
    OBJ_EVENT_GFX_BIKER,
    OBJ_EVENT_GFX_BLACK_BELT_FRLG,
    OBJ_EVENT_GFX_SCIENTIST,
    OBJ_EVENT_GFX_FISHER,
    OBJ_EVENT_GFX_CHANNELER,
    OBJ_EVENT_GFX_CHEF,
    OBJ_EVENT_GFX_POLICEMAN,
    OBJ_EVENT_GFX_CAPTAIN,
    OBJ_EVENT_GFX_CABLE_CLUB_RECEPTIONIST,
    OBJ_EVENT_GFX_UNION_ROOM_RECEPTIONIST,
    OBJ_EVENT_GFX_CLERK,
    OBJ_EVENT_GFX_MG_DELIVERYMAN,
    OBJ_EVENT_GFX_TRAINER_TOWER_DUDE,
    OBJ_EVENT_GFX_PROF_OAK,
    OBJ_EVENT_GFX_BLUE,
    OBJ_EVENT_GFX_BILL,
    OBJ_EVENT_GFX_LANCE,
    OBJ_EVENT_GFX_AGATHA,
    OBJ_EVENT_GFX_DAISY,
    OBJ_EVENT_GFX_LORELEI,
    OBJ_EVENT_GFX_MR_FUJI,
    OBJ_EVENT_GFX_BRUNO,
    OBJ_EVENT_GFX_BROCK,
    OBJ_EVENT_GFX_MISTY,
    OBJ_EVENT_GFX_LT_SURGE,
    OBJ_EVENT_GFX_ERIKA,
    OBJ_EVENT_GFX_KOGA,
    OBJ_EVENT_GFX_SABRINA,
    OBJ_EVENT_GFX_BLAINE,
    OBJ_EVENT_GFX_GIOVANNI,
    OBJ_EVENT_GFX_CELIO,
    OBJ_EVENT_GFX_TEACHY_TV_HOST,
    OBJ_EVENT_GFX_GYM_GUY,
    OBJ_EVENT_GFX_TOWN_MAP,
    OBJ_EVENT_GFX_POKEDEX,
    OBJ_EVENT_GFX_LITTLE_BOY_FRLG,
    OBJ_EVENT_GFX_LITTLE_GIRL_FRLG,
    OBJ_EVENT_GFX_YOUNGSTER_FRLG,
    OBJ_EVENT_GFX_BUG_CATCHER_FRLG,
    OBJ_EVENT_GFX_LASS_FRLG,
    OBJ_EVENT_GFX_WOMAN_1_FRLG,
    OBJ_EVENT_GFX_FAT_MAN_FRLG,
    OBJ_EVENT_GFX_WOMAN_2_FRLG,
    OBJ_EVENT_GFX_BEAUTY_FRLG,
    OBJ_EVENT_GFX_WOMAN_3_FRLG,
    OBJ_EVENT_GFX_OLD_WOMAN_FRLG,
    OBJ_EVENT_GFX_CAMPER_FRLG,
    OBJ_EVENT_GFX_PICNICKER_FRLG,
    OBJ_EVENT_GFX_MOM_FRLG,
    OBJ_EVENT_GFX_TUBER_F_FRLG,
    OBJ_EVENT_GFX_HIKER_FRLG,
    OBJ_EVENT_GFX_GENTLEMAN_FRLG,
    OBJ_EVENT_GFX_SAILOR_FRLG,
    OBJ_EVENT_GFX_NURSE_FRLG,
    OBJ_EVENT_GFX_FOSSIL_FRLG,
    OBJ_EVENT_GFX_RUBY,
    OBJ_EVENT_GFX_SAPPHIRE,
    OBJ_EVENT_GFX_OLD_AMBER,
    OBJ_EVENT_GFX_GYM_SIGN,
    OBJ_EVENT_GFX_SIGN,
    OBJ_EVENT_GFX_TRAINER_TIPS,
    OBJ_EVENT_GFX_CLIPBOARD,
    OBJ_EVENT_GFX_METEORITE,
    OBJ_EVENT_GFX_LAPRAS_DOLL,
    OBJ_EVENT_GFX_SEAGALLOP,
    OBJ_EVENT_GFX_SNORLAX,
    OBJ_EVENT_GFX_SPEAROW,
    OBJ_EVENT_GFX_CUBONE,
    OBJ_EVENT_GFX_POLIWRATH,
    OBJ_EVENT_GFX_CLEFAIRY,
    OBJ_EVENT_GFX_PIDGEOT,
    OBJ_EVENT_GFX_JIGGLYPUFF,
    OBJ_EVENT_GFX_PIDGEY,
    OBJ_EVENT_GFX_CHANSEY,
    OBJ_EVENT_GFX_OMANYTE,
    OBJ_EVENT_GFX_KANGASKHAN,
    OBJ_EVENT_GFX_PIKACHU_FRLG,
    OBJ_EVENT_GFX_PSYDUCK,
    OBJ_EVENT_GFX_NIDORAN_F,
    OBJ_EVENT_GFX_NIDORAN_M,
    OBJ_EVENT_GFX_NIDORINO,
    OBJ_EVENT_GFX_MEOWTH,
    OBJ_EVENT_GFX_SEEL,
    OBJ_EVENT_GFX_VOLTORB,
    OBJ_EVENT_GFX_SLOWPOKE,
    OBJ_EVENT_GFX_SLOWBRO,
    OBJ_EVENT_GFX_MACHOP,
    OBJ_EVENT_GFX_WIGGLYTUFF,
    OBJ_EVENT_GFX_DODUO,
    OBJ_EVENT_GFX_FEAROW,
    OBJ_EVENT_GFX_MACHOKE,
    OBJ_EVENT_GFX_LAPRAS,
    OBJ_EVENT_GFX_ZAPDOS,
    OBJ_EVENT_GFX_MOLTRES,
    OBJ_EVENT_GFX_ARTICUNO,
    OBJ_EVENT_GFX_MEWTWO,
    OBJ_EVENT_GFX_ENTEI,
    OBJ_EVENT_GFX_SUICUNE,
    OBJ_EVENT_GFX_RAIKOU,
    OBJ_EVENT_GFX_CELEBI,
    OBJ_EVENT_GFX_KABUTO,
    OBJ_EVENT_GFX_DEOXYS_D,
    OBJ_EVENT_GFX_DEOXYS_A,
    OBJ_EVENT_GFX_DEOXYS_N,
    OBJ_EVENT_GFX_SS_ANNE,
    OBJ_EVENT_GFX_AARON,
    OBJ_EVENT_GFX_ACCORDIANIST,
    OBJ_EVENT_GFX_ACTOR,
    OBJ_EVENT_GFX_ADHIRA,
    OBJ_EVENT_GFX_AGATHA_1,
    OBJ_EVENT_GFX_AHAB,
    OBJ_EVENT_GFX_AKARI,
    OBJ_EVENT_GFX_ALDER,
    OBJ_EVENT_GFX_AMELIA,
    OBJ_EVENT_GFX_ANTHEA,
    OBJ_EVENT_GFX_AROMA_LADY,
    OBJ_EVENT_GFX_ARTIST_1,
    OBJ_EVENT_GFX_ARTIST_2,
    OBJ_EVENT_GFX_ARTIST_3,
    OBJ_EVENT_GFX_AUDREY,
    OBJ_EVENT_GFX_BACKPACKER_F,
    OBJ_EVENT_GFX_BACKPACKER_M,
    OBJ_EVENT_GFX_BAKER,
    OBJ_EVENT_GFX_BATTLEGIRL_1,
    OBJ_EVENT_GFX_BATTLEGIRL_2,
    OBJ_EVENT_GFX_BEAUTY_1,
    OBJ_EVENT_GFX_BEAUTY_2,
    OBJ_EVENT_GFX_BEAUTY_3,
    OBJ_EVENT_GFX_BEAUTY_4,
    OBJ_EVENT_GFX_BELLIS,
    OBJ_EVENT_GFX_BENGA,
    OBJ_EVENT_GFX_BERTHA,
    OBJ_EVENT_GFX_BIANCA,
    OBJ_EVENT_GFX_BIKER_1,
    OBJ_EVENT_GFX_BIKER_2,
    OBJ_EVENT_GFX_BIRDKEEPER_F_1,
    OBJ_EVENT_GFX_BIRDKEEPER_F_2,
    OBJ_EVENT_GFX_BIRDKEEPER_M,
    OBJ_EVENT_GFX_BLACKBELT_1,
    OBJ_EVENT_GFX_BLACKBELT_2,
    OBJ_EVENT_GFX_BLACKBELT_3,
    OBJ_EVENT_GFX_BLAINE_1,
    OBJ_EVENT_GFX_BOARDER,
    OBJ_EVENT_GFX_BOY_4,
    OBJ_EVENT_GFX_BRAWLY_1,
    OBJ_EVENT_GFX_BREEDER_F_1,
    OBJ_EVENT_GFX_BREEDER_F_2,
    OBJ_EVENT_GFX_BREEDER_M_1,
    OBJ_EVENT_GFX_BREEDER_M_2,
    OBJ_EVENT_GFX_BROCK_1,
    OBJ_EVENT_GFX_BRUNO_1,
    OBJ_EVENT_GFX_BRYCEN,
    OBJ_EVENT_GFX_BUG_CATCHER_1,
    OBJ_EVENT_GFX_BUGSY,
    OBJ_EVENT_GFX_BURGH,
    OBJ_EVENT_GFX_BURGLAR,
    OBJ_EVENT_GFX_BW_MOM,
    OBJ_EVENT_GFX_BW2_MOM,
    OBJ_EVENT_GFX_BYRON,
    OBJ_EVENT_GFX_CAITLIN,
    OBJ_EVENT_GFX_CALEM,
    OBJ_EVENT_GFX_CAMERAMAN_1,
    OBJ_EVENT_GFX_CAMPER_1,
    OBJ_EVENT_GFX_CANDICE,
    OBJ_EVENT_GFX_CAPTAIN_1,
    OBJ_EVENT_GFX_CARLY,
    OBJ_EVENT_GFX_CARMINE,
    OBJ_EVENT_GFX_CARTER,
    OBJ_EVENT_GFX_CEDRIC,
    OBJ_EVENT_GFX_CHANNELLER,
    OBJ_EVENT_GFX_CHEREN,
    OBJ_EVENT_GFX_CHILI,
    OBJ_EVENT_GFX_CHUCK,
    OBJ_EVENT_GFX_CILAN,
    OBJ_EVENT_GFX_CLAIRE,
    OBJ_EVENT_GFX_CLAY,
    OBJ_EVENT_GFX_CLERK_F,
    OBJ_EVENT_GFX_CLERK_M_1,
    OBJ_EVENT_GFX_CLERK_M_2,
    OBJ_EVENT_GFX_CLOWN,
    OBJ_EVENT_GFX_COLLECTOR,
    OBJ_EVENT_GFX_COLRESS,
    OBJ_EVENT_GFX_CONCORDIA,
    OBJ_EVENT_GFX_COOLTRAINER_F_1,
    OBJ_EVENT_GFX_COOLTRAINER_F_2,
    OBJ_EVENT_GFX_COOLTRAINER_F_3,
    OBJ_EVENT_GFX_COOLTRAINER_F_4,
    OBJ_EVENT_GFX_COOLTRAINER_M_1,
    OBJ_EVENT_GFX_COOLTRAINER_M_2,
    OBJ_EVENT_GFX_COOLTRAINER_M_3,
    OBJ_EVENT_GFX_COOLTRAINER_M_4,
    OBJ_EVENT_GFX_COWGIRL,
    OBJ_EVENT_GFX_CRASHER_WAKE,
    OBJ_EVENT_GFX_CRESS,
    OBJ_EVENT_GFX_CURTIS_1,
    OBJ_EVENT_GFX_CURTIS_2,
    OBJ_EVENT_GFX_CYCLIST_F_1,
    OBJ_EVENT_GFX_CYCLIST_F_2,
    OBJ_EVENT_GFX_CYCLIST_M_1,
    OBJ_EVENT_GFX_CYCLIST_M_2,
    OBJ_EVENT_GFX_CYNTHIA,
    OBJ_EVENT_GFX_DANCER,
    OBJ_EVENT_GFX_DEPOTAGENT,
    OBJ_EVENT_GFX_DIANTHA,
    OBJ_EVENT_GFX_DIVER,
    OBJ_EVENT_GFX_DOCTOR,
    OBJ_EVENT_GFX_DRAGONTAMER,
    OBJ_EVENT_GFX_DRAYDEN,
    OBJ_EVENT_GFX_ELDER,
    OBJ_EVENT_GFX_ELISA,
    OBJ_EVENT_GFX_EMMET,
    OBJ_EVENT_GFX_ERICA_1,
    OBJ_EVENT_GFX_ETHAN_RUN,
    OBJ_EVENT_GFX_ETHAN,
    OBJ_EVENT_GFX_FALKNER,
    OBJ_EVENT_GFX_FANTINA,
    OBJ_EVENT_GFX_FAT_MAN_1,
    OBJ_EVENT_GFX_FAT_MAN_2,
    OBJ_EVENT_GFX_FAT_MAN_3,
    OBJ_EVENT_GFX_FENNEL,
    OBJ_EVENT_GFX_FIREBREATHER,
    OBJ_EVENT_GFX_FISHERMAN_1,
    OBJ_EVENT_GFX_FISHERMAN_2,
    OBJ_EVENT_GFX_FLANNERY_1,
    OBJ_EVENT_GFX_FLAUTIST,
    OBJ_EVENT_GFX_FLINT,
    OBJ_EVENT_GFX_GAMBLER,
    OBJ_EVENT_GFX_GARDENIA,
    OBJ_EVENT_GFX_GEETA,
    OBJ_EVENT_GFX_GENTLEMAN_1,
    OBJ_EVENT_GFX_GENTLEMAN_2,
    OBJ_EVENT_GFX_GENTLEMAN_3,
    OBJ_EVENT_GFX_GLORIA,
    OBJ_EVENT_GFX_GRIMSLEY,
    OBJ_EVENT_GFX_GUIDE_F,
    OBJ_EVENT_GFX_GUIDE_M,
    OBJ_EVENT_GFX_GUITARIST_1,
    OBJ_EVENT_GFX_GUITARIST_2,
    OBJ_EVENT_GFX_GUITARIST_3,
    OBJ_EVENT_GFX_GUITARIST_F_1,
    OBJ_EVENT_GFX_GUITARIST_F_2,
    OBJ_EVENT_GFX_GUZMA,
    OBJ_EVENT_GFX_GYM_GUIDE,
    OBJ_EVENT_GFX_HARLEQUIN,
    OBJ_EVENT_GFX_HARMONICA,
    OBJ_EVENT_GFX_HEX_MANIAC_1,
    OBJ_EVENT_GFX_HIKER_1,
    OBJ_EVENT_GFX_HIKER_2,
    OBJ_EVENT_GFX_HILDA,
    OBJ_EVENT_GFX_HOBIE,
    OBJ_EVENT_GFX_HOOPSTER,
    OBJ_EVENT_GFX_HUGH,
    OBJ_EVENT_GFX_IDOL,
    OBJ_EVENT_GFX_INFIELDER,
    OBJ_EVENT_GFX_INGO,
    OBJ_EVENT_GFX_IRIS,
    OBJ_EVENT_GFX_ISRAEL,
    OBJ_EVENT_GFX_JANINE,
    OBJ_EVENT_GFX_JANITOR,
    OBJ_EVENT_GFX_JASMINE,
    OBJ_EVENT_GFX_JELISSA,
    OBJ_EVENT_GFX_JOGGER_1,
    OBJ_EVENT_GFX_JOGGER_2,
    OBJ_EVENT_GFX_JOGGER_3,
    OBJ_EVENT_GFX_JOSH,
    OBJ_EVENT_GFX_JUAN_1,
    OBJ_EVENT_GFX_JUGGLER,
    OBJ_EVENT_GFX_JUNIPER,
    OBJ_EVENT_GFX_JUNKO,
    OBJ_EVENT_GFX_KAHILI,
    OBJ_EVENT_GFX_KAREN_1,
    OBJ_EVENT_GFX_KEYTAURIST,
    OBJ_EVENT_GFX_KIERAN,
    OBJ_EVENT_GFX_KOGA_1,
    OBJ_EVENT_GFX_LADY_1,
    OBJ_EVENT_GFX_LADY_2,
    OBJ_EVENT_GFX_LANCE_1,
    OBJ_EVENT_GFX_LASS_1,
    OBJ_EVENT_GFX_LASS_2,
    OBJ_EVENT_GFX_LASS_3,
    OBJ_EVENT_GFX_LEAF_1,
    OBJ_EVENT_GFX_LEON,
    OBJ_EVENT_GFX_LEONORA,
    OBJ_EVENT_GFX_LINEBACKER,
    OBJ_EVENT_GFX_LIZA_1,
    OBJ_EVENT_GFX_LORELAI_1,
    OBJ_EVENT_GFX_LORETTA,
    OBJ_EVENT_GFX_LT_SURGE_1,
    OBJ_EVENT_GFX_LUCIAN,
    OBJ_EVENT_GFX_LYRA,
    OBJ_EVENT_GFX_MAID_1,
    OBJ_EVENT_GFX_MAID_2,
    OBJ_EVENT_GFX_MAN_6,
    OBJ_EVENT_GFX_MAN_7,
    OBJ_EVENT_GFX_MAN_8,
    OBJ_EVENT_GFX_MARLIN_SWIM,
    OBJ_EVENT_GFX_MARLIN,
    OBJ_EVENT_GFX_MARNIE,
    OBJ_EVENT_GFX_MARSHALL,
    OBJ_EVENT_GFX_MAYLENE,
    OBJ_EVENT_GFX_MEDAL_GUY,
    OBJ_EVENT_GFX_MEDIUM,
    OBJ_EVENT_GFX_MISTY_1,
    OBJ_EVENT_GFX_MORTY,
    OBJ_EVENT_GFX_N,
    OBJ_EVENT_GFX_NEMONA,
    OBJ_EVENT_GFX_NEO_GHETHIS_CANE,
    OBJ_EVENT_GFX_NEO_GHETHIS,
    OBJ_EVENT_GFX_NEO_PLASMA_F,
    OBJ_EVENT_GFX_NEO_PLASMA_M,
    OBJ_EVENT_GFX_NEO_ZINZOLIN,
    OBJ_EVENT_GFX_NESSA,
    OBJ_EVENT_GFX_NINJA_BOY_1,
    OBJ_EVENT_GFX_NORMAN_1,
    OBJ_EVENT_GFX_NURSE_1,
    OBJ_EVENT_GFX_NURSE_JOY,
    OBJ_EVENT_GFX_NURSE_JOY_WALK,
    OBJ_EVENT_GFX_NURSERY_AIDE,
    OBJ_EVENT_GFX_OAK,
    OBJ_EVENT_GFX_OLD_WOMAN_1,
    OBJ_EVENT_GFX_OTNAR,
    OBJ_EVENT_GFX_PARASOL_LADY_1,
    OBJ_EVENT_GFX_PARASOL_LADY_2,
    OBJ_EVENT_GFX_PERRIN,
    OBJ_EVENT_GFX_PETER,
    OBJ_EVENT_GFX_PICNICKER_1,
    OBJ_EVENT_GFX_PIERS,
    OBJ_EVENT_GFX_PILOT,
    OBJ_EVENT_GFX_POKEFAN_F_1,
    OBJ_EVENT_GFX_POKEFAN_F_2,
    OBJ_EVENT_GFX_POKEFAN_M_1,
    OBJ_EVENT_GFX_POKEFAN_M_2,
    OBJ_EVENT_GFX_POKEKID,
    OBJ_EVENT_GFX_POKEMANIAC,
    OBJ_EVENT_GFX_POKEMART,
    OBJ_EVENT_GFX_POLICEMAN_1,
    OBJ_EVENT_GFX_POLICEMAN_2,
    OBJ_EVENT_GFX_POSTMAN,
    OBJ_EVENT_GFX_PRESCHOOLER_F,
    OBJ_EVENT_GFX_PRESCHOOLER_M,
    OBJ_EVENT_GFX_PROF_UNICORN,
    OBJ_EVENT_GFX_PRYCE,
    OBJ_EVENT_GFX_PSYCHIC_F_1,
    OBJ_EVENT_GFX_PSYCHIC_F_2,
    OBJ_EVENT_GFX_PSYCHIC_M_1,
    OBJ_EVENT_GFX_PSYCHIC_M_2,
    OBJ_EVENT_GFX_PUNK_GUY,
    OBJ_EVENT_GFX_RANCHER,
    OBJ_EVENT_GFX_RANGER_F_1,
    OBJ_EVENT_GFX_RANGER_F_2,
    OBJ_EVENT_GFX_RANGER_M_1,
    OBJ_EVENT_GFX_RANGER_M_2,
    OBJ_EVENT_GFX_RECEPTIONIST_1,
    OBJ_EVENT_GFX_RECEPTIONIST_2,
    OBJ_EVENT_GFX_RECEPTIONIST_3,
    OBJ_EVENT_GFX_RECEPTIONIST_4,
    OBJ_EVENT_GFX_REPORTER,
    OBJ_EVENT_GFX_RICH_BOY_1,
    OBJ_EVENT_GFX_RICH_BOY_2,
    OBJ_EVENT_GFX_RICH_MAN,
    OBJ_EVENT_GFX_ROARK,
    OBJ_EVENT_GFX_ROUGHNECK_1,
    OBJ_EVENT_GFX_ROUGHNECK_2,
    OBJ_EVENT_GFX_ROUGHNECK_2_FIGHT,
    OBJ_EVENT_GFX_ROXANNE_1,
    OBJ_EVENT_GFX_ROXIE,
    OBJ_EVENT_GFX_ROXIE_GUITAR,
    OBJ_EVENT_GFX_RUIN_MANIAC,
    OBJ_EVENT_GFX_RYME,
    OBJ_EVENT_GFX_SABRINA_1,
    OBJ_EVENT_GFX_SAGE_BRONIUS,
    OBJ_EVENT_GFX_SAGE_GIALLO,
    OBJ_EVENT_GFX_SAGE_GORM,
    OBJ_EVENT_GFX_SAGE_ROOD,
    OBJ_EVENT_GFX_SAGE_RYOKU,
    OBJ_EVENT_GFX_SAGE,
    OBJ_EVENT_GFX_SAILOR_1,
    OBJ_EVENT_GFX_SCHOOLKID_F,
    OBJ_EVENT_GFX_SCHOOLKID_M_1,
    OBJ_EVENT_GFX_SCIENTIST_F,
    OBJ_EVENT_GFX_SCIENTIST_M_1,
    OBJ_EVENT_GFX_SCIENTIST_M_2,
    OBJ_EVENT_GFX_SCIENTIST_M_3,
    OBJ_EVENT_GFX_SEAN,
    OBJ_EVENT_GFX_SERENA,
    OBJ_EVENT_GFX_SHADOW_TRIAD,
    OBJ_EVENT_GFX_SHADY_GUY,
    OBJ_EVENT_GFX_SHAUNTAL,
    OBJ_EVENT_GFX_SIDNEY_1,
    OBJ_EVENT_GFX_SINGER,
    OBJ_EVENT_GFX_SKIER_F_1,
    OBJ_EVENT_GFX_SKIER_F_2,
    OBJ_EVENT_GFX_SKIER_M,
    OBJ_EVENT_GFX_SKYLA,
    OBJ_EVENT_GFX_SMASHER,
    OBJ_EVENT_GFX_SOCIALITE_1,
    OBJ_EVENT_GFX_SOCIALITE_2,
    OBJ_EVENT_GFX_STRIKER,
    OBJ_EVENT_GFX_SUPERNERD,
    OBJ_EVENT_GFX_SWIMMER_F_1,
    OBJ_EVENT_GFX_SWIMMER_F_2,
    OBJ_EVENT_GFX_SWIMMER_F_3,
    OBJ_EVENT_GFX_SWIMMER_M_1,
    OBJ_EVENT_GFX_SWIMMER_M_2,
    OBJ_EVENT_GFX_SWIMMER_M_3,
    OBJ_EVENT_GFX_TATE_1,
    OBJ_EVENT_GFX_TEACHER,
    OBJ_EVENT_GFX_TEAM_PLASMA_F,
    OBJ_EVENT_GFX_TEAM_PLASMA_M,
    OBJ_EVENT_GFX_TOXIANNA,
    OBJ_EVENT_GFX_TRUMPETER,
    OBJ_EVENT_GFX_TUBER_F_1,
    OBJ_EVENT_GFX_TUBER_M_1,
    OBJ_EVENT_GFX_TWINS_1,
    OBJ_EVENT_GFX_TWINS_2,
    OBJ_EVENT_GFX_TWINS_3,
    OBJ_EVENT_GFX_ULTIMA,
    OBJ_EVENT_GFX_VETRAN_F,
    OBJ_EVENT_GFX_VETRAN_M_1,
    OBJ_EVENT_GFX_VETRAN_M_2,
    OBJ_EVENT_GFX_VICTOR,
    OBJ_EVENT_GFX_VIOLA,
    OBJ_EVENT_GFX_VOLKNER,
    OBJ_EVENT_GFX_WAITER_1,
    OBJ_EVENT_GFX_WAITER_2,
    OBJ_EVENT_GFX_WAITRESS_1,
    OBJ_EVENT_GFX_WAITRESS_2,
    OBJ_EVENT_GFX_WALLACE_1,
    OBJ_EVENT_GFX_WATTSON_1,
    OBJ_EVENT_GFX_WHITNEY,
    OBJ_EVENT_GFX_WILL,
    OBJ_EVENT_GFX_WINONA_1,
    OBJ_EVENT_GFX_WOMAN_6,
    OBJ_EVENT_GFX_WOMAN_7,
    OBJ_EVENT_GFX_WOMAN_8,
    OBJ_EVENT_GFX_WOMAN_9,
    OBJ_EVENT_GFX_WOMAN_10,
    OBJ_EVENT_GFX_WOMAN_11,
    OBJ_EVENT_GFX_WORKER_1,
    OBJ_EVENT_GFX_WORKER_2,
    OBJ_EVENT_GFX_WORKER_3,
    OBJ_EVENT_GFX_YANCY_1,
    OBJ_EVENT_GFX_YANCY_2,
    OBJ_EVENT_GFX_YOUNGSTER_1,
    OBJ_EVENT_GFX_YOUNGSTER_2,
    OBJ_EVENT_GFX_YOUNGSTER_3,
    OBJ_EVENT_GFX_LUCAS_NORMAL,
    OBJ_EVENT_GFX_LUCAS_MACH_BIKE,
    OBJ_EVENT_GFX_LUCAS_ACRO_BIKE,
    OBJ_EVENT_GFX_LUCAS_SURFING,
    OBJ_EVENT_GFX_LUCAS_FIELD_MOVE,
    OBJ_EVENT_GFX_BRENDAN_FISHING,
    OBJ_EVENT_GFX_BRENDAN_WATERING,
    OBJ_EVENT_GFX_LUCAS_DECORATING,
    OBJ_EVENT_GFX_BRENDAN_UNDERWATER,
    OBJ_EVENT_GFX_LUCAS_VS_SEEKER,
    OBJ_EVENT_GFX_LUCAS_VS_SEEKER_BIKE,
    OBJ_EVENT_GFX_DAWN_NORMAL,
    OBJ_EVENT_GFX_DAWN_MACH_BIKE,
    OBJ_EVENT_GFX_DAWN_ACRO_BIKE,
    OBJ_EVENT_GFX_DAWN_SURFING,
    OBJ_EVENT_GFX_DAWN_FIELD_MOVE,
    OBJ_EVENT_GFX_MAY_FISHING,
    OBJ_EVENT_GFX_MAY_WATERING,
    OBJ_EVENT_GFX_DAWN_DECORATING,
    OBJ_EVENT_GFX_MAY_UNDERWATER,
    OBJ_EVENT_GFX_DAWN_VS_SEEKER,
    OBJ_EVENT_GFX_DAWN_VS_SEEKER_BIKE,
    OBJ_EVENT_GFX_RIVAL_BRENDAN_NORMAL,
    OBJ_EVENT_GFX_RIVAL_BRENDAN_MACH_BIKE,
    OBJ_EVENT_GFX_RIVAL_BRENDAN_ACRO_BIKE,
    OBJ_EVENT_GFX_RIVAL_BRENDAN_SURFING,
    OBJ_EVENT_GFX_RIVAL_BRENDAN_FIELD_MOVE,
    OBJ_EVENT_GFX_RIVAL_MAY_NORMAL,
    OBJ_EVENT_GFX_RIVAL_MAY_MACH_BIKE,
    OBJ_EVENT_GFX_RIVAL_MAY_ACRO_BIKE,
    OBJ_EVENT_GFX_RIVAL_MAY_SURFING,
    OBJ_EVENT_GFX_RIVAL_MAY_FIELD_MOVE,
    OBJ_EVENT_GFX_LINK_BRENDAN,
    OBJ_EVENT_GFX_LINK_MAY,
    OBJ_EVENT_GFX_PUSHABLE_BOULDER_FRLG,
    OBJ_EVENT_GFX_CUTTABLE_TREE_FRLG,
    OBJ_EVENT_GFX_BREAKABLE_ROCK_FRLG,
    NUM_OBJ_EVENT_GFX,
};

// FRLG equivalents
// #define OBJ_EVENT_GFX_MEW OBJ_EVENT_GFX_NINJA_BOY
// #define OBJ_EVENT_GFX_LUGIA OBJ_EVENT_GFX_NINJA_BOY

// NOTE: The maximum amount of object events has been expanded from 255 to 65535.
// Since dynamic graphics ids still require at least 16 free values, the actual limit
// is 65519, but even considering follower Pokémon, this should be more than enough :)


// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define OBJ_EVENT_GFX_VARS   (NUM_OBJ_EVENT_GFX + 1)
#define OBJ_EVENT_GFX_VAR_0  (OBJ_EVENT_GFX_VARS + 0x0)
#define OBJ_EVENT_GFX_VAR_1  (OBJ_EVENT_GFX_VARS + 0x1)
#define OBJ_EVENT_GFX_VAR_2  (OBJ_EVENT_GFX_VARS + 0x2)
#define OBJ_EVENT_GFX_VAR_3  (OBJ_EVENT_GFX_VARS + 0x3)
#define OBJ_EVENT_GFX_VAR_4  (OBJ_EVENT_GFX_VARS + 0x4)
#define OBJ_EVENT_GFX_VAR_5  (OBJ_EVENT_GFX_VARS + 0x5)
#define OBJ_EVENT_GFX_VAR_6  (OBJ_EVENT_GFX_VARS + 0x6)
#define OBJ_EVENT_GFX_VAR_7  (OBJ_EVENT_GFX_VARS + 0x7)
#define OBJ_EVENT_GFX_VAR_8  (OBJ_EVENT_GFX_VARS + 0x8)
#define OBJ_EVENT_GFX_VAR_9  (OBJ_EVENT_GFX_VARS + 0x9)
#define OBJ_EVENT_GFX_VAR_A  (OBJ_EVENT_GFX_VARS + 0xA)
#define OBJ_EVENT_GFX_VAR_B  (OBJ_EVENT_GFX_VARS + 0xB)
#define OBJ_EVENT_GFX_VAR_C  (OBJ_EVENT_GFX_VARS + 0xC)
#define OBJ_EVENT_GFX_VAR_D  (OBJ_EVENT_GFX_VARS + 0xD)
#define OBJ_EVENT_GFX_VAR_E  (OBJ_EVENT_GFX_VARS + 0xE)
#define OBJ_EVENT_GFX_VAR_F  (OBJ_EVENT_GFX_VARS + 0xF)

// Don't use (1u << 15) to avoid conflict with BLEND_IMMUNE_FLAG.
#define OBJ_EVENT_MON               (1u << 14)
#define OBJ_EVENT_MON_SHINY         (1u << 13)
#define OBJ_EVENT_MON_FEMALE        (1u << 12)
#define OBJ_EVENT_MON_SPECIES_MASK  (~(7u << 12))

// Used to call a specific species' follower graphics. Useful for static encounters.
#define OBJ_EVENT_GFX_SPECIES(name)                 (SPECIES_##name + OBJ_EVENT_MON)
#define OBJ_EVENT_GFX_SPECIES_SHINY(name)           (SPECIES_##name + OBJ_EVENT_MON + OBJ_EVENT_MON_SHINY)
#define OBJ_EVENT_GFX_SPECIES_FEMALE(name)          (SPECIES_##name + OBJ_EVENT_MON + OBJ_EVENT_MON_FEMALE)
#define OBJ_EVENT_GFX_SPECIES_SHINY_FEMALE(name)    (SPECIES_##name + OBJ_EVENT_MON + OBJ_EVENT_MON_SHINY + OBJ_EVENT_MON_FEMALE)

#define OW_SPECIES(x) ((x)->graphicsId & OBJ_EVENT_MON_SPECIES_MASK)
#define OW_SHINY(x) ((x)->graphicsId & OBJ_EVENT_MON_SHINY)
#define OW_FEMALE(x) ((x)->graphicsId & OBJ_EVENT_MON_FEMALE)

// Whether Object Event is an OW Pokémon
#define IS_OW_MON_OBJ(obj) ((obj)->graphicsId & OBJ_EVENT_MON)

#define SHADOW_SIZE_S       0
#define SHADOW_SIZE_M       1
#define SHADOW_SIZE_L       2
#define SHADOW_SIZE_NONE    3   // Originally SHADOW_SIZE_XL, which went unused due to shadowSize in ObjectEventGraphicsInfo being only 2 bits.

#define SHADOW_SIZE_XL_BATTLE_ONLY  SHADOW_SIZE_NONE    // Battle-only definition for XL shadow size.

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2
#define TRACKS_SLITHER    3
#define TRACKS_SPOT       4
#define TRACKS_BUG        5

#define LIGHT_TYPE_BALL             0
#define LIGHT_TYPE_PKMN_CENTER_SIGN 1
#define LIGHT_TYPE_POKE_MART_SIGN   2

#define FIRST_DECORATION_SPRITE_GFX OBJ_EVENT_GFX_PICHU_DOLL

#define OBJ_KIND_NORMAL 0
#define OBJ_KIND_CLONE  255 // Exclusive to FRLG


// Each object event template gets an ID that can be used to refer to it in scripts and elsewhere.
// This is referred to as the "local id" (and it's really just 1 + its index in the templates array).
// There are a few special IDs reserved for objects that don't have templates in the map data -- one for the player
// in regular offline play, five for linked players while playing Berry Blender, and one for an invisible object that
// can be spawned for the camera to track instead of the player. Additionally, the value 0 is reserved as an "empty" indicator.
#define LOCALID_NONE                              0
#define LOCALID_CAMERA                          127
#define LOCALID_BERRY_BLENDER_PLAYER_END        240 // This will use 5 (MAX_RFU_PLAYERS) IDs ending at 240, i.e. 236-240
#define LOCALID_OW_ENCOUNTER_END                252 // This will use 4 (OWE_SPAWNS_MAX) IDs ending at 252, i.e. 249-252
#define LOCALID_FOLLOWING_POKEMON               254
#define LOCALID_PLAYER                          255
#define OBJ_EVENT_ID_FOLLOWER                   0xFE
#define OBJ_EVENT_ID_NPC_FOLLOWER               0xFD

#define IS_LOCALID_GENERATED_OWE(localId)       (localId <= LOCALID_OW_ENCOUNTER_END \
                                                 && localId > (LOCALID_OW_ENCOUNTER_END - OWE_SPAWNS_MAX))

// Aliases for old names. "object event id" normally refers to an index into gObjectEvents, which these are not.
// Used for link player OWs in CreateLinkPlayerSprite
#define OBJ_EVENT_ID_CAMERA LOCALID_CAMERA
#define OBJ_EVENT_ID_PLAYER LOCALID_PLAYER
#define OBJ_EVENT_ID_DYNAMIC_BASE 0xF0

// Moved from src/event_object_movement.c so that they're accesible from other files.
#define OBJ_EVENT_PAL_TAG_BRENDAN                 0x1100
#define OBJ_EVENT_PAL_TAG_BRENDAN_REFLECTION      0x1101
#define OBJ_EVENT_PAL_TAG_BRIDGE_REFLECTION       0x1102
#define OBJ_EVENT_PAL_TAG_NPC_1                   0x1103
#define OBJ_EVENT_PAL_TAG_NPC_2                   0x1104
#define OBJ_EVENT_PAL_TAG_NPC_3                   0x1105
#define OBJ_EVENT_PAL_TAG_NPC_4                   0x1106
#define OBJ_EVENT_PAL_TAG_NPC_5                   0x1107
#define OBJ_EVENT_PAL_TAG_NPC_6                   0x1108
#define OBJ_EVENT_PAL_TAG_NPC_7                   0x1109
#define OBJ_EVENT_PAL_TAG_NPC_8                   0x110A
#define OBJ_EVENT_PAL_TAG_QUINTY_PLUMP            0x110B
#define OBJ_EVENT_PAL_TAG_QUINTY_PLUMP_REFLECTION 0x110C
#define OBJ_EVENT_PAL_TAG_TRUCK                   0x110D
#define OBJ_EVENT_PAL_TAG_VIGOROTH                0x110E
#define OBJ_EVENT_PAL_TAG_ZIGZAGOON               0x110F
#define OBJ_EVENT_PAL_TAG_MAY                     0x1110
#define OBJ_EVENT_PAL_TAG_MAY_REFLECTION          0x1111
#define OBJ_EVENT_PAL_TAG_MOVING_BOX              0x1112
#define OBJ_EVENT_PAL_TAG_CABLE_CAR               0x1113
#define OBJ_EVENT_PAL_TAG_SSTIDAL                 0x1114
#define OBJ_EVENT_PAL_TAG_PLAYER_UNDERWATER       0x1115
#define OBJ_EVENT_PAL_TAG_KYOGRE                  0x1116
#define OBJ_EVENT_PAL_TAG_KYOGRE_REFLECTION       0x1117
#define OBJ_EVENT_PAL_TAG_GROUDON                 0x1118
#define OBJ_EVENT_PAL_TAG_GROUDON_REFLECTION      0x1119
#define OBJ_EVENT_PAL_TAG_UNUSED                  0x111A
#define OBJ_EVENT_PAL_TAG_SUBMARINE_SHADOW        0x111B
#define OBJ_EVENT_PAL_TAG_POOCHYENA               0x111C
#define OBJ_EVENT_PAL_TAG_RED_LEAF                0x111D
#define OBJ_EVENT_PAL_TAG_DEOXYS                  0x111E
#define OBJ_EVENT_PAL_TAG_BIRTH_ISLAND_STONE      0x111F
#define OBJ_EVENT_PAL_TAG_HO_OH                   0x1120
#define OBJ_EVENT_PAL_TAG_LUGIA                   0x1121
#define OBJ_EVENT_PAL_TAG_RS_BRENDAN              0x1122
#define OBJ_EVENT_PAL_TAG_RS_MAY                  0x1123
#define OBJ_EVENT_PAL_TAG_DYNAMIC                 0x1124
#define OBJ_EVENT_PAL_TAG_PLAYER_RED              0x1125
#define OBJ_EVENT_PAL_TAG_PLAYER_RED_REFLECTION   0x1126
#define OBJ_EVENT_PAL_TAG_PLAYER_GREEN            0x1127
#define OBJ_EVENT_PAL_TAG_PLAYER_GREEN_REFLECTION 0x1128
#define OBJ_EVENT_PAL_TAG_NPC_BLUE                0x1129
#define OBJ_EVENT_PAL_TAG_NPC_PINK                0x112A
#define OBJ_EVENT_PAL_TAG_NPC_GREEN               0x112B
#define OBJ_EVENT_PAL_TAG_NPC_WHITE               0x112C
#define OBJ_EVENT_PAL_TAG_NPC_BLUE_REFLECTION     0x112D
#define OBJ_EVENT_PAL_TAG_NPC_PINK_REFLECTION     0x112E
#define OBJ_EVENT_PAL_TAG_NPC_GREEN_REFLECTION    0x112F
#define OBJ_EVENT_PAL_TAG_NPC_WHITE_REFLECTION    0x1130
#define OBJ_EVENT_PAL_TAG_METEORITE               0x1131
#define OBJ_EVENT_PAL_TAG_SEAGALLOP               0x1132
#define OBJ_EVENT_PAL_TAG_SS_ANNE                 0x1133
#define OBJ_EVENT_PAL_TAG_DAWN                    0x1134
#define OBJ_EVENT_PAL_TAG_LUCAS                   0x1135
#define OBJ_EVENT_PAL_TAG_DAWN_LUCAS_UNDERWATER   0x1136
#define OBJ_EVENT_PAL_TAG_ADHIRA                  0x1137
#define OBJ_EVENT_PAL_TAG_AHAB                    0x1138
#define OBJ_EVENT_PAL_TAG_CARLY                   0x1139
#define OBJ_EVENT_PAL_TAG_ISRAEL                  0x1140
#define OBJ_EVENT_PAL_TAG_JELISSA                 0x1141
#define OBJ_EVENT_PAL_TAG_JOSH                    0x1142
#define OBJ_EVENT_PAL_TAG_OTNAR                   0x1143
#define OBJ_EVENT_PAL_TAG_PETER                   0x1144
#define OBJ_EVENT_PAL_TAG_TOXIANNA                0x1145
#define OBJ_EVENT_PAL_TAG_AMELIA                  0x1146
#define OBJ_EVENT_PAL_TAG_AUDREY                  0x1147
#define OBJ_EVENT_PAL_TAG_BELLIS                  0x1148
#define OBJ_EVENT_PAL_TAG_CARTER                  0x1149
#define OBJ_EVENT_PAL_TAG_HOBIE                   0x1150
#define OBJ_EVENT_PAL_TAG_JUNKO                   0x1151
#define OBJ_EVENT_PAL_TAG_LORETTA                 0x1152
#define OBJ_EVENT_PAL_TAG_PROF_UNICORN            0x1153
#define OBJ_EVENT_PAL_TAG_SEAN                    0x1154

#if OW_FOLLOWERS_POKEBALLS
// Vanilla
#define OBJ_EVENT_PAL_TAG_BALL_MASTER             0x1150
#define OBJ_EVENT_PAL_TAG_BALL_ULTRA              0x1151
#define OBJ_EVENT_PAL_TAG_BALL_GREAT              0x1152
#define OBJ_EVENT_PAL_TAG_BALL_SAFARI             0x1153
#define OBJ_EVENT_PAL_TAG_BALL_NET                0x1154
#define OBJ_EVENT_PAL_TAG_BALL_DIVE               0x1155
#define OBJ_EVENT_PAL_TAG_BALL_NEST               0x1156
#define OBJ_EVENT_PAL_TAG_BALL_REPEAT             0x1157
#define OBJ_EVENT_PAL_TAG_BALL_TIMER              0x1158
#define OBJ_EVENT_PAL_TAG_BALL_LUXURY             0x1159
#define OBJ_EVENT_PAL_TAG_BALL_PREMIER            0x115A
// Gen IV/Sinnoh
#define OBJ_EVENT_PAL_TAG_BALL_DUSK               0x115B
#define OBJ_EVENT_PAL_TAG_BALL_HEAL               0x115C
#define OBJ_EVENT_PAL_TAG_BALL_QUICK              0x115D
#define OBJ_EVENT_PAL_TAG_BALL_CHERISH            0x115E
#define OBJ_EVENT_PAL_TAG_BALL_PARK               0x115F
// Gen II/Johto Apricorns
#define OBJ_EVENT_PAL_TAG_BALL_FAST               0x1160
#define OBJ_EVENT_PAL_TAG_BALL_LEVEL              0x1161
#define OBJ_EVENT_PAL_TAG_BALL_LURE               0x1162
#define OBJ_EVENT_PAL_TAG_BALL_HEAVY              0x1163
#define OBJ_EVENT_PAL_TAG_BALL_LOVE               0x1164
#define OBJ_EVENT_PAL_TAG_BALL_FRIEND             0x1165
#define OBJ_EVENT_PAL_TAG_BALL_MOON               0x1166
#define OBJ_EVENT_PAL_TAG_BALL_SPORT              0x1167
// Gen V
#define OBJ_EVENT_PAL_TAG_BALL_DREAM              0x1168
// Gen VII
#define OBJ_EVENT_PAL_TAG_BALL_BEAST              0x1169
// Gen VIII
#define OBJ_EVENT_PAL_TAG_BALL_STRANGE            0x116A
#endif //OW_FOLLOWERS_POKEBALLS
// Used as a placeholder follower graphic
#define OBJ_EVENT_PAL_TAG_SUBSTITUTE              0x7611
#define OBJ_EVENT_PAL_TAG_LIGHT                   0x8001
#define OBJ_EVENT_PAL_TAG_LIGHT_2                 0x8002
#define OBJ_EVENT_PAL_TAG_EMOTES                  0x8003
#define OBJ_EVENT_PAL_TAG_NEON_LIGHT              0x8004
// Not a real OW palette tag; used for the white flash applied to followers
#define OBJ_EVENT_PAL_TAG_WHITE                   (OBJ_EVENT_PAL_TAG_NONE - 1)
#define OBJ_EVENT_PAL_TAG_NONE                    0x11FF

// This + localId is used as the tileTag
// for compressed graphicsInfos
// '(C)ompressed (E)vent'
#define COMP_OW_TILE_TAG_BASE 0xCE00

#endif  // GUARD_CONSTANTS_EVENT_OBJECTS_H
