#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#include "metaprogram.h"
#include "constants/tms_hms.h"

enum __attribute__((packed)) Item
{
    ITEM_NONE = 0,

    // Poké Balls
    ITEM_POKE_BALL = 1,
    ITEM_GREAT_BALL = 2,
    ITEM_ULTRA_BALL = 3,
    ITEM_MASTER_BALL = 4,
    ITEM_PREMIER_BALL = 5,
    ITEM_HEAL_BALL = 6,
    ITEM_NET_BALL = 7,
    ITEM_NEST_BALL = 8,
    ITEM_DIVE_BALL = 9,
    ITEM_DUSK_BALL = 10,
    ITEM_TIMER_BALL = 11,
    ITEM_QUICK_BALL = 12,
    ITEM_REPEAT_BALL = 13,
    ITEM_LUXURY_BALL = 14,
    ITEM_LEVEL_BALL = 15,
    ITEM_LURE_BALL = 16,
    ITEM_MOON_BALL = 17,
    ITEM_FRIEND_BALL = 18,
    ITEM_LOVE_BALL = 19,
    ITEM_FAST_BALL = 20,
    ITEM_HEAVY_BALL = 21,
    ITEM_DREAM_BALL = 22,
    ITEM_SAFARI_BALL = 23,
    ITEM_SPORT_BALL = 24,
    ITEM_PARK_BALL = 25,
    ITEM_BEAST_BALL = 26,
    ITEM_CHERISH_BALL = 27,

    // Medicine
    ITEM_POTION = 28,
    ITEM_SUPER_POTION = 29,
    ITEM_HYPER_POTION = 30,
    ITEM_MAX_POTION = 31,
    ITEM_FULL_RESTORE = 32,
    ITEM_REVIVE = 33,
    ITEM_MAX_REVIVE = 34,
    ITEM_FRESH_WATER = 35,
    ITEM_SODA_POP = 36,
    ITEM_LEMONADE = 37,
    ITEM_MOOMOO_MILK = 38,
    ITEM_ENERGY_POWDER = 39,
    ITEM_ENERGYPOWDER = ITEM_ENERGY_POWDER, // Pre-Gen VI name
    ITEM_ENERGY_ROOT = 40,
    ITEM_HEAL_POWDER = 41,
    ITEM_REVIVAL_HERB = 42,
    ITEM_ANTIDOTE = 43,
    ITEM_PARALYZE_HEAL = 44,
    ITEM_PARLYZ_HEAL = ITEM_PARALYZE_HEAL, // Pre-Gen VI name
    ITEM_BURN_HEAL = 45,
    ITEM_ICE_HEAL = 46,
    ITEM_AWAKENING = 47,
    ITEM_FULL_HEAL = 48,
    ITEM_ETHER = 49,
    ITEM_MAX_ETHER = 50,
    ITEM_ELIXIR = 51,
    ITEM_ELIXER = ITEM_ELIXIR, // Pre-Gen III name
    ITEM_MAX_ELIXIR = 52,
    ITEM_MAX_ELIXER = ITEM_MAX_ELIXIR, // Pre-Gen III name
    ITEM_BERRY_JUICE = 53,
    ITEM_SACRED_ASH = 54,
    ITEM_SWEET_HEART = 55,
    ITEM_MAX_HONEY = 56,

    // Regional Specialties
    ITEM_PEWTER_CRUNCHIES = 57,
    ITEM_RAGE_CANDY_BAR = 58,
    ITEM_RAGECANDYBAR = ITEM_RAGE_CANDY_BAR, // Pre-Gen VI name
    ITEM_LAVA_COOKIE = 59,
    ITEM_OLD_GATEAU = 60,
    ITEM_CASTELIACONE = 61,
    ITEM_LUMIOSE_GALETTE = 62,
    ITEM_SHALOUR_SABLE = 63,
    ITEM_BIG_MALASADA = 64,

    // Vitamins
    ITEM_HP_UP = 65,
    ITEM_PROTEIN = 66,
    ITEM_IRON = 67,
    ITEM_CALCIUM = 68,
    ITEM_ZINC = 69,
    ITEM_CARBOS = 70,
    ITEM_PP_UP = 71,
    ITEM_PP_MAX = 72,

    // EV Feathers
    ITEM_HEALTH_FEATHER = 73,
    ITEM_HEALTH_WING = ITEM_HEALTH_FEATHER, // Pre-Gen VIII name
    ITEM_MUSCLE_FEATHER = 74,
    ITEM_MUSCLE_WING = ITEM_MUSCLE_FEATHER, // Pre-Gen VIII name
    ITEM_RESIST_FEATHER = 75,
    ITEM_RESIST_WING = ITEM_RESIST_FEATHER, // Pre-Gen VIII name
    ITEM_GENIUS_FEATHER = 76,
    ITEM_GENIUS_WING = ITEM_GENIUS_FEATHER, // Pre-Gen VIII name
    ITEM_CLEVER_FEATHER = 77,
    ITEM_CLEVER_WING = ITEM_CLEVER_FEATHER, // Pre-Gen VIII name
    ITEM_SWIFT_FEATHER = 78,
    ITEM_SWIFT_WING = ITEM_SWIFT_FEATHER, // Pre-Gen VIII name

    // Ability Modifiers
    ITEM_ABILITY_CAPSULE = 79,
    ITEM_ABILITY_PATCH = 80,

    // Mints
    ITEM_LONELY_MINT = 81,
    ITEM_ADAMANT_MINT = 82,
    ITEM_NAUGHTY_MINT = 83,
    ITEM_BRAVE_MINT = 84,
    ITEM_BOLD_MINT = 85,
    ITEM_IMPISH_MINT = 86,
    ITEM_LAX_MINT = 87,
    ITEM_RELAXED_MINT = 88,
    ITEM_MODEST_MINT = 89,
    ITEM_MILD_MINT = 90,
    ITEM_RASH_MINT = 91,
    ITEM_QUIET_MINT = 92,
    ITEM_CALM_MINT = 93,
    ITEM_GENTLE_MINT = 94,
    ITEM_CAREFUL_MINT = 95,
    ITEM_SASSY_MINT = 96,
    ITEM_TIMID_MINT = 97,
    ITEM_HASTY_MINT = 98,
    ITEM_JOLLY_MINT = 99,
    ITEM_NAIVE_MINT = 100,
    ITEM_SERIOUS_MINT = 101,

    // Candy
    ITEM_RARE_CANDY = 102,
    ITEM_EXP_CANDY_XS = 103,
    ITEM_EXP_CANDY_S = 104,
    ITEM_EXP_CANDY_M = 105,
    ITEM_EXP_CANDY_L = 106,
    ITEM_EXP_CANDY_XL = 107,
    ITEM_DYNAMAX_CANDY = 108,

    // Medicinal Flutes
    ITEM_BLUE_FLUTE = 109,
    ITEM_YELLOW_FLUTE = 110,
    ITEM_RED_FLUTE = 111,

    // Encounter-modifying Flutes
    ITEM_BLACK_FLUTE = 112,
    ITEM_WHITE_FLUTE = 113,

    // Encounter Modifiers
    ITEM_REPEL = 114,
    ITEM_SUPER_REPEL = 115,
    ITEM_MAX_REPEL = 116,
    ITEM_LURE = 117,
    ITEM_SUPER_LURE = 118,
    ITEM_MAX_LURE = 119,

    ITEM_ESCAPE_ROPE = 120,

    // X Items
    ITEM_X_ATTACK = 121,
    ITEM_X_DEFENSE = 122,
    ITEM_X_DEFEND = ITEM_X_DEFENSE, // Pre-Gen VI name
    ITEM_X_SP_ATK = 123,
    ITEM_X_SPECIAL = ITEM_X_SP_ATK, // Pre-Gen VI name
    ITEM_X_SP_DEF = 124,
    ITEM_X_SPEED = 125,
    ITEM_X_ACCURACY = 126,

    ITEM_DIRE_HIT = 127,
    ITEM_GUARD_SPEC = 128,

    // Escape Items
    ITEM_POKE_DOLL = 129,
    ITEM_FLUFFY_TAIL = 130,
    ITEM_POKE_TOY = 131,

    ITEM_MAX_MUSHROOMS = 132,

    // Treasures
    ITEM_BOTTLE_CAP = 133,
    ITEM_GOLD_BOTTLE_CAP = 134,
    ITEM_NUGGET = 135,
    ITEM_BIG_NUGGET = 136,
    ITEM_TINY_MUSHROOM = 137,
    ITEM_TINYMUSHROOM = ITEM_TINY_MUSHROOM, // Pre-Gen VI name
    ITEM_BIG_MUSHROOM = 138,
    ITEM_BALM_MUSHROOM = 139,
    ITEM_BALMMUSHROOM = ITEM_BALM_MUSHROOM, // Pre-Gen VI name
    ITEM_PEARL = 140,
    ITEM_BIG_PEARL = 141,
    ITEM_PEARL_STRING = 142,
    ITEM_STARDUST = 143,
    ITEM_STAR_PIECE = 144,
    ITEM_COMET_SHARD = 145,
    ITEM_SHOAL_SALT = 146,
    ITEM_SHOAL_SHELL = 147,
    ITEM_RED_SHARD = 148,
    ITEM_BLUE_SHARD = 149,
    ITEM_YELLOW_SHARD = 150,
    ITEM_GREEN_SHARD = 151,
    ITEM_HEART_SCALE = 152,
    ITEM_HONEY = 153,
    ITEM_RARE_BONE = 154,
    ITEM_ODD_KEYSTONE = 155,
    ITEM_PRETTY_FEATHER = 156,
    ITEM_PRETTY_WING = ITEM_PRETTY_FEATHER, // Pre-Gen VIII name
    ITEM_RELIC_COPPER = 157,
    ITEM_RELIC_SILVER = 158,
    ITEM_RELIC_GOLD = 159,
    ITEM_RELIC_VASE = 160,
    ITEM_RELIC_BAND = 161,
    ITEM_RELIC_STATUE = 162,
    ITEM_RELIC_CROWN = 163,
    ITEM_STRANGE_SOUVENIR = 164,

    // Fossils
    ITEM_HELIX_FOSSIL = 165,
    ITEM_DOME_FOSSIL = 166,
    ITEM_OLD_AMBER = 167,
    ITEM_ROOT_FOSSIL = 168,
    ITEM_CLAW_FOSSIL = 169,
    ITEM_ARMOR_FOSSIL = 170,
    ITEM_SKULL_FOSSIL = 171,
    ITEM_COVER_FOSSIL = 172,
    ITEM_PLUME_FOSSIL = 173,
    ITEM_JAW_FOSSIL = 174,
    ITEM_SAIL_FOSSIL = 175,
    ITEM_FOSSILIZED_BIRD = 176,
    ITEM_FOSSILIZED_FISH = 177,
    ITEM_FOSSILIZED_DRAKE = 178,
    ITEM_FOSSILIZED_DINO = 179,
    ITEM_HAMMER_FOSSIL = 180,
    ITEM_LEAF_FOSSIL = 181,

    // Mulch
    ITEM_GROWTH_MULCH = 182,
    ITEM_DAMP_MULCH = 183,
    ITEM_STABLE_MULCH = 184,
    ITEM_GOOEY_MULCH = 185,
    ITEM_RICH_MULCH = 186,
    ITEM_SURPRISE_MULCH = 187,
    ITEM_BOOST_MULCH = 188,
    ITEM_AMAZE_MULCH = 189,

    // Apricorns
    ITEM_RED_APRICORN = 190,
    ITEM_BLUE_APRICORN = 191,
    ITEM_BLU_APRICORN = ITEM_BLUE_APRICORN, // Pre-Gen VI name
    ITEM_YELLOW_APRICORN = 192,
    ITEM_YLW_APRICORN = ITEM_YELLOW_APRICORN, // Pre-Gen VI name
    ITEM_GREEN_APRICORN = 193,
    ITEM_GRN_APRICORN = ITEM_GREEN_APRICORN, // Pre-Gen VI name
    ITEM_PINK_APRICORN = 194,
    ITEM_PNK_APRICORN = ITEM_PINK_APRICORN, // Pre-Gen VI name
    ITEM_WHITE_APRICORN = 195,
    ITEM_WHT_APRICORN = ITEM_WHITE_APRICORN, // Pre-Gen VI name
    ITEM_BLACK_APRICORN = 196,
    ITEM_BLK_APRICORN = ITEM_BLACK_APRICORN, // Pre-Gen VI name

    ITEM_WISHING_PIECE = 197,
    ITEM_GALARICA_TWIG = 198,
    ITEM_ARMORITE_ORE = 199,
    ITEM_DYNITE_ORE = 200,

    // Mail
    FIRST_MAIL_INDEX = 201,
    ITEM_ORANGE_MAIL = FIRST_MAIL_INDEX,
    ITEM_HARBOR_MAIL = 202,
    ITEM_GLITTER_MAIL = 203,
    ITEM_MECH_MAIL = 204,
    ITEM_WOOD_MAIL = 205,
    ITEM_WAVE_MAIL = 206,
    ITEM_BEAD_MAIL = 207,
    ITEM_SHADOW_MAIL = 208,
    ITEM_TROPIC_MAIL = 209,
    ITEM_DREAM_MAIL = 210,
    ITEM_FAB_MAIL = 211,
    ITEM_RETRO_MAIL = 212,

    // Evolution Items
    ITEM_FIRE_STONE = 213,
    ITEM_WATER_STONE = 214,
    ITEM_THUNDER_STONE = 215,
    ITEM_THUNDERSTONE = ITEM_THUNDER_STONE, // Pre-Gen VI name
    ITEM_LEAF_STONE = 216,
    ITEM_ICE_STONE = 217,
    ITEM_SUN_STONE = 218,
    ITEM_MOON_STONE = 219,
    ITEM_SHINY_STONE = 220,
    ITEM_DUSK_STONE = 221,
    ITEM_DAWN_STONE = 222,
    ITEM_SWEET_APPLE = 223,
    ITEM_TART_APPLE = 224,
    ITEM_CRACKED_POT = 225,
    ITEM_CHIPPED_POT = 226,
    ITEM_GALARICA_CUFF = 227,
    ITEM_GALARICA_WREATH = 228,
    ITEM_DRAGON_SCALE = 229,
    ITEM_UPGRADE = 230,
    ITEM_UP_GRADE = ITEM_UPGRADE, // Pre-Gen VIII name
    ITEM_PROTECTOR = 231,
    ITEM_ELECTIRIZER = 232,
    ITEM_MAGMARIZER = 233,
    ITEM_DUBIOUS_DISC = 234,
    ITEM_REAPER_CLOTH = 235,
    ITEM_PRISM_SCALE = 236,
    ITEM_WHIPPED_DREAM = 237,
    ITEM_SACHET = 238,
    ITEM_OVAL_STONE = 239,
    ITEM_STRAWBERRY_SWEET = 240,
    ITEM_LOVE_SWEET = 241,
    ITEM_BERRY_SWEET = 242,
    ITEM_CLOVER_SWEET = 243,
    ITEM_FLOWER_SWEET = 244,
    ITEM_STAR_SWEET = 245,
    ITEM_RIBBON_SWEET = 246,

    ITEM_EVERSTONE = 247,

    // Nectars
    ITEM_RED_NECTAR = 248,
    ITEM_YELLOW_NECTAR = 249,
    ITEM_PINK_NECTAR = 250,
    ITEM_PURPLE_NECTAR = 251,

    // Plates
    ITEM_FLAME_PLATE = 252,
    ITEM_SPLASH_PLATE = 253,
    ITEM_ZAP_PLATE = 254,
    ITEM_MEADOW_PLATE = 255,
    ITEM_ICICLE_PLATE = 256,
    ITEM_FIST_PLATE = 257,
    ITEM_TOXIC_PLATE = 258,
    ITEM_EARTH_PLATE = 259,
    ITEM_SKY_PLATE = 260,
    ITEM_MIND_PLATE = 261,
    ITEM_INSECT_PLATE = 262,
    ITEM_STONE_PLATE = 263,
    ITEM_SPOOKY_PLATE = 264,
    ITEM_DRACO_PLATE = 265,
    ITEM_DREAD_PLATE = 266,
    ITEM_IRON_PLATE = 267,
    ITEM_PIXIE_PLATE = 268,
    ITEM_SONAR_PLATE = 269,

    // Drives
    ITEM_DOUSE_DRIVE = 270,
    ITEM_SHOCK_DRIVE = 271,
    ITEM_BURN_DRIVE = 272,
    ITEM_CHILL_DRIVE = 273,

    // Memories
    ITEM_FIRE_MEMORY = 274,
    ITEM_WATER_MEMORY = 275,
    ITEM_ELECTRIC_MEMORY = 276,
    ITEM_GRASS_MEMORY = 277,
    ITEM_ICE_MEMORY = 278,
    ITEM_FIGHTING_MEMORY = 279,
    ITEM_POISON_MEMORY = 280,
    ITEM_GROUND_MEMORY = 281,
    ITEM_FLYING_MEMORY = 282,
    ITEM_PSYCHIC_MEMORY = 283,
    ITEM_BUG_MEMORY = 284,
    ITEM_ROCK_MEMORY = 285,
    ITEM_GHOST_MEMORY = 286,
    ITEM_DRAGON_MEMORY = 287,
    ITEM_DARK_MEMORY = 288,
    ITEM_STEEL_MEMORY = 289,
    ITEM_FAIRY_MEMORY = 290,
    ITEM_SOUND_MEMORY = 291,

    ITEM_RUSTED_SWORD = 292,
    ITEM_RUSTED_SHIELD = 293,

    // Colored Orbs
    ITEM_RED_ORB = 294,
    ITEM_BLUE_ORB = 295,
    ITEM_RED_CHAIN = 296,

    // Mega Stones
    ITEM_VENUSAURITE = 297,
    ITEM_CHARIZARDITE_X = 298,
    ITEM_CHARIZARDITE_Y = 299,
    ITEM_BLASTOISINITE = 300,
    ITEM_BEEDRILLITE = 301,
    ITEM_PIDGEOTITE = 302,
    ITEM_ALAKAZITE = 303,
    ITEM_SLOWBRONITE = 304,
    ITEM_GENGARITE = 305,
    ITEM_KANGASKHANITE = 306,
    ITEM_PINSIRITE = 307,
    ITEM_GYARADOSITE = 308,
    ITEM_AERODACTYLITE = 309,
    ITEM_MEWTWONITE_X = 310,
    ITEM_MEWTWONITE_Y = 311,
    ITEM_AMPHAROSITE = 312,
    ITEM_STEELIXITE = 313,
    ITEM_SCIZORITE = 314,
    ITEM_HERACRONITE = 315,
    ITEM_HOUNDOOMINITE = 316,
    ITEM_TYRANITARITE = 317,
    ITEM_SCEPTILITE = 318,
    ITEM_BLAZIKENITE = 319,
    ITEM_SWAMPERTITE = 320,
    ITEM_GARDEVOIRITE = 321,
    ITEM_SABLENITE = 322,
    ITEM_MAWILITE = 323,
    ITEM_AGGRONITE = 324,
    ITEM_MEDICHAMITE = 325,
    ITEM_MANECTITE = 326,
    ITEM_SHARPEDONITE = 327,
    ITEM_CAMERUPTITE = 328,
    ITEM_ALTARIANITE = 329,
    ITEM_BANETTITE = 330,
    ITEM_ABSOLITE = 331,
    ITEM_GLALITITE = 332,
    ITEM_SALAMENCITE = 333,
    ITEM_METAGROSSITE = 334,
    ITEM_LATIASITE = 335,
    ITEM_LATIOSITE = 336,
    ITEM_LOPUNNITE = 337,
    ITEM_GARCHOMPITE = 338,
    ITEM_LUCARIONITE = 339,
    ITEM_ABOMASITE = 340,
    ITEM_GALLADITE = 341,
    ITEM_AUDINITE = 342,
    ITEM_DIANCITE = 343,
    ITEM_PORYGONITE = 344,
    ITEM_TYPHLOSIONITE = 345,
    ITEM_EXPLOUDITE = 346,
    ITEM_MAMOSWITE = 347,
    ITEM_DUSKNOIRITE = 348,
    ITEM_TORTERRITE = 349,
    ITEM_INFERNITE = 350,
    ITEM_EMPOLEONITE = 351,
    ITEM_MUSHARNITE = 352,
    ITEM_COFAGRIGITE = 353,
    ITEM_GIGALITE = 354,

    // Gems
    ITEM_NORMAL_GEM = 355,
    ITEM_FIRE_GEM = 356,
    ITEM_WATER_GEM = 357,
    ITEM_ELECTRIC_GEM = 358,
    ITEM_GRASS_GEM = 359,
    ITEM_ICE_GEM = 360,
    ITEM_FIGHTING_GEM = 361,
    ITEM_POISON_GEM = 362,
    ITEM_GROUND_GEM = 363,
    ITEM_FLYING_GEM = 364,
    ITEM_PSYCHIC_GEM = 365,
    ITEM_BUG_GEM = 366,
    ITEM_ROCK_GEM = 367,
    ITEM_GHOST_GEM = 368,
    ITEM_DRAGON_GEM = 369,
    ITEM_DARK_GEM = 370,
    ITEM_STEEL_GEM = 371,
    ITEM_FAIRY_GEM = 372,
    ITEM_SOUND_GEM = 373,

    // Z-Crystals
    ITEM_NORMALIUM_Z = 374,
    ITEM_FIRIUM_Z = 375,
    ITEM_WATERIUM_Z = 376,
    ITEM_ELECTRIUM_Z = 377,
    ITEM_GRASSIUM_Z = 378,
    ITEM_ICIUM_Z = 379,
    ITEM_FIGHTINIUM_Z = 380,
    ITEM_POISONIUM_Z = 381,
    ITEM_GROUNDIUM_Z = 382,
    ITEM_FLYINIUM_Z = 383,
    ITEM_PSYCHIUM_Z = 384,
    ITEM_BUGINIUM_Z = 385,
    ITEM_ROCKIUM_Z = 386,
    ITEM_GHOSTIUM_Z = 387,
    ITEM_DRAGONIUM_Z = 388,
    ITEM_DARKINIUM_Z = 389,
    ITEM_STEELIUM_Z = 390,
    ITEM_FAIRIUM_Z = 391,
    ITEM_SOUNDIUM_Z = 392,
    ITEM_PIKANIUM_Z = 393,
    ITEM_EEVIUM_Z = 394,
    ITEM_SNORLIUM_Z = 395,
    ITEM_MEWNIUM_Z = 396,
    ITEM_DECIDIUM_Z = 397,
    ITEM_INCINIUM_Z = 398,
    ITEM_PRIMARIUM_Z = 399,
    ITEM_LYCANIUM_Z = 400,
    ITEM_MIMIKIUM_Z = 401,
    ITEM_KOMMONIUM_Z = 402,
    ITEM_TAPUNIUM_Z = 403,
    ITEM_SOLGANIUM_Z = 404,
    ITEM_LUNALIUM_Z = 405,
    ITEM_MARSHADIUM_Z = 406,
    ITEM_ALORAICHIUM_Z = 407,
    ITEM_PIKASHUNIUM_Z = 408,
    ITEM_ULTRANECROZIUM_Z = 409,

    // Species-specific Held Items
    ITEM_LIGHT_BALL = 410,
    ITEM_LEEK = 411,
    ITEM_STICK = ITEM_LEEK, // Pre-Gen VIII name
    ITEM_THICK_CLUB = 412,
    ITEM_LUCKY_PUNCH = 413,
    ITEM_METAL_POWDER = 414,
    ITEM_QUICK_POWDER = 415,
    ITEM_DEEP_SEA_SCALE = 416,
    ITEM_DEEPSEASCALE = ITEM_DEEP_SEA_SCALE, // Pre-Gen VI name
    ITEM_DEEP_SEA_TOOTH = 417,
    ITEM_DEEPSEATOOTH = ITEM_DEEP_SEA_TOOTH, // Pre-Gen VI name
    ITEM_SOUL_DEW = 418,
    ITEM_ADAMANT_ORB = 419,
    ITEM_LUSTROUS_ORB = 420,
    ITEM_GRISEOUS_ORB = 421,

    // Incenses
    ITEM_SEA_INCENSE = 422,
    ITEM_LAX_INCENSE = 423,
    ITEM_ODD_INCENSE = 424,
    ITEM_ROCK_INCENSE = 425,
    ITEM_FULL_INCENSE = 426,
    ITEM_WAVE_INCENSE = 427,
    ITEM_ROSE_INCENSE = 428,
    ITEM_LUCK_INCENSE = 429,
    ITEM_PURE_INCENSE = 430,

    // Contest Scarves
    ITEM_RED_SCARF = 431,
    ITEM_BLUE_SCARF = 432,
    ITEM_PINK_SCARF = 433,
    ITEM_GREEN_SCARF = 434,
    ITEM_YELLOW_SCARF = 435,

    // EV Gain Modifiers
    ITEM_MACHO_BRACE = 436,
    ITEM_POWER_WEIGHT = 437,
    ITEM_POWER_BRACER = 438,
    ITEM_POWER_BELT = 439,
    ITEM_POWER_LENS = 440,
    ITEM_POWER_BAND = 441,
    ITEM_POWER_ANKLET = 442,

    // Type-boosting Held Items
    ITEM_SILK_SCARF = 443,
    ITEM_CHARCOAL = 444,
    ITEM_MYSTIC_WATER = 445,
    ITEM_MAGNET = 446,
    ITEM_MIRACLE_SEED = 447,
    ITEM_NEVER_MELT_ICE = 448,
    ITEM_NEVERMELTICE = ITEM_NEVER_MELT_ICE, // Pre-Gen VI name
    ITEM_BLACK_BELT = 449,
    ITEM_BLACKBELT = ITEM_BLACK_BELT, // Gen II name
    ITEM_POISON_BARB = 450,
    ITEM_SOFT_SAND = 451,
    ITEM_SHARP_BEAK = 452,
    ITEM_TWISTED_SPOON = 453,
    ITEM_TWISTEDSPOON = ITEM_TWISTED_SPOON, // Pre-Gen VI name
    ITEM_SILVER_POWDER = 454,
    ITEM_SILVERPOWDER = ITEM_SILVER_POWDER, // Pre-Gen VI name
    ITEM_HARD_STONE = 455,
    ITEM_SPELL_TAG = 456,
    ITEM_DRAGON_FANG = 457,
    ITEM_BLACK_GLASSES = 458,
    ITEM_BLACKGLASSES = ITEM_BLACK_GLASSES, // Pre-Gen VI name
    ITEM_METAL_COAT = 459,
    ITEM_MP3_PLAYER = 460,

    // Choice Items
    ITEM_CHOICE_BAND = 461,
    ITEM_CHOICE_SPECS = 462,
    ITEM_CHOICE_SCARF = 463,

    // Status Orbs
    ITEM_FLAME_ORB = 464,
    ITEM_TOXIC_ORB = 465,

    // Weather Rocks
    ITEM_DAMP_ROCK = 466,
    ITEM_HEAT_ROCK = 467,
    ITEM_SMOOTH_ROCK = 468,
    ITEM_ICY_ROCK = 469,

    // Terrain Seeds
    ITEM_ELECTRIC_SEED = 470,
    ITEM_PSYCHIC_SEED = 471,
    ITEM_MISTY_SEED = 472,
    ITEM_GRASSY_SEED = 473,

    // Type-activated Stat Modifiers
    ITEM_ABSORB_BULB = 474,
    ITEM_CELL_BATTERY = 475,
    ITEM_LUMINOUS_MOSS = 476,
    ITEM_SNOWBALL = 477,

    // Misc. Held Items
    ITEM_BRIGHT_POWDER = 478,
    ITEM_BRIGHTPOWDER = ITEM_BRIGHT_POWDER, // Pre-Gen VI name
    ITEM_WHITE_HERB = 479,
    ITEM_EXP_SHARE = 480,
    ITEM_EXP_ALL = ITEM_EXP_SHARE, // Gen I name
    ITEM_QUICK_CLAW = 481,
    ITEM_SOOTHE_BELL = 482,
    ITEM_MENTAL_HERB = 483,
    ITEM_KINGS_ROCK = 484,
    ITEM_AMULET_COIN = 485,
    ITEM_CLEANSE_TAG = 486,
    ITEM_SMOKE_BALL = 487,
    ITEM_FOCUS_BAND = 488,
    ITEM_LUCKY_EGG = 489,
    ITEM_SCOPE_LENS = 490,
    ITEM_LEFTOVERS = 491,
    ITEM_SHELL_BELL = 492,
    ITEM_WIDE_LENS = 493,
    ITEM_MUSCLE_BAND = 494,
    ITEM_WISE_GLASSES = 495,
    ITEM_EXPERT_BELT = 496,
    ITEM_LIGHT_CLAY = 497,
    ITEM_LIFE_ORB = 498,
    ITEM_POWER_HERB = 499,
    ITEM_FOCUS_SASH = 500,
    ITEM_ZOOM_LENS = 501,
    ITEM_METRONOME = 502,
    ITEM_IRON_BALL = 503,
    ITEM_LAGGING_TAIL = 504,
    ITEM_DESTINY_KNOT = 505,
    ITEM_BLACK_SLUDGE = 506,
    ITEM_GRIP_CLAW = 507,
    ITEM_STICKY_BARB = 508,
    ITEM_SHED_SHELL = 509,
    ITEM_BIG_ROOT = 510,
    ITEM_RAZOR_CLAW = 511,
    ITEM_RAZOR_FANG = 512,
    ITEM_EVIOLITE = 513,
    ITEM_FLOAT_STONE = 514,
    ITEM_ROCKY_HELMET = 515,
    ITEM_AIR_BALLOON = 516,
    ITEM_YELLOW_CARD = 517,
    ITEM_RED_CARD = 518,
    ITEM_RING_TARGET = 519,
    ITEM_BINDING_BAND = 520,
    ITEM_EJECT_BUTTON = 521,
    ITEM_WEAKNESS_POLICY = 522,
    ITEM_ASSAULT_VEST = 523,
    ITEM_SAFETY_GOGGLES = 524,
    ITEM_ADRENALINE_ORB = 525,
    ITEM_TERRAIN_EXTENDER = 526,
    ITEM_PROTECTIVE_PADS = 527,
    ITEM_THROAT_SPRAY = 528,
    ITEM_EJECT_PACK = 529,
    ITEM_HEAVY_DUTY_BOOTS = 530,
    ITEM_BLUNDER_POLICY = 531,
    ITEM_ROOM_SERVICE = 532,
    ITEM_UTILITY_UMBRELLA = 533,

    // Berries
    FIRST_BERRY_INDEX = 534,
    ITEM_CHERI_BERRY = FIRST_BERRY_INDEX,
    ITEM_CHESTO_BERRY = 535,
    ITEM_PECHA_BERRY = 536,
    ITEM_RAWST_BERRY = 537,
    ITEM_ASPEAR_BERRY = 538,
    ITEM_LEPPA_BERRY = 539,
    ITEM_ORAN_BERRY = 540,
    ITEM_PERSIM_BERRY = 541,
    ITEM_LUM_BERRY = 542,
    ITEM_SITRUS_BERRY = 543,
    ITEM_FIGY_BERRY = 544,
    ITEM_WIKI_BERRY = 545,
    ITEM_MAGO_BERRY = 546,
    ITEM_AGUAV_BERRY = 547,
    ITEM_IAPAPA_BERRY = 548,
    ITEM_RAZZ_BERRY = 549,
    ITEM_BLUK_BERRY = 550,
    ITEM_NANAB_BERRY = 551,
    ITEM_WEPEAR_BERRY = 552,
    ITEM_PINAP_BERRY = 553,
    ITEM_POMEG_BERRY = 554,
    ITEM_KELPSY_BERRY = 555,
    ITEM_QUALOT_BERRY = 556,
    ITEM_HONDEW_BERRY = 557,
    ITEM_GREPA_BERRY = 558,
    ITEM_TAMATO_BERRY = 559,
    ITEM_CORNN_BERRY = 560,
    ITEM_MAGOST_BERRY = 561,
    ITEM_RABUTA_BERRY = 562,
    ITEM_NOMEL_BERRY = 563,
    ITEM_SPELON_BERRY = 564,
    ITEM_PAMTRE_BERRY = 565,
    ITEM_WATMEL_BERRY = 566,
    ITEM_DURIN_BERRY = 567,
    ITEM_BELUE_BERRY = 568,
    ITEM_CHILAN_BERRY = 569,
    ITEM_OCCA_BERRY = 570,
    ITEM_PASSHO_BERRY = 571,
    ITEM_WACAN_BERRY = 572,
    ITEM_RINDO_BERRY = 573,
    ITEM_YACHE_BERRY = 574,
    ITEM_CHOPLE_BERRY = 575,
    ITEM_KEBIA_BERRY = 576,
    ITEM_SHUCA_BERRY = 577,
    ITEM_COBA_BERRY = 578,
    ITEM_PAYAPA_BERRY = 579,
    ITEM_TANGA_BERRY = 580,
    ITEM_CHARTI_BERRY = 581,
    ITEM_KASIB_BERRY = 582,
    ITEM_HABAN_BERRY = 583,
    ITEM_COLBUR_BERRY = 584,
    ITEM_BABIRI_BERRY = 585,
    ITEM_ROSELI_BERRY = 586,
    ITEM_LIECHI_BERRY = 587,
    ITEM_GANLON_BERRY = 588,
    ITEM_SALAC_BERRY = 589,
    ITEM_PETAYA_BERRY = 590,
    ITEM_APICOT_BERRY = 591,
    ITEM_LANSAT_BERRY = 592,
    ITEM_STARF_BERRY = 593,
    ITEM_ENIGMA_BERRY = 594,
    ITEM_MICLE_BERRY = 595,
    ITEM_CUSTAP_BERRY = 596,
    ITEM_JABOCA_BERRY = 597,
    ITEM_ROWAP_BERRY = 598,
    ITEM_KEE_BERRY = 599,
    ITEM_MARANGA_BERRY = 600,
    ITEM_NINIKU_BERRY = 601,
    ITEM_ENIGMA_BERRY_E_READER = 602,
    LAST_BERRY_INDEX =  ITEM_ENIGMA_BERRY_E_READER,

    // TMs/HMs
    ITEM_TM01 = 603,
    ITEM_TM02 = 604,
    ITEM_TM03 = 605,
    ITEM_TM04 = 606,
    ITEM_TM05 = 607,
    ITEM_TM06 = 608,
    ITEM_TM07 = 609,
    ITEM_TM08 = 610,
    ITEM_TM09 = 611,
    ITEM_TM10 = 612,
    ITEM_TM11 = 613,
    ITEM_TM12 = 614,
    ITEM_TM13 = 615,
    ITEM_TM14 = 616,
    ITEM_TM15 = 617,
    ITEM_TM16 = 618,
    ITEM_TM17 = 619,
    ITEM_TM18 = 620,
    ITEM_TM19 = 621,
    ITEM_TM20 = 622,
    ITEM_TM21 = 623,
    ITEM_TM22 = 624,
    ITEM_TM23 = 625,
    ITEM_TM24 = 626,
    ITEM_TM25 = 627,
    ITEM_TM26 = 628,
    ITEM_TM27 = 629,
    ITEM_TM28 = 630,
    ITEM_TM29 = 631,
    ITEM_TM30 = 632,
    ITEM_TM31 = 633,
    ITEM_TM32 = 634,
    ITEM_TM33 = 635,
    ITEM_TM34 = 636,
    ITEM_TM35 = 637,
    ITEM_TM36 = 638,
    ITEM_TM37 = 639,
    ITEM_TM38 = 640,
    ITEM_TM39 = 641,
    ITEM_TM40 = 642,
    ITEM_TM41 = 643,
    ITEM_TM42 = 644,
    ITEM_TM43 = 645,
    ITEM_TM44 = 646,
    ITEM_TM45 = 647,
    ITEM_TM46 = 648,
    ITEM_TM47 = 649,
    ITEM_TM48 = 650,
    ITEM_TM49 = 651,
    ITEM_TM50 = 652,
    ITEM_TM51 = 653,
    ITEM_TM52 = 654,
    ITEM_TM53 = 655,
    ITEM_TM54 = 656,
    ITEM_TM55 = 657,
    ITEM_TM56 = 658,
    ITEM_TM57 = 659,
    ITEM_TM58 = 660,
    ITEM_TM59 = 661,
    ITEM_TM60 = 662,
    ITEM_TM61 = 663,
    ITEM_TM62 = 664,
    ITEM_TM63 = 665,
    ITEM_TM64 = 666,
    ITEM_TM65 = 667,
    ITEM_TM66 = 668,
    ITEM_TM67 = 669,
    ITEM_TM68 = 670,
    ITEM_TM69 = 671,
    ITEM_TM70 = 672,
    ITEM_TM71 = 673,
    ITEM_TM72 = 674,
    ITEM_TM73 = 675,
    ITEM_TM74 = 676,
    ITEM_TM75 = 677,
    ITEM_TM76 = 678,
    ITEM_TM77 = 679,
    ITEM_TM78 = 680,
    ITEM_TM79 = 681,
    ITEM_TM80 = 682,
    ITEM_TM81 = 683,
    ITEM_TM82 = 684,
    ITEM_TM83 = 685,
    ITEM_TM84 = 686,
    ITEM_TM85 = 687,
    ITEM_TM86 = 688,
    ITEM_TM87 = 689,
    ITEM_TM88 = 690,
    ITEM_TM89 = 691,
    ITEM_TM90 = 692,
    ITEM_TM91 = 693,
    ITEM_TM92 = 694,
    ITEM_TM93 = 695,
    ITEM_TM94 = 696,
    ITEM_TM95 = 697,
    ITEM_TM96 = 698,
    ITEM_TM97 = 699,
    ITEM_TM98 = 700,
    ITEM_TM99 = 701,
    ITEM_TM100 = 702,

    ITEM_HM01 = 703,
    ITEM_HM02 = 704,
    ITEM_HM03 = 705,
    ITEM_HM04 = 706,
    ITEM_HM05 = 707,
    ITEM_HM06 = 708,
    ITEM_HM07 = 709,
    ITEM_HM08 = 710,


    /* Expands to:
     *   ITEM_TM_FOCUS_PUNCH = ITEM_TM01,
     *   ...
     *   ITEM_HM_CUT = ITM_HM01,
     *   ... */
    #define ENUM_TM(n, id) CAT(ITEM_TM_, id) = CAT(ITEM_TM, n),
    #define ENUM_HM(n, id) CAT(ITEM_HM_, id) = CAT(ITEM_HM, n),
    #define TO_TMHM_NUMS(a, ...) (__VA_ARGS__)
    RECURSIVELY(R_ZIP(ENUM_TM, TO_TMHM_NUMS NUMBERS_256, (FOREACH_TM(APPEND_COMMA))))
    RECURSIVELY(R_ZIP(ENUM_HM, TO_TMHM_NUMS NUMBERS_256, (FOREACH_HM(APPEND_COMMA))))
    #undef ENUM_TM
    #undef ENUM_HM
    #undef TO_TMHM_NUMS

    // Charms
    ITEM_OVAL_CHARM = 711,
    ITEM_SHINY_CHARM = 712,
    ITEM_CATCHING_CHARM = 713,
    ITEM_EXP_CHARM = 714,

    // Form-changing Key Items
    ITEM_ROTOM_CATALOG = 715,
    ITEM_GRACIDEA = 716,
    ITEM_REVEAL_GLASS = 717,
    ITEM_DNA_SPLICERS = 718,
    ITEM_ZYGARDE_CUBE = 719,
    ITEM_PRISON_BOTTLE = 720,
    ITEM_N_SOLARIZER = 721,
    ITEM_N_LUNARIZER = 722,
    ITEM_REINS_OF_UNITY = 723,

    // Battle Mechanic Key Items
    ITEM_MEGA_RING = 724,
    ITEM_Z_POWER_RING = 725,
    ITEM_DYNAMAX_BAND = 726,

    // Misc. Key Items
    ITEM_BICYCLE = 727,
    ITEM_MACH_BIKE = 728,
    ITEM_ACRO_BIKE = 729,
    ITEM_OLD_ROD = 730,
    ITEM_GOOD_ROD = 731,
    ITEM_SUPER_ROD = 732,
    ITEM_DOWSING_MACHINE = 733,
    ITEM_ITEMFINDER = ITEM_DOWSING_MACHINE, // Pre-Gen IV name
    ITEM_DOWSING_MCHN = ITEM_DOWSING_MACHINE, // Gen IV-V name
    ITEM_TOWN_MAP = 734,
    ITEM_VS_SEEKER = 735,
    ITEM_TM_CASE = 736,
    ITEM_BERRY_POUCH = 737,
    ITEM_POKEMON_BOX_LINK = 738,
    ITEM_POKEMON_BOX = ITEM_POKEMON_BOX_LINK, // Pre-Gen VIII name
    ITEM_COIN_CASE = 739,
    ITEM_POWDER_JAR = 740,
    ITEM_WAILMER_PAIL = 741,
    ITEM_POKE_RADAR = 742,
    ITEM_POKEBLOCK_CASE = 743,
    ITEM_SOOT_SACK = 744,
    ITEM_POKE_FLUTE = 745,
    ITEM_FAME_CHECKER = 746,
    ITEM_TEACHY_TV = 747,

    // Story Key Items
    ITEM_SS_TICKET = 748,
    ITEM_EON_TICKET = 749,
    ITEM_MYSTIC_TICKET = 750,
    ITEM_AURORA_TICKET = 751,
    ITEM_OLD_SEA_MAP = 752,
    ITEM_LETTER = 753,
    ITEM_DEVON_PARTS = 754,
    ITEM_DEVON_GOODS = ITEM_DEVON_PARTS, // Pre-Gen VI name
    ITEM_GO_GOGGLES = 755,
    ITEM_DEVON_SCOPE = 756,
    ITEM_BASEMENT_KEY = 757,
    ITEM_SCANNER = 758,
    ITEM_STORAGE_KEY = 759,
    ITEM_KEY_TO_ROOM_1 = 760,
    ITEM_RM_1_KEY = ITEM_KEY_TO_ROOM_1, // Pre-Gen VI name
    ITEM_KEY_TO_ROOM_2 = 761,
    ITEM_RM_2_KEY = ITEM_KEY_TO_ROOM_2, // Pre-Gen VI name
    ITEM_KEY_TO_ROOM_4 = 762,
    ITEM_RM_4_KEY = ITEM_KEY_TO_ROOM_4, // Pre-Gen VI name
    ITEM_KEY_TO_ROOM_6 = 763,
    ITEM_RM_6_KEY = ITEM_KEY_TO_ROOM_6, // Pre-Gen VI name
    ITEM_METEORITE = 764,
    ITEM_MAGMA_EMBLEM = 765,
    ITEM_CONTEST_PASS = 766,
    ITEM_PARCEL = 767,
    ITEM_OAKS_PARCEL = ITEM_PARCEL, // Pre-Gen IV name
    ITEM_SECRET_KEY = 768,
    ITEM_BIKE_VOUCHER = 769,
    ITEM_GOLD_TEETH = 770,
    ITEM_CARD_KEY = 771,
    ITEM_LIFT_KEY = 772,
    ITEM_SILPH_SCOPE = 773,
    ITEM_TRI_PASS = 774,
    ITEM_RAINBOW_PASS = 775,
    ITEM_TEA = 776,
    ITEM_RUBY = 777,
    ITEM_SAPPHIRE = 778,

    // GEN IX ITEMS
    ITEM_ABILITY_SHIELD = 779,
    ITEM_CLEAR_AMULET = 780,
    ITEM_PUNCHING_GLOVE = 781,
    ITEM_COVERT_CLOAK = 782,
    ITEM_LOADED_DICE = 783,
    ITEM_AUSPICIOUS_ARMOR = 784,
    ITEM_BOOSTER_ENERGY = 785,
    ITEM_BIG_BAMBOO_SHOOT = 786,
    ITEM_GIMMIGHOUL_COIN = 787,
    ITEM_LEADERS_CREST = 788,
    ITEM_MALICIOUS_ARMOR = 789,
    ITEM_MIRROR_HERB = 790,
    ITEM_SCROLL_OF_DARKNESS = 791,
    ITEM_SCROLL_OF_WATERS = 792,
    ITEM_TERA_ORB = 793,
    ITEM_TINY_BAMBOO_SHOOT = 794,

    ITEM_BUG_TERA_SHARD = 795,
    ITEM_DARK_TERA_SHARD = 796,
    ITEM_DRAGON_TERA_SHARD = 797,
    ITEM_ELECTRIC_TERA_SHARD = 798,
    ITEM_FAIRY_TERA_SHARD = 799,
    ITEM_FIGHTING_TERA_SHARD = 800,
    ITEM_FIRE_TERA_SHARD = 801,
    ITEM_FLYING_TERA_SHARD = 802,
    ITEM_GHOST_TERA_SHARD = 803,
    ITEM_GRASS_TERA_SHARD = 804,
    ITEM_GROUND_TERA_SHARD = 805,
    ITEM_ICE_TERA_SHARD = 806,
    ITEM_NORMAL_TERA_SHARD = 807,
    ITEM_POISON_TERA_SHARD = 808,
    ITEM_PSYCHIC_TERA_SHARD = 809,
    ITEM_ROCK_TERA_SHARD = 810,
    ITEM_STEEL_TERA_SHARD = 811,
    ITEM_WATER_TERA_SHARD = 812,
    ITEM_SOUND_TERA_SHARD = 813,

    ITEM_ADAMANT_CRYSTAL = 814,
    ITEM_GRISEOUS_CORE = 815,
    ITEM_LUSTROUS_GLOBE = 816,

    ITEM_BLACK_AUGURITE = 817,
    ITEM_LINKING_CORD = 818,
    ITEM_PEAT_BLOCK = 819,
    ITEM_BERSERK_GENE = 820,

    ITEM_FAIRY_FEATHER = 821,
    ITEM_SYRUPY_APPLE = 822,
    ITEM_UNREMARKABLE_TEACUP = 823,
    ITEM_MASTERPIECE_TEACUP = 824,
    ITEM_CORNERSTONE_MASK = 825,
    ITEM_WELLSPRING_MASK = 826,
    ITEM_HEARTHFLAME_MASK = 827,
    ITEM_HEALTH_MOCHI = 828,
    ITEM_MUSCLE_MOCHI = 829,
    ITEM_RESIST_MOCHI = 830,
    ITEM_GENIUS_MOCHI = 831,
    ITEM_CLEVER_MOCHI = 832,
    ITEM_SWIFT_MOCHI = 833,
    ITEM_FRESH_START_MOCHI = 834,
    ITEM_GLIMMERING_CHARM = 835,
    ITEM_METAL_ALLOY = 836,
    ITEM_STELLAR_TERA_SHARD = 837,

    ITEM_JUBILIFE_MUFFIN = 838,
    ITEM_REMEDY = 839,
    ITEM_FINE_REMEDY = 840,
    ITEM_SUPERB_REMEDY = 841,
    ITEM_AUX_EVASION = 842,
    ITEM_AUX_GUARD = 843,
    ITEM_AUX_POWER = 844,
    ITEM_AUX_POWERGUARD = 845,
    ITEM_CHOICE_DUMPLING = 846,
    ITEM_SWAP_SNACK = 847,
    ITEM_TWICE_SPICED_RADISH = 848,
    ITEM_POKESHI_DOLL = 849,

    ITEM_STRANGE_BALL = 850,

    // Legends Z-A Mega Stones
    ITEM_CLEFABLITE = 851,
    ITEM_VICTREEBELITE = 852,
    ITEM_STARMINITE = 853,
    ITEM_DRAGONINITE = 854,
    ITEM_MEGANIUMITE = 855,
    ITEM_FERALIGITE = 856,
    ITEM_SKARMORITE = 857,
    ITEM_FROSLASSITE = 858,
    ITEM_EMBOARITE = 859,
    ITEM_EXCADRITE = 860,
    ITEM_SCOLIPITE = 861,
    ITEM_SCRAFTINITE = 862,
    ITEM_EELEKTROSSITE = 863,
    ITEM_CHANDELURITE = 864,
    ITEM_CHESNAUGHTITE = 865,
    ITEM_DELPHOXITE = 866,
    ITEM_GRENINJITE = 867,
    ITEM_PYROARITE = 868,
    ITEM_FLOETTITE = 869,
    ITEM_MALAMARITE = 870,
    ITEM_BARBARACITE = 871,
    ITEM_DRAGALGITE = 872,
    ITEM_HAWLUCHANITE = 873,
    ITEM_ZYGARDITE = 874,
    ITEM_DRAMPANITE = 875,
    ITEM_FALINKSITE = 876,

    // Legends Z-A: Mega Dimension DLC Mega Stones
    ITEM_HEATRANITE = 877,
    ITEM_DARKRANITE = 878,
    ITEM_ZERAORITE = 879,
    ITEM_RAICHUNITE_X = 880,
    ITEM_RAICHUNITE_Y = 881,
    ITEM_CHIMECHITE = 882,
    ITEM_ABSOLITE_Z = 883,
    ITEM_STARAPTITE = 884,
    ITEM_GARCHOMPITE_Z = 885,
    ITEM_LUCARIONITE_Z = 886,
    ITEM_GOLURKITE = 887,
    ITEM_MEOWSTICITE = 888,
    ITEM_CRABOMINITE = 889,
    ITEM_GOLISOPITE = 890,
    ITEM_MAGEARNITE = 891,
    ITEM_SCOVILLAINITE = 892,
    ITEM_BAXCALIBRITE = 893,
    ITEM_TATSUGIRINITE = 894,
    ITEM_GLIMMORANITE = 895,

    ITEMS_COUNT,
    ITEM_FIELD_ARROW = ITEMS_COUNT,
};

// A special item id associated with "Cancel"/"Exit" etc. in a list of items or decorations
// Its icon is defined at ITEMS_COUNT as the "return to field" arrow
#define ITEM_LIST_END 0xFFFF

#if B_CONFUSE_BERRIES_HEAL >= GEN_8
    #define CONFUSE_BERRY_HEAL_FRACTION 3
#elif B_CONFUSE_BERRIES_HEAL == GEN_7
    #define CONFUSE_BERRY_HEAL_FRACTION 2
#else
    #define CONFUSE_BERRY_HEAL_FRACTION 8
#endif

#define CONFUSE_BERRY_HP_FRACTION ((B_CONFUSE_BERRIES_HEAL >= GEN_7) ? 4 : 2)

// Range of berries given out by various NPCS
#define FIRST_BERRY_MASTER_BERRY      ITEM_POMEG_BERRY
#define LAST_BERRY_MASTER_BERRY       ITEM_NOMEL_BERRY
#define FIRST_BERRY_MASTER_WIFE_BERRY ITEM_CHERI_BERRY
#define LAST_BERRY_MASTER_WIFE_BERRY  ITEM_SITRUS_BERRY
#define FIRST_KIRI_BERRY              ITEM_POMEG_BERRY
#define LAST_KIRI_BERRY               ITEM_NOMEL_BERRY
#define FIRST_ROUTE_114_MAN_BERRY     ITEM_RAZZ_BERRY
#define LAST_ROUTE_114_MAN_BERRY      ITEM_PINAP_BERRY

#define NUM_BERRY_MASTER_BERRIES          (LAST_BERRY_MASTER_BERRY - FIRST_BERRY_MASTER_BERRY + 1)
#define NUM_BERRY_MASTER_BERRIES_SKIPPED  (FIRST_BERRY_MASTER_BERRY - FIRST_BERRY_INDEX)
#define NUM_BERRY_MASTER_WIFE_BERRIES     (LAST_BERRY_MASTER_WIFE_BERRY - FIRST_BERRY_MASTER_WIFE_BERRY + 1)
#define NUM_KIRI_BERRIES                  (LAST_KIRI_BERRY - FIRST_KIRI_BERRY + 1)
#define NUM_KIRI_BERRIES_SKIPPED          (FIRST_KIRI_BERRY - FIRST_BERRY_INDEX)
#define NUM_ROUTE_114_MAN_BERRIES         (LAST_ROUTE_114_MAN_BERRY - FIRST_ROUTE_114_MAN_BERRY + 1)
#define NUM_ROUTE_114_MAN_BERRIES_SKIPPED (FIRST_ROUTE_114_MAN_BERRY - FIRST_BERRY_INDEX)

#define ITEM_TO_BERRY(itemId) (((itemId) - FIRST_BERRY_INDEX) + 1)
#define ITEM_TO_MAIL(itemId) ((itemId) - FIRST_MAIL_INDEX)
#define MAIL_NONE 0xFF
#define ITEM_TO_MULCH(itemId)(((itemId) - ITEM_GROWTH_MULCH) + 1)

#define MAX_BAG_ITEM_CAPACITY         999
#define MAX_PC_ITEM_CAPACITY          999
#define MAX_PYRAMID_BAG_ITEM_CAPACITY  99 // Values higher than 255 require free SaveBlock2 space.

#define MAX_ITEM_DIGITS         ((MAX_BAG_ITEM_CAPACITY > 99) ? 3 : 2)
#define MAX_PYRAMID_ITEM_DIGITS ((MAX_PYRAMID_BAG_ITEM_CAPACITY > 99) ? 3 : 2)

// Secondary IDs for rods
#define OLD_ROD   0
#define GOOD_ROD  1
#define SUPER_ROD 2

// Secondary IDs for bikes
#define MACH_BIKE 0
#define ACRO_BIKE 1
#define STANDARD_BIKE 2

// Item parameters for EXP Candies
#define EXP_100   1
#define EXP_800   2
#define EXP_3000  3
#define EXP_10000 4
#define EXP_30000 5

// Item type IDs (used to determine the exit callback)
enum ItemType
{
    ITEM_USE_MAIL,
    ITEM_USE_PARTY_MENU,
    ITEM_USE_FIELD,
    ITEM_USE_PBLOCK_CASE,
    ITEM_USE_BAG_MENU, // No exit callback, stays in bag menu
    ITEM_USE_PARTY_MENU_MOVES,
    ITEM_USE_BATTLER, // Auto-select in Singles but lets you choose from party menu in Doubles
};

// Item battle script IDs (need to be non-zero)
enum EffectItem
{
    EFFECT_ITEM_ENIGMA_BERRY_EREADER = 1, // dummy constant
    EFFECT_ITEM_RESTORE_HP = 1, // needs to be non-zero
    EFFECT_ITEM_CURE_STATUS,
    EFFECT_ITEM_HEAL_AND_CURE_STATUS,
    EFFECT_ITEM_INCREASE_STAT,
    EFFECT_ITEM_SET_MIST,
    EFFECT_ITEM_SET_FOCUS_ENERGY,
    EFFECT_ITEM_ESCAPE,
    EFFECT_ITEM_THROW_BALL,
    EFFECT_ITEM_REVIVE,
    EFFECT_ITEM_RESTORE_PP,
    EFFECT_ITEM_INCREASE_ALL_STATS,
    EFFECT_ITEM_USE_POKE_FLUTE,
};

#endif  // GUARD_CONSTANTS_ITEMS_H
