gText_Birch_Welcome::
	.string "Oh gosh! I've fallen into a\n"
	.string "Black hole!\p"
	.string "…But I'm fine?\p"
	.string "How is this possible?\p"
	.string "Is this good game design?\n"
	.string "Or a lazy cover-up?\p"
	.string "I guess I'll just smile and\n"
	.string "Play it off…\p"
	.string "My name is Doctor Proffessor\n"
	.string "Kieran Unicorn.\p"
	.string "I am the Pokémon Proffessor\n"
	.string "Of the Banjime Region!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is my favorite Pokémon!\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "There are many Pokémon in the\n"
	.string "Banjime Region indigenous to it.\p"
	.string "As a world-renowned biologist,\n"
	.string "I have been studying these unique\l"
	.string "Pokémon to show them to the world.\p"
	.string "Also, many Pokémon found elsewhere\n"
	.string "in the world have different stats,\l"
	.string "types, or abilities in this region.\p"
	.string "In order to make my work easier,\n"
	.string "I made field research laboratories\l"
	.string "all throughout the region.\p"
	.string "If you ever see one of my labs,\n"
	.string "feel free to drop on by!\l"
	.string "But enough about me.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "How about you?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "You're {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "{PLAYER}{KUN}!\n"
	.string "Nice to meet you!\p"
	.string "You're from Zephyr Town?\n"
	.string "I have a lab out there!\l"
	.string "Let's meet there tomorrow!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Are you ready, bitch?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Pokémon where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my Pokémon Lab.\p"
	.string "$"
