LittlerootTown_SeansHouse_MapScripts::
	.byte 0

LittlerootTown_SeansHouse_EventScript_SeansSister::
	msgbox LittlerootTown_Text_SeansSister, MSGBOX_NPC
	end

LittlerootTown_Text_SeansSister:
	.string "Mindy: Hey, {PLAYER}!\n"
	.string "How are you doing?\p"
	.string "I hope my little brother hasn't\n"
	.string "been giving you too much trouble.\p"
	.string "Try to keep an eye on him, would you?\p"
	.string "I know he's his own man now,\n"
	.string "but I can't help but worry about him.\p"
	.string "You, Sean, and Amelia…\n"
	.string "You're all in my prayers constantly!$"


