PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "Have you heard of Moose?\p"
	.string "He's a member of the Elite Four.\p"
	.string "He became champion a few years ago, but\n"
	.string "was defeated.\p"
	.string "After that, he became the Gym Leader of\n"
	.string "Arkane City.\p"
	.string "Didn't you know?\p"
	.string "To become a Gym Leader, you must become\n"
	.string "the Pokémon League Champion. Then, you\l"
	.string "must lose your title to someone else.\p"
	.string "Each champion chooses his or her own\n"
	.string "Elite Four of former champions, and the\l"
	.string "rest become Gym Leaders.\p"
	.string "Moose was chosen to be a member of the\n"
	.string "current champion, Gwen's Elite Four.$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "Each member of the Elite Four presides\n"
	.string "over a portion of Banjime.\p"
	.string "We're in the Northwest, so we're in\n"
	.string "Moose's jurisdiction.\p"
	.string "He prioritizes his hometown, Arkane City,\n"
	.string "a bit more than us, but he takes care of\l"
	.string "the rest of us pretty well nonetheless.\p"
	.string "Besides, it's a Gym Leader's job to\n"
	.string "defend us when Moose isn't available.\p"
	.string "I thank God for strong trainers!$"

