PetalburgCity_OtnarsInn_3F_MapScripts::
	.byte 0

PetalburgCity_OtnarsInn_3F_EventScript_GruntM::
	msgbox PetalburgCity_OtnarsInn_3F_Text_GruntM, MSGBOX_NPC
	end

PetalburgCity_OtnarsInn_3F_Text_GruntM:
	.string "I promised Zinzolin I'd follow him\n"
	.string "to the ends of the Earth.\p"
	.string "So why is it that we always end up\n"
	.string "in frigid tundras?!$"

PetalburgCity_OtnarsInn_3F_EventScript_Nerd::
	msgbox PetalburgCity_OtnarsInn_3F_Text_Nerd, MSGBOX_NPC
	end

PetalburgCity_OtnarsInn_3F_Text_Nerd:
	.string "I came here to display my artwork.\p"
	.string "I'm excited to show my skills,\n"
	.string "but I can't sleep soundly knowing\l"
	.string "that Team Plasma is in the next room!$"
