LittlerootTown_AmeliasHouse_MapScripts::
	.byte 0

LittlerootTown_SeansHouse_EventScript_AmeliasMom::
	msgbox LittlerootTown_Text_AmeliasMom, MSGBOX_NPC
	end

LittlerootTown_Text_AmeliasMom:
	.string "Amelia's Mom: {PLAYER}!\n"
	.string "Good to see you!\p"
	.string "Gosh, it seems like just yesterday\n"
	.string "that you, Sean, and Amelia were all\l"
	.string "playing in the bath together.\p"
	.string "The three of you have grown into\n"
	.string "fine young men and women.\p"
	.string "I know I've got little to worry about\n"
	.string "when it comes to my daughter, but\l"
	.string "I'm still very grateful she has you.$"

