#include "global.h"
#include "constants/passive.h"
#include "passive_indicators.h"

static const u8 ALIGNED(4) sBoostNormalIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_normal_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostFireIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_fire_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostWaterIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_water_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostGrassIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_grass_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostElectricIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_electric_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostIceIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_ice_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostFightingIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_fighting_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostPoisonIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_poison_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostGroundIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_ground_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostFlyingIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_flying_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostPsychicIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_psychic_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostBugIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_bug_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostRockIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_rock_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostGhostIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_ghost_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostDragonIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_dragon_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostDarkIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_dark_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostSteelIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_steel_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostFairyIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_fairy_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostSoundIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_sound_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistNormalIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_normal_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistFireIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_fire_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistWaterIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_water_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistGrassIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_grass_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistElectricIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_electric_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistIceIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_ice_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistFightingIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_fighting_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistPoisonIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_poison_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistGroundIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_ground_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistFlyingIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_flying_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistPsychicIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_psychic_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistBugIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_bug_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistRockIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_rock_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistGhostIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_ghost_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistDragonIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_dragon_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistDarkIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_dark_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistSteelIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_steel_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistFairyIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_fairy_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistSoundIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_sound_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullNormalIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_normal_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullFireIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_fire_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullWaterIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_water_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullGrassIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_grass_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullElectricIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_electric_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullIceIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_ice_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullFightingIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_fighting_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullPoisonIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_poison_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullGroundIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_ground_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullFlyingIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_flying_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullPsychicIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_psychic_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullBugIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_bug_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullRockIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_rock_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullGhostIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_ghost_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullDragonIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_dragon_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullDarkIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_dark_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullSteelIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_steel_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullFairyIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_fairy_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullSoundIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_sound_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDrainNormalIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/drain_normal_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDrainFireIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/drain_fire_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDrainWaterIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/drain_water_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDrainGrassIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/drain_grass_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDrainElectricIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/drain_electric_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDrainIceIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/drain_ice_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDrainFightingIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/drain_fighting_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDrainPoisonIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/drain_poison_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDrainGroundIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/drain_ground_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDrainFlyingIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/drain_flying_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDrainPsychicIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/drain_psychic_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDrainBugIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/drain_bug_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDrainRockIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/drain_rock_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDrainGhostIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/drain_ghost_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDrainDragonIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/drain_dragon_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDrainDarkIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/drain_dark_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDrainSteelIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/drain_steel_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDrainFairyIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/drain_fairy_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDrainSoundIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/drain_sound_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sRepelNormalIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/repel_normal_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sRepelFireIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/repel_fire_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sRepelWaterIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/repel_water_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sRepelGrassIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/repel_grass_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sRepelElectricIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/repel_electric_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sRepelIceIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/repel_ice_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sRepelFightingIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/repel_fighting_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sRepelPoisonIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/repel_poison_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sRepelGroundIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/repel_ground_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sRepelFlyingIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/repel_flying_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sRepelPsychicIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/repel_psychic_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sRepelBugIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/repel_bug_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sRepelRockIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/repel_rock_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sRepelGhostIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/repel_ghost_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sRepelDragonIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/repel_dragon_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sRepelDarkIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/repel_dark_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sRepelSteelIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/repel_steel_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sRepelFairyIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/repel_fairy_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sRepelSoundIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/repel_sound_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostHealIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_heal_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostCritIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_crit_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostSpeedIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_speed_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostPhysIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_phys_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sBoostSpecIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/boost_spec_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistPhysIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_phys_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sResistSpecIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/resist_spec_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sPhysMasteryIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/phys_mastery_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sSpecMasteryIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/spec_mastery_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sAttackMasteryIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/attack_mastery_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sDefenseMasteryIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/defense_mastery_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sCopyPassiveIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/copy_passive_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sSteadyHealIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/steady_heal_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sPierceIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/pierce_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sChangeClearIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/change_clear_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sStatusClearIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/status_clear_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullSeIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_se_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullAeIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_ae_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullNveIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_nve_indicator.png", ".4bpp");
static const u8 ALIGNED(4) sNullPdIndicatorGfx[] = INCGFX_U8("graphics/battle_interface/null_pd_indicator.png", ".4bpp");

const u8 *const gPassiveIndicatorGfx[PASSIVES_COUNT] =
{
    [PASSIVE_BOOST_NORMAL] = sBoostNormalIndicatorGfx,
    [PASSIVE_BOOST_FIRE] = sBoostFireIndicatorGfx,
    [PASSIVE_BOOST_WATER] = sBoostWaterIndicatorGfx,
    [PASSIVE_BOOST_GRASS] = sBoostGrassIndicatorGfx,
    [PASSIVE_BOOST_ELECTRIC] = sBoostElectricIndicatorGfx,
    [PASSIVE_BOOST_ICE] = sBoostIceIndicatorGfx,
    [PASSIVE_BOOST_FIGHTING] = sBoostFightingIndicatorGfx,
    [PASSIVE_BOOST_POISON] = sBoostPoisonIndicatorGfx,
    [PASSIVE_BOOST_GROUND] = sBoostGroundIndicatorGfx,
    [PASSIVE_BOOST_FLYING] = sBoostFlyingIndicatorGfx,
    [PASSIVE_BOOST_PSYCHIC] = sBoostPsychicIndicatorGfx,
    [PASSIVE_BOOST_BUG] = sBoostBugIndicatorGfx,
    [PASSIVE_BOOST_ROCK] = sBoostRockIndicatorGfx,
    [PASSIVE_BOOST_GHOST] = sBoostGhostIndicatorGfx,
    [PASSIVE_BOOST_DRAGON] = sBoostDragonIndicatorGfx,
    [PASSIVE_BOOST_DARK] = sBoostDarkIndicatorGfx,
    [PASSIVE_BOOST_STEEL] = sBoostSteelIndicatorGfx,
    [PASSIVE_BOOST_FAIRY] = sBoostFairyIndicatorGfx,
    [PASSIVE_BOOST_SOUND] = sBoostSoundIndicatorGfx,
    [PASSIVE_RESIST_NORMAL] = sResistNormalIndicatorGfx,
    [PASSIVE_RESIST_FIRE] = sResistFireIndicatorGfx,
    [PASSIVE_RESIST_WATER] = sResistWaterIndicatorGfx,
    [PASSIVE_RESIST_GRASS] = sResistGrassIndicatorGfx,
    [PASSIVE_RESIST_ELECTRIC] = sResistElectricIndicatorGfx,
    [PASSIVE_RESIST_ICE] = sResistIceIndicatorGfx,
    [PASSIVE_RESIST_FIGHTING] = sResistFightingIndicatorGfx,
    [PASSIVE_RESIST_POISON] = sResistPoisonIndicatorGfx,
    [PASSIVE_RESIST_GROUND] = sResistGroundIndicatorGfx,
    [PASSIVE_RESIST_FLYING] = sResistFlyingIndicatorGfx,
    [PASSIVE_RESIST_PSYCHIC] = sResistPsychicIndicatorGfx,
    [PASSIVE_RESIST_BUG] = sResistBugIndicatorGfx,
    [PASSIVE_RESIST_ROCK] = sResistRockIndicatorGfx,
    [PASSIVE_RESIST_GHOST] = sResistGhostIndicatorGfx,
    [PASSIVE_RESIST_DRAGON] = sResistDragonIndicatorGfx,
    [PASSIVE_RESIST_DARK] = sResistDarkIndicatorGfx,
    [PASSIVE_RESIST_STEEL] = sResistSteelIndicatorGfx,
    [PASSIVE_RESIST_FAIRY] = sResistFairyIndicatorGfx,
    [PASSIVE_RESIST_SOUND] = sResistSoundIndicatorGfx,
    [PASSIVE_NULL_NORMAL] = sNullNormalIndicatorGfx,
    [PASSIVE_NULL_FIRE] = sNullFireIndicatorGfx,
    [PASSIVE_NULL_WATER] = sNullWaterIndicatorGfx,
    [PASSIVE_NULL_GRASS] = sNullGrassIndicatorGfx,
    [PASSIVE_NULL_ELECTRIC] = sNullElectricIndicatorGfx,
    [PASSIVE_NULL_ICE] = sNullIceIndicatorGfx,
    [PASSIVE_NULL_FIGHTING] = sNullFightingIndicatorGfx,
    [PASSIVE_NULL_POISON] = sNullPoisonIndicatorGfx,
    [PASSIVE_NULL_GROUND] = sNullGroundIndicatorGfx,
    [PASSIVE_NULL_FLYING] = sNullFlyingIndicatorGfx,
    [PASSIVE_NULL_PSYCHIC] = sNullPsychicIndicatorGfx,
    [PASSIVE_NULL_BUG] = sNullBugIndicatorGfx,
    [PASSIVE_NULL_ROCK] = sNullRockIndicatorGfx,
    [PASSIVE_NULL_GHOST] = sNullGhostIndicatorGfx,
    [PASSIVE_NULL_DRAGON] = sNullDragonIndicatorGfx,
    [PASSIVE_NULL_DARK] = sNullDarkIndicatorGfx,
    [PASSIVE_NULL_STEEL] = sNullSteelIndicatorGfx,
    [PASSIVE_NULL_FAIRY] = sNullFairyIndicatorGfx,
    [PASSIVE_NULL_SOUND] = sNullSoundIndicatorGfx,
    [PASSIVE_DRAIN_NORMAL] = sDrainNormalIndicatorGfx,
    [PASSIVE_DRAIN_FIRE] = sDrainFireIndicatorGfx,
    [PASSIVE_DRAIN_WATER] = sDrainWaterIndicatorGfx,
    [PASSIVE_DRAIN_GRASS] = sDrainGrassIndicatorGfx,
    [PASSIVE_DRAIN_ELECTRIC] = sDrainElectricIndicatorGfx,
    [PASSIVE_DRAIN_ICE] = sDrainIceIndicatorGfx,
    [PASSIVE_DRAIN_FIGHTING] = sDrainFightingIndicatorGfx,
    [PASSIVE_DRAIN_POISON] = sDrainPoisonIndicatorGfx,
    [PASSIVE_DRAIN_GROUND] = sDrainGroundIndicatorGfx,
    [PASSIVE_DRAIN_FLYING] = sDrainFlyingIndicatorGfx,
    [PASSIVE_DRAIN_PSYCHIC] = sDrainPsychicIndicatorGfx,
    [PASSIVE_DRAIN_BUG] = sDrainBugIndicatorGfx,
    [PASSIVE_DRAIN_ROCK] = sDrainRockIndicatorGfx,
    [PASSIVE_DRAIN_GHOST] = sDrainGhostIndicatorGfx,
    [PASSIVE_DRAIN_DRAGON] = sDrainDragonIndicatorGfx,
    [PASSIVE_DRAIN_DARK] = sDrainDarkIndicatorGfx,
    [PASSIVE_DRAIN_STEEL] = sDrainSteelIndicatorGfx,
    [PASSIVE_DRAIN_FAIRY] = sDrainFairyIndicatorGfx,
    [PASSIVE_DRAIN_SOUND] = sDrainSoundIndicatorGfx,
    [PASSIVE_REPEL_NORMAL] = sRepelNormalIndicatorGfx,
    [PASSIVE_REPEL_FIRE] = sRepelFireIndicatorGfx,
    [PASSIVE_REPEL_WATER] = sRepelWaterIndicatorGfx,
    [PASSIVE_REPEL_GRASS] = sRepelGrassIndicatorGfx,
    [PASSIVE_REPEL_ELECTRIC] = sRepelElectricIndicatorGfx,
    [PASSIVE_REPEL_ICE] = sRepelIceIndicatorGfx,
    [PASSIVE_REPEL_FIGHTING] = sRepelFightingIndicatorGfx,
    [PASSIVE_REPEL_POISON] = sRepelPoisonIndicatorGfx,
    [PASSIVE_REPEL_GROUND] = sRepelGroundIndicatorGfx,
    [PASSIVE_REPEL_FLYING] = sRepelFlyingIndicatorGfx,
    [PASSIVE_REPEL_PSYCHIC] = sRepelPsychicIndicatorGfx,
    [PASSIVE_REPEL_BUG] = sRepelBugIndicatorGfx,
    [PASSIVE_REPEL_ROCK] = sRepelRockIndicatorGfx,
    [PASSIVE_REPEL_GHOST] = sRepelGhostIndicatorGfx,
    [PASSIVE_REPEL_DRAGON] = sRepelDragonIndicatorGfx,
    [PASSIVE_REPEL_DARK] = sRepelDarkIndicatorGfx,
    [PASSIVE_REPEL_STEEL] = sRepelSteelIndicatorGfx,
    [PASSIVE_REPEL_FAIRY] = sRepelFairyIndicatorGfx,
    [PASSIVE_REPEL_SOUND] = sRepelSoundIndicatorGfx,
    [PASSIVE_BOOST_HEAL] = sBoostHealIndicatorGfx,
    [PASSIVE_BOOST_CRIT] = sBoostCritIndicatorGfx,
    [PASSIVE_BOOST_SPEED] = sBoostSpeedIndicatorGfx,
    [PASSIVE_BOOST_PHYS] = sBoostPhysIndicatorGfx,
    [PASSIVE_BOOST_SPEC] = sBoostSpecIndicatorGfx,
    [PASSIVE_RESIST_PHYS] = sResistPhysIndicatorGfx,
    [PASSIVE_RESIST_SPEC] = sResistSpecIndicatorGfx,
    [PASSIVE_PHYS_MASTERY] = sPhysMasteryIndicatorGfx,
    [PASSIVE_SPEC_MASTERY] = sSpecMasteryIndicatorGfx,
    [PASSIVE_ATK_MASTERY] = sAttackMasteryIndicatorGfx,
    [PASSIVE_DEF_MASTERY] = sDefenseMasteryIndicatorGfx,
    [PASSIVE_COPY] = sCopyPassiveIndicatorGfx,
    [PASSIVE_STEADY_HEAL] = sSteadyHealIndicatorGfx,
    [PASSIVE_PIERCE] = sPierceIndicatorGfx,
    [PASSIVE_CHANGE_CLEAR] = sChangeClearIndicatorGfx,
    [PASSIVE_STATUS_CLEAR] = sStatusClearIndicatorGfx,
    [PASSIVE_NULL_SE] = sNullSeIndicatorGfx,
    [PASSIVE_NULL_AE] = sNullAeIndicatorGfx,
    [PASSIVE_NULL_NVE] = sNullNveIndicatorGfx,
    [PASSIVE_NULL_PD] = sNullPdIndicatorGfx,
};

const u16 gPassiveIndicatorPal[] = INCGFX_U16("graphics/battle_interface/passive_indicator.pal", ".gbapal"); // was static - needs to be visible from swsh_summary_screen.c too
const struct SpritePalette gSpritePalette_PassiveIndicator = {gPassiveIndicatorPal, TAG_PASSIVE_INDICATOR_PAL}; // was static
